Repository hashicorp/consul-k8s, pull requests merged in 2020-07, with the labels that each got.

#259 Extract http flags from consul/command pkg
  go.mod
  go.sum
  subcommand/acl-init/command.go
  subcommand/create-federation-secret/command.go
  subcommand/delete-completed-job/command.go
  subcommand/flags/flag_slice_value.go
  subcommand/flags/flag_slice_value_test.go
  subcommand/flags/flags.go
  subcommand/flags/http.go
  subcommand/flags/http_test.go
  subcommand/flags/k8s.go
  subcommand/flags/usage.go
  subcommand/flags/usage_test.go
  subcommand/get-consul-client-ca/command.go
  subcommand/inject-connect/command.go
  subcommand/lifecycle-sidecar/command.go
  subcommand/lifecycle-sidecar/command_test.go
  subcommand/server-acl-init/command.go
  subcommand/service-address/command.go
  subcommand/sync-catalog/command.go
Labels: area/infrastructure

#291 Update resources for lifecycle sidecar and init container for connect-inject
  connect-inject/container_init.go
  connect-inject/lifecycle_sidecar.go
Labels: bug, enhancement

#284 Fix tests
  .circleci/config.yml
  go.mod
  go.sum
  subcommand/lifecycle-sidecar/command_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/sync-catalog/command_test.go
Labels: area/infrastructure

#297 Respect allow/deny lists even when namespaces aren't enabled
  CHANGELOG.md
  connect-inject/handler.go
  connect-inject/handler_test.go
Labels: area/connect

#298 Allow init and lifecycle containers resource limits to be configured
  CHANGELOG.md
  connect-inject/container_init.go
  connect-inject/container_init_test.go
  connect-inject/handler.go
  connect-inject/lifecycle_sidecar.go
  connect-inject/lifecycle_sidecar_test.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: area/connect, enhancement

#300 Update lifecycle sidecar memory limit flag default value
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: area/connect

#301 Update changelog
  CHANGELOG.md
Labels: documentation
