Repository hashicorp/consul-k8s, pull requests merged in 2020-03, with the labels that each got.

#217 Inject-connect command: deprecate the -consul-ca-cert flag
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: area/connect

#208 Fix initial sync race
  catalog/to-consul/syncer.go
  catalog/to-consul/syncer_test.go
Labels: area/sync, bug

#230 Configure anonymous token policy for connect
  subcommand/server-acl-init/anonymous_token.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/dns.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
Labels: area/acls, area/multi-dc, enhancement

#234 Add new load-balancer-address command
  commands.go
  subcommand/load-balancer-address/command.go
  subcommand/load-balancer-address/command_test.go
Labels: area/multi-dc, enhancement

#232 Add -token-sink-file flag to acl-init
  subcommand/acl-init/command.go
  subcommand/acl-init/command_test.go
Labels: area/acls, area/multi-dc, enhancement

#235 load-balancer-address support for ClusterIP
  commands.go
  subcommand/service-address/command.go
  subcommand/service-address/command_test.go
Labels: area/multi-dc, enhancement

#211 Add get-consul-client-ca command
  commands.go
  go.mod
  helper/cert/source_gen.go
  helper/cert/source_gen_test.go
  helper/cert/tls_util.go
  subcommand/get-consul-client-ca/command.go
  subcommand/get-consul-client-ca/command_test.go
  subcommand/lifecycle-sidecar/command_test.go
  subcommand/server-acl-init/command_test.go
Labels: theme/tls
