Repository hashicorp/consul-k8s, pull requests merged in 2020-09, with the labels that each got.

#312 Feature/name k8s node
  CHANGELOG.md
  catalog/to-consul/resource.go
  catalog/to-consul/resource_test.go
  catalog/to-consul/syncer.go
  catalog/to-consul/syncer_test.go
  catalog/to-consul/testing.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/create_or_update.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
  subcommand/sync-catalog/command.go
  subcommand/sync-catalog/command_test.go
Labels: area/sync, enhancement

#321 Connect: only look for service account secrets when creating/updating auth method
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/connect_inject.go
  subcommand/server-acl-init/connect_inject_test.go
Labels: area/connect, theme/openshift

#322 Update ACLs for consul ent and controller
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
Labels: area/acls, enhancement, theme/crds

#323 Support Consul Ent NS's for CRDs
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_webhook_test.go
  catalog/to-consul/resource.go
  catalog/to-consul/syncer.go
  connect-inject/handler.go
  connect-inject/handler_ent_test.go
  controllers/servicedefaults_controller.go
  controllers/servicedefaults_controller_ent_test.go
  controllers/servicedefaults_controller_test.go
  go.mod
  namespaces/namespaces.go
  namespaces/namespaces_test.go
  subcommand/controller/command.go
  subcommand/delete-completed-job/command_test.go
  subcommand/flags/mapset.go
  subcommand/inject-connect/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/connect_inject.go
  subcommand/server-acl-init/create_or_update.go
  subcommand/sync-catalog/command.go
  subcommand/sync-catalog/command_ent_test.go
Labels: enhancement, theme/consul-namespaces, theme/crds

#320 Add defaults and validation for ServiceDefaults
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/servicedefaults_webhook.go
  api/v1alpha1/types.go
  hack/boilerplate.go.txt
Labels: area/connect, enhancement, theme/crds

#316 Provision webhooks with self-generated certs
  commands.go
  go.mod
  helper/cert/notify.go
  helper/cert/notify_test.go
  helper/cert/source.go
  subcommand/controller/command.go
  subcommand/controller/command_test.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
  subcommand/webhook-cert-manager/command.go
  subcommand/webhook-cert-manager/command_test.go
Labels: enhancement, theme/crds

#326 Ensure system recovers quickly from failures or drift in state
  subcommand/webhook-cert-manager/command.go
  subcommand/webhook-cert-manager/command_test.go
  subcommand/webhook-cert-manager/mocks/mocks.go
Labels: bug, theme/crds

#338 Ignore ProxyDefaultsValidator from deepcopy
  api/v1alpha1/proxydefaults_webhook.go
Labels: bug, theme/crds

#335 Update to latest serviceresolver code
  api/v1alpha1/serviceresolver_types.go
  api/v1alpha1/serviceresolver_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  go.mod
  go.sum
Labels: theme/crds

#340 Replace reflect.DeepEqual with gocmp.Equal
  api/v1alpha1/proxydefaults_types.go
  api/v1alpha1/proxydefaults_types_test.go
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/serviceresolver_types.go
  api/v1alpha1/serviceresolver_types_test.go
  api/v1alpha1/servicerouter_types.go
  api/v1alpha1/servicerouter_types_test.go
  api/v1alpha1/servicesplitter_types.go
  api/v1alpha1/servicesplitter_types_test.go
  go.mod
  go.sum
Labels: enhancement, theme/crds

#342 Refactor ent controller tests
  api/v1alpha1/proxydefaults_webhook.go
  api/v1alpha1/proxydefaults_webhook_test.go
  api/v1alpha1/servicedefaults_webhook.go
  api/v1alpha1/serviceresolver_webhook.go
  api/v1alpha1/servicerouter_webhook.go
  api/v1alpha1/servicesplitter_webhook.go
  controller/configentry_controller.go
  controller/configentry_controller_ent_test.go
  controller/configentry_controller_test.go
  controller/proxydefaults_controller.go
  controller/servicedefaults_controller.go
  controller/serviceresolver_controller.go
  controller/servicerouter_controller.go
  controller/servicesplitter_controller.go
  controllers/configentry_controller_ent_test.go
  subcommand/controller/command.go
Labels: enhancement, theme/crds
