Repository hashicorp/consul-k8s, pull requests merged in 2020-04, with the labels that each got.

#239 Update policies for namespaces
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
Labels: area/multi-dc, enhancement

#240 Changelog for wan-federation
  CHANGELOG.md
Labels: area/multi-dc

#223 Support acl replication across multiple dcs
  CHANGELOG.md
  commands.go
  subcommand/acl-init/command.go
  subcommand/acl-init/command_test.go
  subcommand/server-acl-init/anonymous_token.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/create_or_update.go
  subcommand/server-acl-init/dns.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
  subcommand/service-address/command.go
  subcommand/service-address/command_test.go
Labels: area/multi-dc, enhancement

#238 server-acl-init: Add -server-address and -server-port
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/servers.go
Labels: area/acls, enhancement

#233 Trim spaces before checking if an upstream is a prepared query
  connect-inject/container_init.go
  connect-inject/container_init_test.go
Labels: area/connect, bug

#243 Support external servers
  helper/go-discover/discover.go
  helper/go-discover/discover_test.go
  helper/go-discover/mocks/mock_provider.go
  subcommand/get-consul-client-ca/command.go
  subcommand/get-consul-client-ca/command_test.go
  subcommand/server-acl-init/anonymous_token.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/connect_inject.go
  subcommand/server-acl-init/create_or_update.go
  subcommand/server-acl-init/servers.go
  subcommand/sync-catalog/command_ent_test.go
Labels: area/acls, theme/external-servers

#248 Change perms from 0400 to 0600 for acl-token
  CHANGELOG.md
  subcommand/acl-init/command.go
  subcommand/acl-init/command_test.go
Labels: area/acls, bug
