Repository hashicorp/consul-k8s, pull requests merged in 2020-02, with the labels that each got.

#196 Update the lifecycle sidecar to shell out to Consul
  connect-inject/lifecycle_sidecar.go
  connect-inject/lifecycle_sidecar_test.go
  subcommand/lifecycle-sidecar/command.go
  subcommand/lifecycle-sidecar/command_test.go
Labels: enhancement, theme/consul-namespaces

#198 Fixes to the lifecycle sidecar cmd, plus tests
  .circleci/config.yml
  subcommand/lifecycle-sidecar/command.go
  subcommand/lifecycle-sidecar/command_test.go
Labels: area/connect

#200 Add namespace tests to the lifecycle sidecar command
  .circleci/config.yml
  subcommand/lifecycle-sidecar/command.go
  subcommand/lifecycle-sidecar/command_ent_test.go
  subcommand/lifecycle-sidecar/command_test.go
Labels: area/connect, theme/consul-namespaces

#199 Add tests for namespaces and acl bootstrapping
  .circleci/config.yml
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
Labels: theme/consul-namespaces

#204 Don't retry when context cancelled.
  catalog/to-consul/syncer.go
  catalog/to-consul/syncer_test.go
Labels: theme/consul-namespaces

#205 Support older versions of Consul in sync catalog
  catalog/to-consul/consul_node_services_client.go
  catalog/to-consul/consul_node_services_client_ent_test.go
  catalog/to-consul/consul_node_services_client_test.go
  catalog/to-consul/syncer.go
  catalog/to-consul/syncer_ent_test.go
  catalog/to-consul/syncer_test.go
  subcommand/sync-catalog/command.go
Labels: theme/consul-namespaces

#212 Format imports
  catalog/to-consul/syncer_ent_test.go
  catalog/to-consul/syncer_test.go
Labels: theme/consul-namespaces

#197 Support Consul namespaces in consul-k8s
  .circleci/config.yml
  Makefile
  catalog/to-consul/consul_node_services_client.go
  catalog/to-consul/consul_node_services_client_ent_test.go
  catalog/to-consul/consul_node_services_client_test.go
  catalog/to-consul/resource.go
  catalog/to-consul/resource_test.go
  catalog/to-consul/syncer.go
  catalog/to-consul/syncer_ent_test.go
  catalog/to-consul/syncer_test.go
  connect-inject/container_init.go
  connect-inject/container_init_test.go
  connect-inject/envoy_sidecar.go
  connect-inject/envoy_sidecar_test.go
  connect-inject/handler.go
  connect-inject/handler_ent_test.go
  connect-inject/handler_test.go
  go.mod
  go.sum
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
  subcommand/lifecycle-sidecar/command.go
  subcommand/lifecycle-sidecar/command_ent_test.go
  subcommand/lifecycle-sidecar/command_test.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_ent_test.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/connect_inject.go
  subcommand/server-acl-init/create_or_update.go
  subcommand/server-acl-init/dns.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
  subcommand/server-acl-init/servers.go
  subcommand/sync-catalog/command.go
  subcommand/sync-catalog/command_ent_test.go
  subcommand/sync-catalog/command_test.go
Labels: theme/consul-namespaces

#215 Update changelog with namespace details
  CHANGELOG.md
Labels: theme/consul-namespaces
