Repository hashicorp/consul-k8s, pull requests merged in 2020-10, with the labels that each got.

#343 Use metadata field from configEntry
  api/common/common.go
  api/common/configentry.go
  api/common/configentry_webhook_test.go
  api/v1alpha1/proxydefaults_types.go
  api/v1alpha1/proxydefaults_types_test.go
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/serviceresolver_types.go
  api/v1alpha1/serviceresolver_types_test.go
  api/v1alpha1/servicerouter_types.go
  api/v1alpha1/servicerouter_types_test.go
  api/v1alpha1/servicesplitter_types.go
  api/v1alpha1/servicesplitter_types_test.go
  api/v1alpha1/types.go
  controller/configentry_controller.go
  controller/configentry_controller_test.go
  go.mod
  go.sum
  subcommand/controller/command.go
  subcommand/controller/command_test.go
Labels: enhancement, theme/crds

#348 Add -log-level flag to controller
  go.mod
  subcommand/controller/command.go
  subcommand/controller/command_test.go
Labels: theme/crds

#333 Health checks base
  connect-inject/handler.go
  connect-inject/handler_test.go
  connect-inject/health_check_resource.go
  connect-inject/health_check_resource_test.go
  connect-inject/patch.go
  go.mod
  helper/controller/controller.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: enhancement, theme/health-checks

#363 Health Checks support for consul service mesh
  connect-inject/handler.go
  connect-inject/handler_test.go
  connect-inject/health_check_resource.go
  connect-inject/health_check_resource_test.go
  connect-inject/patch.go
  go.mod
  go.sum
  helper/controller/controller.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: enhancement, theme/health-checks

#362 Support Consul namespaces for service-intentions
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/serviceintentions_types.go
  api/v1alpha1/serviceintentions_types_test.go
  api/v1alpha1/serviceintentions_webhook.go
  api/v1alpha1/serviceintentions_webhook_test.go
  controller/configentry_controller.go
  controller/configentry_controller_ent_test.go
  go.mod
  subcommand/controller/command.go
Labels: bug, theme/crds
