Repository hashicorp/consul-k8s, pull requests merged in 2021-03, with the labels that each got.

#449 wait for serf check before starting the test
  connect-inject/cleanup_resource_ent_test.go
Labels: bug

#448 Add LastSyncedTime field on CRDs
  CHANGELOG.md
  api/common/configentry.go
  api/common/configentry_webhook_test.go
  api/v1alpha1/ingressgateway_types.go
  api/v1alpha1/ingressgateway_types_test.go
  api/v1alpha1/proxydefaults_types.go
  api/v1alpha1/proxydefaults_types_test.go
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/serviceintentions_types.go
  api/v1alpha1/serviceintentions_types_test.go
  api/v1alpha1/serviceresolver_types.go
  api/v1alpha1/serviceresolver_types_test.go
  api/v1alpha1/servicerouter_types.go
  api/v1alpha1/servicerouter_types_test.go
  api/v1alpha1/servicesplitter_types.go
  api/v1alpha1/servicesplitter_types_test.go
  api/v1alpha1/status.go
  api/v1alpha1/terminatinggateway_types.go
  api/v1alpha1/terminatinggateway_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  controller/configentry_controller.go
Labels: enhancement, theme/crds

#452 add service registration polling to connect-init
  connect-inject/container_init.go
  connect-inject/container_init_test.go
  subcommand/common/test_util.go
  subcommand/connect-init/command.go
  subcommand/connect-init/command_test.go
Labels: area/connect, theme/tproxy

#460 add wait to test to prevent race on ACL read
  namespaces/namespaces_test.go
Labels: bug

#459 add tls support and tests to connect-init command
  namespaces/namespaces_test.go
  subcommand/common/test_util.go
  subcommand/connect-init/command_test.go
  subcommand/create-federation-secret/command_test.go
  subcommand/get-consul-client-ca/command_test.go
  subcommand/server-acl-init/command_test.go
Labels: enhancement, theme/tproxy

#455 Endpoints controller with tests
  connect-inject/container_init.go
  connect-inject/endpoints_controller.go
  connect-inject/endpoints_controller_test.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
Labels: theme/tproxy

#461 tproxy use quotes in ServicesWithFilter's filter
  subcommand/connect-init/command.go
  subcommand/connect-init/command_test.go
Labels: bug, theme/tproxy

#465 Tproxy writefile changes
  subcommand/common/common.go
  subcommand/common/common_test.go
  subcommand/connect-init/command.go
  subcommand/connect-init/command_test.go
Labels: bug, theme/tproxy
