Repository hashicorp/consul-k8s, pull requests merged in 2021-04, with the labels that each got.

#470 Add acls and tls to endpoints controller
  connect-inject/endpoints_controller.go
  connect-inject/endpoints_controller_test.go
  subcommand/inject-connect/command.go
Labels: area/acls, enhancement, theme/tproxy

#476 tproxy remove cleanup controller
  connect-inject/cleanup_resource.go
  connect-inject/cleanup_resource_ent_test.go
  connect-inject/cleanup_resource_test.go
  subcommand/inject-connect/command.go
  subcommand/inject-connect/command_test.go
  subcommand/server-acl-init/command.go
  subcommand/server-acl-init/command_test.go
  subcommand/server-acl-init/rules.go
  subcommand/server-acl-init/rules_test.go
Labels: theme/tproxy

#479 Add HA support to endpoints controller
  subcommand/inject-connect/command.go
Labels: enhancement, theme/tproxy

#477 change the annotationInject key since its a label as well now
  connect-inject/annotations.go
  connect-inject/cleanup_resource.go
  connect-inject/cleanup_resource_ent_test.go
  connect-inject/cleanup_resource_test.go
  connect-inject/endpoints_controller.go
  connect-inject/endpoints_controller_test.go
  connect-inject/handler.go
  connect-inject/handler_test.go
Labels: theme/tproxy

#480 remove processing of pods in PodPending phase in endpoints controller
  connect-inject/endpoints_controller.go
Labels: bug, theme/tproxy

#475 Support Consul ENT Namespaces in the endpoints controller
  connect-inject/container_init.go
  connect-inject/container_init_test.go
  connect-inject/endpoints_controller.go
  connect-inject/endpoints_controller_ent_test.go
  connect-inject/endpoints_controller_test.go
  go.mod
  subcommand/common/common.go
  subcommand/common/common_test.go
  subcommand/connect-init/command.go
  subcommand/connect-init/command_ent_test.go
  subcommand/inject-connect/command.go
Labels: enhancement, theme/tproxy

#495 Allow unstructured schema for the ProxyDefaults CRD
  CHANGELOG.md
  api/v1alpha1/proxydefaults_types.go
  config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
Labels: bug, theme/crds

#493 use rootless containers where possible
  CHANGELOG.md
  connect-inject/container_init.go
  connect-inject/container_init_test.go
  connect-inject/envoy_sidecar.go
  connect-inject/envoy_sidecar_test.go
  connect-inject/handler.go
Labels: theme/tproxy

#485 Add support for field TransparentProxy to SvcDefaults and ProxyDefaults
  .circleci/config.yml
  api/v1alpha1/ingressgateway_webhook.go
  api/v1alpha1/proxydefaults_types.go
  api/v1alpha1/proxydefaults_types_test.go
  api/v1alpha1/proxydefaults_webhook.go
  api/v1alpha1/proxydefaults_webhook_test.go
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/servicedefaults_webhook.go
  api/v1alpha1/serviceintentions_webhook.go
  api/v1alpha1/serviceresolver_webhook.go
  api/v1alpha1/servicerouter_webhook.go
  api/v1alpha1/servicesplitter_webhook.go
  api/v1alpha1/terminatinggateway_webhook.go
  api/v1alpha1/types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  config/webhook/manifests.yaml
  connect-inject/endpoints_controller_ent_test.go
  connect-inject/endpoints_controller_test.go
  controller/configentry_controller_ent_test.go
  controller/configentry_controller_test.go
Labels: enhancement, theme/crds, theme/tproxy

#503 Update health check status based on the endpoints object instead of pod
  CHANGELOG.md
  connect-inject/endpoints_controller.go
  connect-inject/endpoints_controller_test.go
Labels: area/connect, bug

#501 use hclog instead of UI logging for connect-init
  subcommand/connect-init/command.go
  subcommand/connect-init/command_test.go
Labels: enhancement, theme/tproxy

#502 Update service defaults
  api/v1alpha1/proxydefaults_types.go
  api/v1alpha1/servicedefaults_types.go
  api/v1alpha1/servicedefaults_types_test.go
  api/v1alpha1/types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
Labels: enhancement, theme/tproxy
