Repository hashicorp/consul-k8s, pull requests merged in 2022-08, with the labels that each got.

#1271 Feature Branch: `consul-k8s` Envoy Debugging
  CHANGELOG.md
  acceptance/framework/cli/cli.go
  acceptance/framework/consul/cli_cluster.go
  acceptance/tests/connect/connect_inject_test.go
  cli/cmd/install/install.go
  cli/cmd/proxy/command.go
  cli/cmd/proxy/list/command.go
  cli/cmd/proxy/list/command_test.go
  cli/cmd/proxy/read/command.go
  cli/cmd/proxy/read/command_test.go
  cli/cmd/proxy/read/config.go
  cli/cmd/proxy/read/config_test.go
  cli/cmd/proxy/read/envoy_types.go
  cli/cmd/proxy/read/filters.go
  cli/cmd/proxy/read/filters_test.go
  cli/cmd/proxy/read/format.go
  cli/cmd/proxy/read/format_test.go
  cli/cmd/proxy/read/test_clusters.json
  cli/cmd/proxy/read/test_config_dump.json
  cli/cmd/status/status.go
  cli/cmd/uninstall/uninstall.go
  cli/cmd/uninstall/uninstall_test.go
  cli/cmd/upgrade/upgrade.go
  cli/cmd/version/version.go
  cli/commands.go
  cli/common/base.go
  cli/common/flag/set.go
  cli/common/portforward.go
  cli/common/portforward_test.go
  cli/common/terminal/basic.go
  cli/common/terminal/table.go
  cli/common/terminal/ui.go
  cli/go.mod
  cli/go.sum
Labels: area/cli

#1422 Update the sed match to replace image
  control-plane/build-support/functions/10-util.sh
Labels: type/bug

#1446 CNI Acceptance test on GKE
  .circleci/config.yml
  acceptance/framework/config/config.go
  acceptance/framework/flags/flags.go
  charts/consul/templates/cni-clusterrole.yaml
  charts/consul/templates/cni-podsecuritypolicy.yaml
Labels: theme/kubernetes, theme/testing

#1449 CNI acceptance tests on AKS
  .circleci/config.yml
Labels: theme/kubernetes, theme/testing

#1431 Kubernetes 1.24 support
  .circleci/config.yml
  CHANGELOG.md
  README.md
  acceptance/framework/k8s/kubectl.go
  acceptance/framework/vault/vault_cluster.go
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/multiport-app/secret.yaml
  acceptance/tests/vault/vault_partitions_test.go
  acceptance/tests/vault/vault_wan_fed_test.go
  charts/consul/Chart.yaml
  charts/consul/templates/auth-method-secret.yaml
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/test/unit/auth-method-secret.bats
  charts/consul/test/unit/connect-inject-clusterrole.bats
  control-plane/connect-inject/mesh_webhook.go
  control-plane/connect-inject/mesh_webhook_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/connect_inject_test.go
Labels: type/enhancement, theme/kubernetes

#1462 api-gateway: configure ACL auth appropriately in secondary dc
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: area/chart-only, theme/federation, theme/api-gateway
