Repository hashicorp/consul-k8s, pull requests merged in 2022-06, with the labels that each got.

#1254 Add consul-version flag to acceptance test framework
  acceptance/framework/config/config.go
  acceptance/framework/flags/flags.go
  acceptance/tests/vault/vault_namespaces_test.go
  acceptance/tests/vault/vault_partitions_test.go
  acceptance/tests/vault/vault_test.go
  acceptance/tests/vault/vault_tls_auto_reload_test.go
  acceptance/tests/vault/vault_wan_fed_test.go
Labels: theme/testing

#1257 Add topology spread constraints to mesh term and ingress gw
  CHANGELOG.md
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/values.yaml
Labels: type/enhancement, area/chart-only

#1261 Expose new options for API Gateway's High Availability feature
  CHANGELOG.md
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/test/unit/api-gateway-gatewayclassconfig.bats
  charts/consul/values.yaml
Labels: area/chart-only, theme/api-gateway

#1274 update changelog to note breaking change for Envoy images.
  CHANGELOG.md
Labels: documentation

#1298 use anchor link alias for TOC
  hack/helm-reference-gen/fixtures/full-values.golden
  hack/helm-reference-gen/main.go
  hack/helm-reference-gen/main_test.go
Labels: documentation

#1311 fix a broken link in values.yaml
  charts/consul/values.yaml
Labels: documentation

#775 Add custom annotations support for catalog sync and connectInject pods via Helm
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/values.yaml
Labels: hacktoberfest-accepted

#1315 Add annotations to support specifying userVolumes and userVolumeMounts for the envoy sidecar
  CHANGELOG.md
  control-plane/connect-inject/annotations.go
  control-plane/connect-inject/envoy_sidecar.go
  control-plane/connect-inject/envoy_sidecar_test.go
  control-plane/connect-inject/mesh_webhook.go
  control-plane/connect-inject/mesh_webhook_ent_test.go
  control-plane/connect-inject/mesh_webhook_test.go
Labels: type/enhancement, theme/telemetry
