Repository hashicorp/consul-k8s, pull requests merged in 2022-03, with the labels that each got.

#1066 Correcting paths to accpetance tests.
  CONTRIBUTING.md
Labels: documentation

#995 Use kube auth method to provision ACL token for the crd controller
  .circleci/config.yml
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/connect-inject-clusterrolebinding.yaml
  charts/consul/templates/connect-inject-serviceaccount.yaml
  charts/consul/templates/controller-deployment.yaml
  charts/consul/templates/server-acl-init-role.yaml
  charts/consul/test/unit/connect-inject-clusterrole.bats
  charts/consul/test/unit/connect-inject-clusterrolebinding.bats
  charts/consul/test/unit/connect-inject-serviceaccount.bats
  charts/consul/test/unit/controller-deployment.bats
  control-plane/commands.go
  control-plane/helper/test/test_util.go
  control-plane/subcommand/acl-init/command.go
  control-plane/subcommand/acl-init/command_test.go
  control-plane/subcommand/common/common.go
  control-plane/subcommand/common/common_test.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/consul-logout/command.go
  control-plane/subcommand/consul-logout/command_test.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/connect_inject_test.go
  control-plane/subcommand/server-acl-init/create_or_update.go
Labels: area/acls, vault

#1089 Rename controller flag in server-acl-init to `-controller`
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_test.go
Labels: area/acls

#1086 Migrate most of build-and-test CircleCI jobs to Github Actions
  .circleci/config.yml
  .github/workflows/build-and-test.yml
  .github/workflows/golangci-lint-acceptance.yml
  .github/workflows/golangci-lint-cli.yml
  .github/workflows/golangci-lint-control-plane.yml
  .github/workflows/reusable-acceptance.yml
  .github/workflows/reusable-golangci-lint.yml
  .github/workflows/reusable-unit.yml
  .golangci.yml
  control-plane/Makefile
Labels: area/infrastructure

#1092 Allow API Gateway controller to get Namespaces
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-clusterrole.yaml
Labels: area/chart-only

#1099 Use SHA instead of latest for acceptance tests
  .circleci/config.yml
Labels: area/infrastructure

#1103 bug: exec'ing into consul server container no longer works when tls is enabled
  acceptance/tests/vault/vault_test.go
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: type/bug

#1121 [CRT] Add required version support
  .github/workflows/build-and-test.yml
  .go-version
  Makefile
  control-plane/build-support/scripts/version.sh
Labels: area/infrastructure

#1104 Don't set TTL for server certs when using Vault
  CHANGELOG.md
  charts/consul/templates/_helpers.tpl
  charts/consul/test/unit/server-statefulset.bats
Labels: type/bug

#1113 Enable snapshot agent configuration to be retrieved from vault
  CHANGELOG.md
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/client-snapshot-agent-deployment.yaml
  charts/consul/test/unit/client-snapshot-agent-deployment.bats
  charts/consul/values.yaml
Labels: vault

#1118 Enable ingress gateways to use ACL Auth Method
  acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
  acceptance/tests/ingress-gateway/ingress_gateway_test.go
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/ingress-gateways-podsecuritypolicy.yaml
  charts/consul/templates/ingress-gateways-role.yaml
  charts/consul/templates/ingress-gateways-rolebinding.yaml
  charts/consul/templates/ingress-gateways-service.yaml
  charts/consul/templates/ingress-gateways-serviceaccount.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/ingress-gateways-podsecuritypolicy.bats
  charts/consul/test/unit/ingress-gateways-role.bats
  charts/consul/test/unit/ingress-gateways-rolebinding.bats
  charts/consul/test/unit/ingress-gateways-service.bats
  charts/consul/test/unit/ingress-gateways-serviceaccount.bats
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_test.go
Labels: area/acls
