Repository hashicorp/consul-k8s, pull requests merged in 2022-11, with the labels that each got.

#1656 Add PodSecurityPolicy for Consul API Gateway controller
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-clusterrole.yaml
  charts/consul/templates/api-gateway-controller-podsecuritypolicy.yaml
  charts/consul/test/unit/api-gateway-controller-clusterrole.bats
  charts/consul/test/unit/api-gateway-controller-podsecuritypolicy.bats
Labels: area/chart-only, theme/api-gateway, backport/0.49.x

#1650 Consul API Gateway, Add Tolerations support
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/values.yaml
Labels: backport/0.49.x

#1662 Mw/circle ci stable release testing
  .circleci/config.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
Labels: backport/0.49.x

#1672 api-gateway: allow controller to bind PodSecurityPolicy to ServiceAccounts that it creates
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-clusterrole.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/api-gateway-podsecuritypolicy.yaml
  charts/consul/test/unit/api-gateway-controller-clusterrole.bats
Labels: area/chart-only, theme/api-gateway, backport/0.49.x

#1691 Add support for maxConnections, maxConcurrentRequests, and maxPendingRequests to IngressGateway CRD
  CHANGELOG.md
  charts/consul/templates/crd-ingressgateways.yaml
  control-plane/api/v1alpha1/ingressgateway_types.go
  control-plane/api/v1alpha1/ingressgateway_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
Labels: backport/0.49.x

#1722 fix release step by adding config for promote staging
  .release/ci.hcl
Labels: backport/0.49.x

#1725 Dockerfile: bump up ubi-minimal image to 9.1
  CHANGELOG.md
  control-plane/Dockerfile
Labels: backport/0.49.x

#1743 Add fix for api-gateway when using system-wide trusted CAs for external servers
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: backport/1.0.x

#1749 add go-discover binary to control-plane image
  CHANGELOG.md
  control-plane/Dockerfile
Labels: backport/1.0.x

#1756 Add support for setting the namespace that the CNI plugin is installed
  CHANGELOG.md
  charts/consul/templates/cni-clusterrole.yaml
  charts/consul/templates/cni-clusterrolebinding.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/cni-networkattachmentdefinition.yaml
  charts/consul/templates/cni-podsecuritypolicy.yaml
  charts/consul/templates/cni-resourcequota.yaml
  charts/consul/templates/cni-securitycontextconstraints.yaml
  charts/consul/templates/cni-serviceaccount.yaml
  charts/consul/test/unit/cni-clusterrole.bats
  charts/consul/test/unit/cni-clusterrolebinding.bats
  charts/consul/test/unit/cni-daemonset.bats
  charts/consul/test/unit/cni-networkattachmentdefinition.bats
  charts/consul/test/unit/cni-podsecuritypolicy.bats
  charts/consul/test/unit/cni-resourcequota.bats
  charts/consul/test/unit/cni-securitycontextcontstraints.bats
  charts/consul/test/unit/cni-serviceaccount.bats
  charts/consul/values.yaml
Labels: area/chart-only

#1753 Fix TLS Cert when using `enableAutoEncrypt`
  CHANGELOG.md
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: area/chart-only, theme/api-gateway, backport/1.0.x
