Repository hashicorp/consul-k8s, pull requests merged in 2023-04, with the labels that each got.

#2037 Fix the indentation of the copyAnnotations example
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2030 add failover policy to service resolver and proxy default
  .changelog/2030.txt
  .circleci/config.yml
  .github/workflows/test.yml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  control-plane/api/v1alpha1/proxydefaults_types.go
  control-plane/api/v1alpha1/proxydefaults_types_test.go
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/shared_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2046 Convert acceptance to use github actions
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-acceptance.yml
  .github/workflows/reusable-golangci-lint.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/helpers.go
  acceptance/framework/k8s/kubectl.go
  acceptance/framework/portforward/port_forward.go
  acceptance/framework/vault/vault_cluster.go
  acceptance/tests/config-entries/config_entries_namespaces_test.go
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/consul-dns/consul_dns_test.go
  acceptance/tests/metrics/metrics_test.go
  acceptance/tests/partitions/partitions_sync_test.go
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/eks/main.tf
  charts/consul/test/terraform/gke/main.tf
  charts/consul/test/terraform/gke/variables.tf
  control-plane/subcommand/connect-init/command_test.go
  control-plane/subcommand/consul-logout/command_test.go
  control-plane/subcommand/create-federation-secret/command_test.go
  control-plane/subcommand/get-consul-client-ca/command_test.go
Labels: pr/no-changelog, pr/no-backport

#2050 Remove CircleCI
  .circleci/config.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2057 Sync GHA release 1.0.x from main
  .circleci/config.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-acceptance.yml
  .github/workflows/reusable-golangci-lint.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2058 Sync GHA release 0.49.x from main
  .circleci/config.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-acceptance.yml
  .github/workflows/reusable-golangci-lint.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2047 Update backport assistant to support -gh-automerge
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#2059 Add a cleanup cron job
  .github/workflows/nightly-cleanup.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2063 Backport ACL error changes
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2072 Supply chain updates for Github Actions
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-cleanup.yml
  .github/workflows/pr.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2068 Fix Sync Catalog ACL Token Environment Var Name
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/test/unit/sync-catalog-deployment.bats
Labels: backport/1.0.x, backport/1.1.x

#2080 Add changelog for NET 2422
  .changelog/2068.txt
Labels: backport/1.0.x, backport/1.1.x

#2081 Backport of Add changelog for NET 2422 into release/1.0.x
  .changelog/2068.txt
Labels: pr/no-changelog

#2082 Backport of Add changelog for NET 2422 into release/1.1.x
  .changelog/2068.txt
Labels: pr/no-changelog

#2070 APIGW Resource Translation
  control-plane/api-gateway/consul/config_entry_translation.go
  control-plane/api-gateway/consul/config_entry_translation_test.go
  control-plane/api-gateway/controllers/gateway_class_config_controller.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2083 Adjust API gateway controller deployment appropriately when Vault configured as secrets backend
  .changelog/2083.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: backport/1.0.x, backport/1.1.x

#2093 Set Consul Server Locality From Node Label
  .changelog/2093.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/server-clusterrole.yaml
  charts/consul/templates/server-clusterrolebinding.yaml
  charts/consul/templates/server-statefulset.yaml
  control-plane/commands.go
  control-plane/subcommand/fetch-server-region/command.go
  control-plane/subcommand/fetch-server-region/command_test.go
Labels: pr/no-backport

#2090 APIGW4CONK8s: TCPRoute Translation
  control-plane/api-gateway/consul/config_entry_translation.go
  control-plane/api-gateway/consul/config_entry_translation_test.go
Labels: theme/api-gateway

#2086 add sameness group to service resolver, update manifests
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/fixtures/bases/crds-oss/serviceresolver.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2097 add sameness group to source intention
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  control-plane/api/v1alpha1/serviceintentions_types.go
  control-plane/api/v1alpha1/serviceintentions_types_test.go
  control-plane/api/v1alpha1/shared_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport
