Repository hashicorp/consul-k8s, pull requests merged in 2023-05, with the labels that each got.

#2099 Updates GatewayClassConfig Controller to use common finalizer methods
  control-plane/api-gateway/controllers/gateway_class_config_controller.go
Labels: theme/api-gateway, pr/no-changelog

#2102 security: update Go version to 1.20.4
  .changelog/2102.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x

#2104 Manual Backport of security: update Go version to 1.20.4 (#2102)
  .changelog/2104.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2108 Security: update Go version to 1.19.9
  .changelog/2108.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/Dockerfile
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/0.49.x, pr/no-changelog

#2110 Manual Backport of security: update Go version to 1.19.9 (#2108)
  .changelog/2110.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/connect-inject/endpoints_controller_ent_test.go
  control-plane/connect-inject/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/install-cni/cniconfig.go
Labels: pr/no-changelog, pr/no-backport

#2105 chore(ci): fix changelog action for non-main base branches
  .github/workflows/changelog-checker.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2113 chore(ci): fix backport assistant not finding new branches
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#2116 Manual Backport: fix backport assistant not finding new branches
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#2114 Manual Backport: Update Backport Assistant and Changelog Checker
  .github/workflows/backport.yml
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog, pr/no-backport

#2088 APIGW4CONK8S: HTTP Route/TCPRoute/Secrets Translation
  control-plane/api-gateway/consul/config_entry_translation.go
  control-plane/api-gateway/consul/config_entry_translation_test.go
  control-plane/api-gateway/translation/config_entry_translation.go
  control-plane/api-gateway/translation/config_entry_translation_test.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2091 Net 3508/gateway controller
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_test.go
  control-plane/api-gateway/controllers/index.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway, pr/no-changelog

#2043 Customizing Vault Version for WanFed Test
  acceptance/framework/config/config.go
  acceptance/framework/flags/flags.go
  acceptance/framework/vault/vault_cluster.go
Labels: pr/no-changelog, pr/no-backport

#2078 add config read command
  .changelog/2078.txt
  cli/cmd/config/command.go
  cli/cmd/config/read/command.go
  cli/cmd/config/read/command_test.go
  cli/commands.go
Labels: backport/1.0.x, backport/1.1.x

#2100 Update CRDs for Permissive mTLS
  .changelog/2100.txt
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  control-plane/api/v1alpha1/mesh_types.go
  control-plane/api/v1alpha1/mesh_types_test.go
  control-plane/api/v1alpha1/proxydefaults_types.go
  control-plane/api/v1alpha1/proxydefaults_types_test.go
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/shared_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
Labels: pr/no-backport

#1808 add HOST_IP to mesh-gateway
  .changelog/1808.txt
  charts/consul/templates/mesh-gateway-deployment.yaml
Labels: backport/1.0.x, backport/1.1.x

#2127 chore(ci): fix typo in changelog checker
  .github/workflows/changelog-checker.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2133 Manual backport of #2078
  .changelog/2078.txt
  cli/cmd/config/command.go
  cli/cmd/config/read/command.go
  cli/cmd/config/read/command_test.go
  cli/commands.go
Labels: pr/no-backport

#2118 APIGW4CONK8s: Add Consul Cache
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/translation/config_entry_translation.go
  control-plane/api-gateway/translation/config_entry_translation_test.go
  control-plane/api-gateway/translation/k8s_cache_translation.go
  control-plane/api-gateway/translation/k8s_cache_translation_test.go
  control-plane/cache/consul.go
  control-plane/cache/consul_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway

#2126 APIGW4CONK8S: Serialize the GatewayClassConfig onto the Gateway for easier retrieval
  control-plane/api-gateway/controllers/gateway_class_serializer.go
  control-plane/api-gateway/controllers/gateway_class_serializer_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/cache/consul_test.go
Labels: theme/api-gateway

#2140 feat: update dataplane and consul images for 1.0.7 release
  .changelog/2140.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#2146 GHA: Get the consul version from values.yaml
  Makefile
  control-plane/build-support/scripts/consul-version.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2151 Prep release 0.49.6
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2150 Prep release 1.0.7
  CHANGELOG.md
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2145 Stub out where the openshift role info will go
  control-plane/api-gateway/gatekeeper/role.go
Labels: theme/api-gateway

#2154 set dev mode 1.0.8
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2155 set dev mode 0.49.7
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2142 [API Gateway] API Gateway Binding Logic
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api-gateway/binding/annotations.go
  control-plane/api-gateway/binding/annotations_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/references.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/binding/setter.go
  control-plane/api-gateway/binding/setter_test.go
  control-plane/api-gateway/binding/snapshot.go
  control-plane/api-gateway/binding/utils.go
  control-plane/api-gateway/binding/utils_test.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/controllers/gateway_class_config_controller_test.go
  control-plane/api-gateway/controllers/gateway_class_serializer.go
  control-plane/api-gateway/controllers/gateway_class_serializer_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_test.go
  control-plane/api-gateway/controllers/gatewayclass_controller_test.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/translation/config_entry_translation.go
  control-plane/api-gateway/translation/config_entry_translation_test.go
  control-plane/cache/consul.go
  control-plane/cache/consul_test.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway

#2161 Basic API gateway acceptance testing
  acceptance/framework/consul/helm_cluster_test.go
  acceptance/framework/environment/environment.go
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/api-gateway/main_test.go
  acceptance/tests/fixtures/bases/api-gateway/apigateway.yaml
  acceptance/tests/fixtures/bases/api-gateway/gatewayclass.yaml
  acceptance/tests/fixtures/bases/api-gateway/gatewayclassconfig.yaml
  acceptance/tests/fixtures/bases/api-gateway/httproute.yaml
  acceptance/tests/fixtures/bases/api-gateway/kustomization.yaml
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/catalog/to-consul/resource_test.go
  control-plane/controllers/configentry_controller_test.go
  control-plane/controllers/samenessgroups_controller.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway

#2157 Update go-discover
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2170 add helm chart values to configure global server side rate limiting
  .changelog/2170.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2173 Net 4124/handle syncing consul lifecycle events
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/cache/consul.go
  control-plane/cache/consul_test.go
Labels: theme/api-gateway

#2169 Net 4125/hookup gatekeeper with snapshot
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/snapshot.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_test.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/role.go
  control-plane/api-gateway/gatekeeper/service.go
  control-plane/api-gateway/gatekeeper/serviceaccount.go
Labels: theme/api-gateway

#2176 Disable DNS redirection when tproxy is disabled
  .changelog/2176.txt
  acceptance/tests/connect/connect_inject_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
Labels: backport/1.0.x, backport/1.1.x

#2160 fix json tags for fields 1.1.x
  .changelog/2160.txt
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/values.yaml
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
Labels: pr/no-backport

#2181 Fix tests
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
Labels: pr/no-changelog, pr/no-backport

#2179 Fix crd loading
  charts/consul/crds/kustomization.yaml
  charts/embed_chart.go
  cli/helm/chart.go
  cli/helm/chart_test.go
  cli/helm/test_fixtures/consul/crds/foo.yaml
Labels: theme/api-gateway

#2189 Update consul image so that acceptance tests run
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2180 Update consul image on prepare-dev and prepare-release
  .github/workflows/pr.yml
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  control-plane/build-support/functions/10-util.sh
  control-plane/build-support/scripts/consul-version.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2193 Fix dev mode on main
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2159 fix json tags for fields 1.0.x
  .changelog/2159.txt
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/values.yaml
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
Labels: pr/no-backport

#2183 Fix CVEs by updating controller-runtime
  .changelog/2183.txt
  control-plane/api/common/configentry_webhook_test.go
  control-plane/api/v1alpha1/exportedservices_webhook_test.go
  control-plane/api/v1alpha1/mesh_webhook_test.go
  control-plane/api/v1alpha1/peeringacceptor_webhook_test.go
  control-plane/api/v1alpha1/peeringdialer_webhook_test.go
  control-plane/api/v1alpha1/proxydefaults_webhook_test.go
  control-plane/api/v1alpha1/serviceintentions_webhook_test.go
  control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhook/redirect_traffic_test.go
  control-plane/controllers/configentry_controller_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.0.x, backport/1.1.x

#2156 Adding support for idleTimeout in Service Router spec
  charts/consul/templates/crd-servicerouters.yaml
  control-plane/api/v1alpha1/servicerouter_types.go
  control-plane/api/v1alpha1/servicerouter_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2200 Changelog: add support for idleTimeout in Service Router config
  .changelog/2156.txt
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2204 build(deps): update controller UBI base to 9.2
  .changelog/2204.txt
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#2205 update cloud preset to enable telemetry collector
  .changelog/2205.txt
  charts/consul/values.yaml
  cli/preset/cloud_preset.go
  cli/preset/cloud_preset_test.go
Labels: backport/1.0.x, backport/1.1.x

#2195 Consul Telemetry acceptance test
  .changelog/2195.txt
  acceptance/framework/config/config.go
  acceptance/framework/flags/flags.go
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/main_test.go
  acceptance/tests/fixtures/bases/cloud/hcp-mock/deployment.yaml
  acceptance/tests/fixtures/bases/cloud/hcp-mock/kustomization.yaml
  acceptance/tests/fixtures/bases/cloud/hcp-mock/service.yaml
  acceptance/tests/fixtures/bases/cloud/hcp-mock/serviceaccount.yaml
  acceptance/tests/fixtures/bases/static-server/deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/telemetry-collector-service.yaml
  charts/consul/templates/telemetry-collector-serviceaccount.yaml
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/telemetry-collector-service.bats
  charts/consul/test/unit/telemetry-collector-serviceaccount.bats
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x

#2194 Fix bug on service intention CRDs causing missed updates
  .changelog/2194.txt
  control-plane/api/v1alpha1/serviceintentions_types.go
  control-plane/api/v1alpha1/serviceintentions_types_test.go
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#2209 Add CRD for jwt-provider config entry
  .changelog/2209.txt
  CONTRIBUTING.md
  Makefile
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/fixtures/bases/crds-oss/jwtprovider.yaml
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/connect-inject-mutatingwebhookconfiguration.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  control-plane/PROJECT
  control-plane/api/common/common.go
  control-plane/api/v1alpha1/jwtprovider_types.go
  control-plane/api/v1alpha1/jwtprovider_types_test.go
  control-plane/api/v1alpha1/jwtprovider_webhook.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
  control-plane/controllers/configentry_controller_test.go
  control-plane/controllers/jwtprovider_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-backport

#2201 API Gateway tenancy tests + fixes
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/api-gateway/apigateway.yaml
  acceptance/tests/fixtures/bases/api-gateway/certificate.yaml
  acceptance/tests/fixtures/cases/api-gateways/certificate/certificate.yaml
  acceptance/tests/fixtures/cases/api-gateways/certificate/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/gateway/gateway.yaml
  acceptance/tests/fixtures/cases/api-gateways/gateway/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/httproute/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/httproute/route.yaml
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/gateway-gatewayclass.yaml
  control-plane/api-gateway/binding/annotations.go
  control-plane/api-gateway/binding/annotations_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/reference_grant.go
  control-plane/api-gateway/binding/reference_grant_test.go
  control-plane/api-gateway/binding/references.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/binding/setter.go
  control-plane/api-gateway/binding/setter_test.go
  control-plane/api-gateway/binding/snapshot.go
  control-plane/api-gateway/binding/utils.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/cache/gateway.go
  control-plane/api-gateway/cache/kubernetes.go
  control-plane/api-gateway/cache/subscription.go
  control-plane/api-gateway/common/constants.go
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/finalizers.go
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/common/helpers.go
  control-plane/api-gateway/common/helpers_test.go
  control-plane/api-gateway/common/labels.go
  control-plane/api-gateway/common/reference.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/secrets.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_test.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/api-gateway/gatekeeper/role.go
  control-plane/api-gateway/gatekeeper/service.go
  control-plane/api-gateway/gatekeeper/serviceaccount.go
  control-plane/api-gateway/translation/config_entry_translation.go
  control-plane/api-gateway/translation/k8s_cache_translation.go
  control-plane/api-gateway/translation/k8s_cache_translation_test.go
  control-plane/connect-inject/constants/constants.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2213 Update ServiceIntentions CRD for JWT auth
  .changelog/2213.txt
  charts/consul/templates/crd-serviceintentions.yaml
  control-plane/api/v1alpha1/serviceintentions_types.go
  control-plane/api/v1alpha1/serviceintentions_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
Labels: pr/no-backport

#2224 Fix setting args for the telemetry-collector
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2226 Fix NET-704 CVEs (backport to 1.1.x)
  .changelog/2226.txt
  control-plane/api/common/configentry_webhook_test.go
  control-plane/api/v1alpha1/exportedservices_webhook_test.go
  control-plane/api/v1alpha1/mesh_webhook_test.go
  control-plane/api/v1alpha1/peeringacceptor_webhook_test.go
  control-plane/api/v1alpha1/peeringdialer_webhook_test.go
  control-plane/api/v1alpha1/proxydefaults_webhook_test.go
  control-plane/api/v1alpha1/serviceintentions_webhook_test.go
  control-plane/catalog/to-consul/resource_test.go
  control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/mesh_webhook_ent_test.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhook/redirect_traffic_test.go
  control-plane/controller/configentry_controller.go
  control-plane/controller/configentry_controller_ent_test.go
  control-plane/controller/configentry_controller_test.go
  control-plane/controller/exportedservices_controller.go
  control-plane/controller/exportedservices_controller_ent_test.go
  control-plane/controller/ingressgateway_controller.go
  control-plane/controller/mesh_controller.go
  control-plane/controller/proxydefaults_controller.go
  control-plane/controller/servicedefaults_controller.go
  control-plane/controller/serviceintentions_controller.go
  control-plane/controller/serviceresolver_controller.go
  control-plane/controller/servicerouter_controller.go
  control-plane/controller/servicesplitter_controller.go
  control-plane/controller/terminatinggateway_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/controller/controller.go
  control-plane/subcommand/common/common.go
Labels: pr/no-backport
