Repository hashicorp/consul-k8s, pull requests merged in 2023-07, with the labels that each got.

#2470 ci: fix eks terraform quota error by cleaning up oidc providers
  hack/aws-acceptance-test-cleanup/main.go
Labels: pr/no-changelog, pr/no-backport

#2511 build: update versions to 1.3.0-dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2514 Add connectInject.prepareDataplanesUpgrade value
  .changelog/2514.txt
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2526 docs: self service changelog instructions
  .github/pull_request_template.md
Labels: pr/no-changelog, pr/no-backport

#2525 feat: adding security context and annotations to tls and acl init/cleanup jobs
  .changelog/2525.txt
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/tls-init-cleanup-job.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/test/unit/gateway-cleanup-job.bats
  charts/consul/test/unit/gateway-resources-job.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/tls-init-cleanup-job.bats
  charts/consul/test/unit/tls-init-job.bats
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2520 NET-4813: Fix issue where virtual IP saving had insufficient ACLs.
  .changelog/2520.txt
  acceptance/framework/connhelper/connect_helper.go
  acceptance/tests/connect/connect_inject_test.go
  acceptance/tests/fixtures/bases/resolver-redirect/intention.yaml
  acceptance/tests/fixtures/bases/resolver-redirect/kustomization.yaml
  acceptance/tests/fixtures/bases/resolver-redirect/resolver.yaml
  acceptance/tests/fixtures/bases/resolver-redirect/service.yaml
  acceptance/tests/fixtures/bases/resolver-redirect/serviceaccount.yaml
  acceptance/tests/fixtures/cases/resolver-redirect-virtualip/kustomization.yaml
  control-plane/subcommand/server-acl-init/rules.go
  control-plane/subcommand/server-acl-init/rules_test.go
Labels: backport/1.2.x

#2532 reactivate proxy-lifecycle tests
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2483 Derekm/fix test flakes
  acceptance/framework/connhelper/connect_helper.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2544 Backport/derekm/fix test flakes/tightly leading coral
  acceptance/framework/connhelper/connect_helper.go
Labels: pr/no-changelog, pr/no-backport

#2543 Backport/derekm/fix test flakes/poorly powerful katydid
  acceptance/framework/connhelper/connect_helper.go
Labels: pr/no-changelog, pr/no-backport

#2539 reactivate proxy-lifecycle tests
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2528 chore: Update chart to use OSS image
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2548 chore: Remove todo.txt
  charts/consul/todo.txt
Labels: pr/no-changelog, pr/no-backport

#2524 first pass making gateway controllers less chatty
  .changelog/2524.txt
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gatewayclass_controller.go
  control-plane/api-gateway/controllers/gatewayclassconfig_controller.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/service.go
Labels: backport/1.2.x

#2254 HCP Observability acceptance test
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/remote_dev_test.go
  acceptance/tests/fixtures/bases/cloud/service-intentions/acl.yaml
  acceptance/tests/fixtures/bases/cloud/service-intentions/kustomization.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
Labels: pr/no-changelog, pr/no-backport

#2551 HCP bootstrap preset to always downcase datacenter
  cli/preset/cloud_preset.go
  cli/preset/cloud_preset_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x

#2413 NET-4638: when multiple listeners have the same port, only add to K8s Service once
  .changelog/2413.txt
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/service.go
Labels: theme/api-gateway, backport/1.2.x

#2420 NET-4482: set route condition appropriately when parent ref includes non-existent section
  .changelog/2420.txt
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/binding/route_binding.go
Labels: theme/api-gateway, backport/1.2.x

#2556 test: update nightly tests to consul 1.17-dev
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-api-gateway-conformance.yml
Labels: pr/no-changelog, pr/no-backport

#2559 Set redhat project to non-fips project
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2558 Update Release Scripts
  Makefile
  charts/consul/values.yaml
  control-plane/build-support/functions/10-util.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2565 added missing changelogs
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2567 Prepare 1.1.x for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2566 Prepare 1.0.x for Dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2568 Set release/0.49.x to dev mode for 0.49.9
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2534 Refactor test framework to allow for more than two kube contexts
  CONTRIBUTING.md
  Makefile
  acceptance/framework/config/config.go
  acceptance/framework/config/config_test.go
  acceptance/framework/consul/cli_cluster.go
  acceptance/framework/environment/environment.go
  acceptance/framework/flags/flags.go
  acceptance/framework/flags/flags_test.go
  acceptance/tests/partitions/main_test.go
  acceptance/tests/partitions/partitions_connect_test.go
  acceptance/tests/partitions/partitions_gateway_test.go
  acceptance/tests/partitions/partitions_sync_test.go
  acceptance/tests/peering/main_test.go
  acceptance/tests/peering/peering_connect_namespaces_test.go
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/peering/peering_gateway_test.go
  acceptance/tests/vault/main_test.go
  acceptance/tests/vault/vault_partitions_test.go
  acceptance/tests/vault/vault_wan_fed_test.go
  acceptance/tests/wan-federation/main_test.go
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  acceptance/tests/wan-federation/wan_federation_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2584 test(eks): fix deprecated CSI driver terraform
  charts/consul/test/terraform/eks/main.tf
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2592 Add a check to prevent a nil-pointer dereference on Ingress LB
  control-plane/catalog/to-consul/resource.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2589 test: remove unused workflow inputs
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-api-gateway-conformance.yml
  .github/workflows/nightly-cleanup.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2583 [NET-4122] Doc guidance for federation with externalServers
  charts/consul/values.yaml
Labels: documentation, type/docs, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2609 Manual backport of test: remove unused workflow inputs (#2589) into release/0.49.x
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2610 Manual backport of test: remove unused workflow inputs (#2589) into release/1.0.x
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2607 Manual backport of test: remove unused workflow inputs (#2589) into release/1.2.x
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-cleanup.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#2571 Handle errors properly when services are de-registered from the catalog
  .changelog/2571.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2481 Adding support for Enterprise and other improvement on the Customizing Vault Version for WanFed Test
  acceptance/framework/config/config.go
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/consul/cli_cluster.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/flags/flags.go
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/deploy.go
  acceptance/framework/vault/vault_cluster.go
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/remote_dev_test.go
  acceptance/tests/config-entries/config_entries_namespaces_test.go
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/connect/connect_external_servers_test.go
  acceptance/tests/connect/connect_inject_namespaces_test.go
  acceptance/tests/connect/connect_inject_test.go
  acceptance/tests/connect/permissive_mtls_test.go
  acceptance/tests/consul-dns/consul_dns_test.go
  acceptance/tests/example/example_test.go
  acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
  acceptance/tests/ingress-gateway/ingress_gateway_test.go
  acceptance/tests/metrics/metrics_test.go
  acceptance/tests/partitions/partitions_connect_test.go
  acceptance/tests/partitions/partitions_gateway_test.go
  acceptance/tests/partitions/partitions_sync_test.go
  acceptance/tests/peering/peering_connect_namespaces_test.go
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/peering/peering_gateway_test.go
  acceptance/tests/sync/sync_catalog_namespaces_test.go
  acceptance/tests/sync/sync_catalog_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_destinations_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_test.go
  acceptance/tests/vault/vault_namespaces_test.go
  acceptance/tests/vault/vault_test.go
  acceptance/tests/vault/vault_tls_auto_reload_test.go
  acceptance/tests/vault/vault_wan_fed_test.go
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  acceptance/tests/wan-federation/wan_federation_test.go
  go.work
  go.work.sum
Labels: pr/no-changelog, pr/no-backport

#2599 Differentiate FIPS linux package names
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2.x

#2603 added make target for checking for hashicorppreview
  Makefile
  control-plane/build-support/scripts/check-hashicorppreview.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2621 Increase golangci-lint timeout to 10m
  .golangci.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2608 Manual backport of test: remove unused workflow inputs (#2589) into release/1.1.x
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
  .golangci.yml
Labels: pr/no-changelog, pr/no-backport

#2631 Fix TestAPIGateway_GatewayClassConfig
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  go.work
  go.work.sum
Labels: pr/no-changelog, pr/no-backport

#2572 Support running with restricted PSA enforcement enabled (part 1)
  .changelog/2572.txt
  acceptance/framework/config/config.go
  acceptance/framework/config/config_test.go
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/consul/helm_cluster_test.go
  acceptance/framework/environment/environment.go
  acceptance/framework/flags/flags.go
  acceptance/tests/connect/connect_external_servers_test.go
  acceptance/tests/connect/connect_inject_namespaces_test.go
  acceptance/tests/connect/connect_inject_test.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/connect/permissive_mtls_test.go
  acceptance/tests/fixtures/bases/openshift/network-attachment.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-inject/patch.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-tproxy/patch.yaml
  acceptance/tests/fixtures/cases/static-server-openshift/kustomization.yaml
  acceptance/tests/fixtures/cases/static-server-openshift/patch.yaml
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/tls-init-cleanup-job.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2591 change fips delimiter to + (#2480)
  .github/workflows/build.yml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, backport/1.2.x

#2642 [NET-4865] security: Upgrade Go and net/http CVE-2023-29406
  .changelog/2642.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2652 Consul client always logs into the local datacenter
  .changelog/2652.txt
  charts/consul/templates/client-daemonset.yaml
  charts/consul/test/unit/client-daemonset.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2641 Add support for requestTimeout in Service Resolver spec
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-gatewayclasses.yaml
  charts/consul/templates/crd-gateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-referencegrants.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  charts/consul/templates/crd-tlsroutes.yaml
  charts/consul/templates/crd-udproutes.yaml
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_controlplanerequestlimits.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_samenessgroups.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2660 Add support for requestTimeout in Service Resolver spec (#2641)
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-gatewayclasses.yaml
  charts/consul/templates/crd-gateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-referencegrants.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  charts/consul/templates/crd-tlsroutes.yaml
  charts/consul/templates/crd-udproutes.yaml
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_controlplanerequestlimits.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_samenessgroups.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
Labels: pr/no-changelog, pr/no-backport

#2661 Add support for requestTimeout in Service Resolver spec
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
Labels: pr/no-changelog, pr/no-backport

#2667 Update changelog to address cloud auto-join change in 1.0.0
  CHANGELOG.md
Labels: documentation, type/docs, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2675 Fix ordering of licence in templates
  charts/consul/templates/crd-gatewayclasses.yaml
  charts/consul/templates/crd-gateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
Labels: pr/no-changelog, backport/1.2.x

#2676 Use 0.8.0 to generate templates
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
Labels: pr/no-changelog, pr/no-backport

#2579 Mw/net 4260 phase 2 automate the k8s sameness tests
  Makefile
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  acceptance/framework/k8s/kubectl.go
  acceptance/tests/fixtures/bases/sameness/default-ns/kustomization.yaml
  acceptance/tests/fixtures/bases/sameness/default-ns/sameness.yaml
  acceptance/tests/fixtures/bases/sameness/exportedservices-ap1/exportedservices-ap1.yaml
  acceptance/tests/fixtures/bases/sameness/exportedservices-ap1/kustomization.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/intentions.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/kustomization.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/payment-service-resolver.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/service-defaults.yaml
  acceptance/tests/fixtures/bases/sameness/peering/kustomization.yaml
  acceptance/tests/fixtures/bases/sameness/peering/mesh.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/ap1-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/ap1-partition/patch.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/default-partition/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/partition/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/default/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/default/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/partition/patch.yaml
  acceptance/tests/partitions/partitions_connect_test.go
  acceptance/tests/sameness/main_test.go
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, backport/1.2.x

#2302 Added logLevel field for components
  .changelog/2302.txt
  charts/consul/templates/client-config-configmap.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/test/unit/client-config-configmap.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/create-federation-secret-job.bats
  charts/consul/test/unit/gossip-encryption-autogenerate-job.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/test/unit/tls-init-job.bats
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2682 Add missing tsccr entries
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2684 Use controller-gen 0.8.0 for CRDs
  Makefile
  acceptance/tests/fixtures/bases/openshift/network-attachment.yaml
  acceptance/tests/fixtures/bases/sameness/default-ns/sameness.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/intentions.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/payment-service-resolver.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/service-defaults.yaml
  acceptance/tests/fixtures/bases/sameness/peering/mesh.yaml
  acceptance/tests/sameness/sameness_test.go
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-referencegrants.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_controlplanerequestlimits.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_samenessgroups.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
Labels: pr/no-changelog, backport/1.2.x

#2686 Use controller-gen 0.8.0 for CRDs
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind-inputs.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  acceptance/tests/connect/permissive_mtls_test.go
  acceptance/tests/fixtures/bases/openshift/network-attachment.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/servicedefaults.yaml
  acceptance/tests/fixtures/cases/permissive-mtls/mesh-config-permissive-allowed.yaml
  acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-permissive.yaml
  acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-strict.yaml
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  cli/version/fips_build.go
  cli/version/non_fips_build.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/common/secrets_test.go
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_controlplanerequestlimits.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_samenessgroups.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
Labels: pr/no-changelog, pr/no-backport

#2687 Fix ingress
  .changelog/2687.txt
  charts/consul/templates/ui-ingress.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2668 [NET-4865] Bump golang.org/x/net to 0.12.0 in cni
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2683 Fix default Ent image tag in acceptance tests
  Makefile
  acceptance/framework/config/config.go
  acceptance/framework/config/config_test.go
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2678 Do not set securityContext on Openshift < 4.11
  .changelog/2678.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.0.x

#2701 Backport of Fix default Ent image tag in acceptance tests into release/1.2.x
  Makefile
  acceptance/framework/config/config.go
  acceptance/framework/config/config_test.go
Labels: pr/no-changelog, pr/no-backport
