Repository hashicorp/consul-k8s, pull requests merged in 2023-06, with the labels that each got.

#2225 Fix NET-704 CVEs (backport to 1.0.x)
  .changelog/2225.txt
  control-plane/api/common/configentry_webhook_test.go
  control-plane/api/v1alpha1/exportedservices_webhook_test.go
  control-plane/api/v1alpha1/mesh_webhook_test.go
  control-plane/api/v1alpha1/peeringacceptor_webhook_test.go
  control-plane/api/v1alpha1/peeringdialer_webhook_test.go
  control-plane/api/v1alpha1/proxydefaults_webhook_test.go
  control-plane/api/v1alpha1/serviceintentions_webhook_test.go
  control-plane/catalog/to-consul/resource_test.go
  control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/mesh_webhook_ent_test.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhook/redirect_traffic_test.go
  control-plane/controller/configentry_controller.go
  control-plane/controller/configentry_controller_ent_test.go
  control-plane/controller/configentry_controller_test.go
  control-plane/controller/exportedservices_controller.go
  control-plane/controller/exportedservices_controller_ent_test.go
  control-plane/controller/ingressgateway_controller.go
  control-plane/controller/mesh_controller.go
  control-plane/controller/proxydefaults_controller.go
  control-plane/controller/servicedefaults_controller.go
  control-plane/controller/serviceintentions_controller.go
  control-plane/controller/serviceresolver_controller.go
  control-plane/controller/servicerouter_controller.go
  control-plane/controller/servicesplitter_controller.go
  control-plane/controller/terminatinggateway_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/controller/controller.go
  control-plane/subcommand/common/common.go
Labels: pr/no-backport

#2237 Add acceptance test cleanup for API Gateway resources
  acceptance/framework/consul/helm_cluster.go
  acceptance/go.mod
  acceptance/go.sum
Labels: pr/no-changelog, pr/no-backport

#2210 improve code readability and fix flaky tests re acl token generation
  control-plane/subcommand/create-federation-secret/command_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2242 Increase timeout and backoff for retry on flaky test
  control-plane/subcommand/get-consul-client-ca/command_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2245 Add fake demo/crds to get around that expectation in chart install
  charts/demo/crds/blank
  charts/demo/templates/intentions.yaml
  charts/embed_chart.go
Labels: backport/1.1.x, pr/no-changelog

#2246 NET-4285 add check for pointer
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog

#2222 Persist virtual-ips for intentions / service-defaults.
  control-plane/controllers/configentry_controller.go
Labels: pr/no-changelog, pr/no-backport

#2253 Allow API Gateways to bind to privileged ports
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/api-gateway/apigateway.yaml
  control-plane/api-gateway/gatekeeper/dataplane.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2256 acceptance: extend api gateway lifecycle test retryCheck timeouts
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
Labels: pr/no-changelog, pr/no-backport

#2252 api-gateway: create RoleBinding attaching Role to ServiceAccount
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/role.go
  control-plane/api-gateway/gatekeeper/rolebinding.go
  control-plane/api-gateway/gatekeeper/service.go
  control-plane/api-gateway/gatekeeper/serviceaccount.go
Labels: pr/no-changelog, pr/no-backport

#2262 Add allow all intention for consul-telemetry-collector for -demo
  .changelog/2262.txt
  charts/demo/templates/intentions.yaml
Labels: backport/1.1.x

#2255 Add missing resources to kustomization.yaml
  acceptance/tests/config-entries/config_entries_namespaces_test.go
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/fixtures/bases/crds-oss/exportedservices.yaml
  acceptance/tests/fixtures/bases/crds-oss/jwtprovider.yaml
  acceptance/tests/fixtures/bases/crds-oss/kustomization.yaml
  acceptance/tests/fixtures/cases/crds-ent/exportedservices.yaml
  acceptance/tests/fixtures/cases/crds-ent/kustomization.yaml
Labels: pr/no-changelog, pr/no-backport

#2261 Fix Gateway trigger for when secret is modified
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_test.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2264 Prerelease 1.1.2
  CHANGELOG.md
  acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2266 Update casing of json tag for ServiceDefault field
  .changelog/2266.txt
  acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
Labels: backport/1.0.x, backport/1.1.x

#2273 Set release 1.1.x to dev mode for 1.1.3
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2275 Add missing entries to main CHANGELOG
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2277 Fixing changelog for 2195
  .changelog/2195.txt
Labels: backport/1.1.x, pr/no-changelog

#2284 Update alpine to 3.18 to fix CVE-2023-2650
  .changelog/2284.txt
  control-plane/Dockerfile
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#2283 Remove check for reference grant for route to gateway
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/reference_grant.go
  control-plane/api-gateway/binding/reference_grant_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/translation_test.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2278 [API Gateway] Add partition test
  acceptance/tests/fixtures/bases/api-gateway/kustomization.yaml
  acceptance/tests/fixtures/bases/api-gateway/meshservice.yaml
  acceptance/tests/fixtures/cases/api-gateways/mesh/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/mesh/proxydefaults.yaml
  acceptance/tests/fixtures/cases/api-gateways/resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/resolver/serviceresolver.yaml
  acceptance/tests/partitions/partitions_gateway_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/common/labels.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2249 Update memory defaults for connect inject controller
  .changelog/2249.txt
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: area/chart-only, backport/1.1.x

#2282 Mw/fix pipeline 1 1 6
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/eks/main.tf
  charts/consul/test/terraform/gke/main.tf
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2276 Fix changelog for 2194
  .changelog/2194.txt
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2311 Fix retry loops that use `t`
  acceptance/tests/cli/cli_install_test.go
  acceptance/tests/config-entries/config_entries_namespaces_test.go
  acceptance/tests/config-entries/config_entries_test.go
  control-plane/subcommand/create-federation-secret/command_test.go
Labels: pr/no-changelog, backport/1.2.x

#2165 Add FIPS builds
  .github/workflows/build.yml
  Makefile
  cli/version/fips_build.go
  cli/version/non_fips_build.go
  cli/version/version.go
  control-plane/Dockerfile
  control-plane/build-support/functions/20-build.sh
  control-plane/build-support/scripts/build-local.sh
  control-plane/subcommand/connect-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
Labels: pr/no-changelog, backport/1.2.x

#2297 Net 4230/add tcp to basic acceptance test
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/deployment.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/privileged-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/psp-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/service.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/serviceaccount.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/servicedefaults.yaml
  acceptance/tests/fixtures/cases/api-gateways/tcproute/route.yaml
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2306 [API Gateway] Add acceptance test for cluster peering
  acceptance/tests/fixtures/cases/api-gateways/peer-resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/peer-resolver/serviceresolver.yaml
  acceptance/tests/peering/peering_gateway_test.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2304 Mw/net 3598 update kind for consul k8s acceptance tests with latest version of kind and k8s 1.27
  .changelog/2304.txt
  README.md
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/gke/main.tf
Labels: backport/1.2.x

#2295 [API Gateway] WAN Federation test and fixes
  acceptance/tests/fixtures/cases/api-gateways/dc1-to-dc2-resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/dc1-to-dc2-resolver/serviceresolver.yaml
  acceptance/tests/fixtures/cases/api-gateways/dc2-to-dc1-resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/dc2-to-dc1-resolver/serviceresolver.yaml
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/connect-inject/constants/constants.go
  control-plane/subcommand/inject-connect/command.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2321 [API Gateway] fix dangling service registrations
  control-plane/api-gateway/cache/gateway.go
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2272 api-gateway: add unit tests verifying scaling parameters on GatewayClassConfig are obeyed
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2317 Rename GatewayClassController to prevent name collision
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/api-gateway/gatewayclass.yaml
  acceptance/tests/fixtures/cases/api-gateways/gateway/gateway.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  control-plane/api-gateway/common/constants.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gatewayclass_controller.go
  control-plane/api-gateway/controllers/gatewayclass_controller_test.go
  control-plane/api-gateway/controllers/gatewayclassconfig_controller.go
  control-plane/api-gateway/controllers/gatewayclassconfig_controller_test.go
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-changelog, backport/1.2.x

#2326 [API Gateway] Conformance Test Fixes
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/validation.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2327 pin for 1.2.x-rc latest Consul submodules
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport, backport/1.2.x

#2305 Ensure Reconciliation Stops
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2333 Add CRT docker changes for release workflow
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, backport/1.2.x

#2330 Update var check with appropriate quotes
  control-plane/build-support/functions/20-build.sh
Labels: pr/no-changelog, pr/no-backport

#2338 update redhat registry id (1.2.x)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2341 Revert "Ensure Reconciliation Stops"
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2339 Mw/ready for release 1 2 0 rc1
  .changelog/1975.txt
  .changelog/1976.txt
  .changelog/2048.txt
  .changelog/2075.txt
  .changelog/2086.txt
  .changelog/2097.txt
  .changelog/2102.txt
  .changelog/2165.txt
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/controllers/configentry_controller_ent_test.go
  control-plane/controllers/configentry_controller_test.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2265 Improvement- [NET-189] Added helm inputs for managing audit logs
  .changelog/2265.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, backport/1.2.x

#2347 Put branch back in dev mode 1.2.x
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2346 Set Consul Service Instance Localities from K8s Node Labels
  .changelog/2346.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#2353 fix: use correct flag when translating namespaces
  control-plane/api-gateway/cache/gateway.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2310 added imagePullPolicy for images in values.yaml
  .changelog/2310.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2356 [chore]: Pin github action workflows
  .github/workflows/build.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog, pr/no-backport

#2365 ci: update backport assistant to 0.3.4
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#2358 Fix retry loops that use `t`
  acceptance/tests/connect/connect_inject_test.go
Labels: pr/no-changelog, pr/no-backport

#2360 Fix retry loops that use `t` (release/1.1.x)
  acceptance/tests/cli/cli_install_test.go
  control-plane/subcommand/create-federation-secret/command_test.go
Labels: pr/no-changelog, pr/no-backport

#2257 api-gateway: nightly conformance test action
  .github/workflows/nightly-api-gateway-conformance.yml
Labels: pr/no-changelog, pr/no-backport

#2376 added imagePullPolicy for images in values.yaml (#2310)
  .changelog/2310.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#2357 Add CRDs for `ProritizeByLocality` Routing
  .changelog/2357.txt
  charts/consul/templates/crd-serviceresolvers.yaml
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
Labels: pr/no-backport

#2374 added imagePullPolicy for images in values.yaml (#2310)
  .changelog/2310.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#2377 api-gateway: fix cache and service deletion issue
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/cache/gateway.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2388 Fix Gateway Service Deregistration
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/cache/gateway.go
Labels: pr/no-changelog, pr/no-backport

#2370 Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.2.x
  .changelog/2370.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2391 Update go-discover
  .changelog/2390.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#2293 Adding support for weighted k8s service
  .changelog/2293.txt
  control-plane/catalog/to-consul/annotation.go
  control-plane/catalog/to-consul/resource.go
  control-plane/catalog/to-consul/resource_test.go
Labels: pr/no-backport

#2369 Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.1.x
  .changelog/2369.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2390 Bumping go-discover to the lastest version
  .changelog/2390.txt
  control-plane/Dockerfile
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2384 Pin Kind versions on release branches
  Makefile
  acceptance/ci-inputs/kind-inputs.yaml
  control-plane/build-support/scripts/read-yaml-config.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2404 Backport Bumping go-discover to the latest version
  .changelog/2390.txt
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#2325 update consul-dataplane on main to use 1.2-dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2378 Acceptance test for permissive mTLS
  acceptance/tests/connect/permissive_mtls_test.go
  acceptance/tests/fixtures/cases/permissive-mtls/mesh-config-permissive-allowed.yaml
  acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-permissive.yaml
  acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-strict.yaml
Labels: pr/no-changelog, backport/1.2.x

#2406 Update Alpine to 3.18 for CVE-2023-2650
  .changelog/2284.txt
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#2408 Mw/release 1 2 0 pin kind
  Makefile
  acceptance/ci-inputs/kind-inputs.yaml
  control-plane/build-support/scripts/read-yaml-config.sh
Labels: pr/no-changelog, pr/no-backport

#2415 Revert "added imagePullPolicy for images in values.yaml (#2310)"
  .changelog/2310.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x

#2419 backport of commit 0ab63e0d18ea2ce3b9f8f10b7f262b27f99246bb (#2418)
  .changelog/2310.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2411 Mw/net 4622 release 0.49.x acceptance tests broken missing packages
  Makefile
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  control-plane/build-support/scripts/set_test_package_matrix.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2428 point at main workflow
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#2426 Mw/net 4622 1 2 0 cp release 0.49.x acceptance tests broken missing packages
  Makefile
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  control-plane/build-support/scripts/set_test_package_matrix.sh
Labels: pr/no-changelog, pr/no-backport

#2432 removed cli test package
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: pr/no-changelog, pr/no-backport

#2416 feat(helm): add configurable server-acl-init and cleanup resource limits
  .changelog/2416.txt
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, backport/1.2.x

#2368 Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.0.x
  .changelog/2265.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2441 update redhat registry id
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2337 update redhat registry id
  .github/workflows/build.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2434 Fix Audit Log Config for Consul Enterprise
  charts/consul/templates/server-config-configmap.yaml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x

#2421 Add acceptance test to test sync + ingress
  acceptance/framework/config/config.go
  acceptance/framework/flags/flags.go
  acceptance/tests/fixtures/bases/ingress/ingress.yaml
  acceptance/tests/fixtures/bases/ingress/kustomization.yaml
  acceptance/tests/sync/sync_catalog_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2451 use latest 1.2 dataplane
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2455 Manual backport of 2337 into release/1.1.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2454 Manual backport of 2337 into release/1.0.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2453 Manual backport of 2337 into release/0.49.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#2452 use latest 1.2 dataplane (#2451)
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2436 Fix failing ingress-gateway tests
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2409 Fix GatewayClassConfig Test Timing Issue
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
Labels: pr/no-changelog, backport/1.2.x

#2392 always update acl policy if it exists
  .changelog/2392.txt
  control-plane/subcommand/server-acl-init/create_or_update.go
  control-plane/subcommand/server-acl-init/create_or_update_test.go
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, backport/1.2.x

#2233 helm: add configuration for proxy lifecycle management
  .changelog/2233.txt
  acceptance/framework/config/config.go
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/flags/flags.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration_test.go
  control-plane/connect-inject/metrics/metrics_configuration.go
  control-plane/connect-inject/metrics/metrics_configuration_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/subcommand/inject-connect/command.go
Labels: backport/1.0.x, backport/1.1.x

#2389 Backport of #2377
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/cache/gateway.go
Labels: pr/no-changelog, pr/no-backport

#2459 Manual backport gatewayclassconfigtest fix
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
Labels: pr/no-changelog, pr/no-backport

#2469 PR breaking change release note change
  .changelog/2392.txt
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2476 Prepare Release 1.2.0
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/scripts/consul-enterprise-version.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2468 Backport of Proxy Lifecycle helm, connect-inject and acceptance tests into release/1.1.x (#2233)
  .changelog/2233.txt
  acceptance/framework/config/config.go
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/flags/flags.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration_test.go
  control-plane/connect-inject/metrics/metrics_configuration.go
  control-plane/connect-inject/metrics/metrics_configuration_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-backport

#2412 Adds back gateway controller integration test
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
Labels: theme/api-gateway, pr/no-changelog, backport/1.2.x

#2467 Backport of Proxy Lifecycle helm, connect-inject and acceptance tests into release/1.0.x (#2233)
  .changelog/2233.txt
  acceptance/framework/config/config.go
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/flags/flags.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration_test.go
  control-plane/connect-inject/metrics/metrics_configuration.go
  control-plane/connect-inject/metrics/metrics_configuration_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-backport

#2464 Mw/net 4605 consul k8s pin cloud tests to latest supported kubernetes version for that release 1 0
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/outputs.tf
  charts/consul/test/terraform/aks/variables.tf
  charts/consul/test/terraform/eks/main.tf
  charts/consul/test/terraform/eks/outputs.tf
  charts/consul/test/terraform/eks/variables.tf
  charts/consul/test/terraform/gke/main.tf
  charts/consul/test/terraform/gke/outputs.tf
  charts/consul/test/terraform/gke/variables.tf
Labels: pr/no-changelog, pr/no-backport

#2485 Prepare release 0.49.7
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/scripts/consul-enterprise-version.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2489 [release/1.2.0] Backport api-gateway: Fix nil pointer exception panic
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
Labels: pr/no-changelog, pr/no-backport

#2484 Setup 1.0.8 for release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/scripts/consul-enterprise-version.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2487 api-gateway: Fix nil pointer exception panic
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
Labels: pr/no-changelog, backport/1.2.x

#2486 Set up 1.1.3 for release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/scripts/consul-enterprise-version.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2478 APIGW: Validate length of RSA Keys
  .changelog/2478.txt
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/api-gateway/common/secrets_test.go
  control-plane/api-gateway/common/translation.go
Labels: theme/api-gateway, backport/1.2.x

#2495 Mw/add changelog 1 2 0 dataplane support
  .changelog/2476.txt
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2496 add changelog for 1.2.0 dataplane and consul 1.16.0
  .changelog/2476.txt
Labels: pr/no-changelog, backport/1.2.x

#2498 Mw/update changelog
  .changelog/2476.txt
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2499 ready for 0.49.8 dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2504 Fix RedHat Tag
  .github/workflows/build.yml
Labels: backport/0.49.x, backport/1.1.x, pr/no-changelog

#2503 Set imageConsul to non-ent image
  charts/consul/values.yaml
Labels: pr/no-backport

#2501 Adds changelog values for 0.49.7
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport
