Repository hashicorp/consul-k8s, pull requests merged in 2023-12, with the labels that each got.

#3284 Update MatchesConsul to normalize partitions during comparison.
  .changelog/3284.txt
  control-plane/api/v1alpha1/exportedservices_types.go
  control-plane/api/v1alpha1/exportedservices_types_test.go
  control-plane/api/v1alpha1/ingressgateway_types.go
  control-plane/api/v1alpha1/ingressgateway_types_test.go
  control-plane/api/v1alpha1/samenessgroup_types.go
  control-plane/api/v1alpha1/samenessgroup_types_test.go
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/servicerouter_types.go
  control-plane/api/v1alpha1/servicerouter_types_test.go
  control-plane/api/v1alpha1/servicesplitter_types.go
  control-plane/api/v1alpha1/servicesplitter_types_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3286 Stop syncing GatewayClass + GatewayClassConfig into Consul
  control-plane/config-entries/controllersv2/gateway_class_config_controller.go
  control-plane/config-entries/controllersv2/gateway_class_controller.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3297 NET-6758 Use kubebuilder for v2 GatewayClassConfig CRD
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3273 [NET-6462] Update gateway resources job for mesh gw v2
  charts/consul/templates/gateway-resources-clusterrole.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, theme/api-gateway, pr/no-changelog, pr/no-backport

#3290 Net 6392- Create MeshGateway Deployment
  control-plane/api/common/common.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/connect-inject/constants/constants.go
  control-plane/gateways/builder.go
  control-plane/gateways/config.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_init_container.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/serviceaccount.go
  control-plane/gateways/serviceaccount_test.go
  control-plane/go.mod
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport, do-not-merge

#3299 Update generated files and manifests
  charts/consul/templates/crd-gatewayclasses-external.yaml
  charts/consul/templates/crd-gateways-external.yaml
  charts/consul/templates/crd-grpcroutes-external.yaml
  charts/consul/templates/crd-httproutes-external.yaml
  charts/consul/templates/crd-proxyconfigurations.yaml
  charts/consul/templates/crd-referencegrants-external.yaml
  charts/consul/templates/crd-routetimeoutfilters.yaml
  charts/consul/templates/crd-tcproutes-external.yaml
  charts/consul/templates/crd-tlsroutes-external.yaml
  charts/consul/templates/crd-udproutes-external.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_proxyconfigurations.yaml
  control-plane/config/rbac/role.yaml
Labels: pr/no-changelog, pr/no-backport

#3303 Create role and role binding for mesh gateways
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/gateways/role.go
Labels: pr/no-changelog, pr/no-backport

#3301 NET-6575- Add ConfigMap volume mount to gateway cleanup job
  charts/consul/templates/gateway-cleanup-job.yaml
Labels: pr/no-changelog, pr/no-backport

#3298 NET-6759 Restructure v2 GatewayClassConfig CRD
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3218 Add validation that externalServers.hosts is not set to HCP-managed cluster's addresses when global.cloud.enabled
  .changelog/3218.txt
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3306 [NET-6404] Create Mesh Gateway Resource from Gateway Resources Job
  charts/consul/templates/gateway-resources-clusterrole.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3302 Stub mesh configuration resource controller
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api/common/common.go
  control-plane/api/mesh/v2beta1/mesh_configuration_types.go
  control-plane/config-entries/controllersv2/mesh_configuration_controller.go
  control-plane/config/rbac/role.yaml
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#3230 Reduce permissions of API gateway policy
  control-plane/api-gateway/cache/consul.go
Labels: pr/no-changelog, pr/no-backport

#3338 test concurrency
  .github/workflows/merge.yml
Labels: pr/no-changelog, pr/no-backport

#3340 add github actor to be used in workflows
  .github/workflows/merge.yml
  .github/workflows/pr.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3317 Net 6575- Modify Gateways Cleanup Job to cleanup v2 resources
  charts/consul/templates/gateway-cleanup-clusterrole.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  control-plane/subcommand/gateway-cleanup/command.go
  control-plane/subcommand/gateway-cleanup/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3330 fixed incorrect test validation with peering test
  acceptance/tests/peering/peering_connect_namespaces_test.go
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/peering/peering_gateway_test.go
Labels: pr/no-changelog, backport/1.3.x

#3347 Add `consul.hashicorp.com/proxy-config-map` annotation.
  .changelog/3347.txt
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3307 [NET-6588] Remove abandoned virtual nodes from Consul Catalog
  .changelog/3307.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3315 Add validation that externalServers.hosts is not set to HCP-managed cluster's addresses when global.cloud.enabled
  .changelog/3315.txt
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3329 [NET-6723] Node Selector Support for Mesh GW
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/common/common.go
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3364 Declare ownership of Deployment, Role and RoleBinding on MeshGateway controller
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3361 Net 6742 - consul k8s mgw deployment priority class name support
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3337 Prevent extra-config from being loaded twice (and erroring for segment config) on clients and servers
  .changelog/3337.txt
  acceptance/tests/segments/main_test.go
  acceptance/tests/segments/segments_test.go
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/client-config-configmap.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/client-tmp-extra-config-configmap.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/server-tmp-extra-config-configmap.yaml
  charts/consul/test/unit/client-config-configmap.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/client-tmp-extra-config-configmap.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/server-tmp-extra-config-configmap.bats
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3363 [NET-6756] Tolerations for MeshGW
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/gateways/deployment.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3366 Mw/net 6911 parallel cluster creation in acceptance test causes tests to hang on failure
  Makefile
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/partitions/partitions_connect_test.go
  acceptance/tests/peering/peering_connect_namespaces_test.go
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/peering/peering_gateway_test.go
  acceptance/tests/sameness/sameness_test.go
  control-plane/subcommand/get-consul-client-ca/command_test.go
Labels: pr/no-changelog, backport/1.3.x

#3371 [NET-6721] Replicas support for MeshGW v2 Deployments
  control-plane/gateways/deployment.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3365 NET-6663 Set gateway-kind in Workload metadata when it represents a xGateway Pod
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3379 [NET-6787] HostNetwork support for meshgw deployments
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3381 NET-6788 - Mesh Gateway Host Port Support
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3328 NET-6393: Create/update/delete Service on MeshGateway reconcile
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/gateways/annotations.go
  control-plane/gateways/service.go
  control-plane/gateways/service_test.go
  control-plane/subcommand/gateway-resources/command.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3386 fix build issues as a result of portModifier
  control-plane/gateways/service.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3376 Net 6779 - Mesh Gateway eployment topology spread constraints
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3390 Prepare 1.2.4 for release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3387 Update test to match PreparedQuery SamenessGroup bugfix.
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x

#3389 Prepare 1.1.8 for release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3394 Fix the Consul dependency version
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#3391 Prepare 1.3.1 for release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3382 [NET-6938] Create workloads in Consul for mesh gateway pods
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3380 [NET-6789] DNSPolicy support for meshgw v2 deployments
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/annotations.go
  control-plane/gateways/deployment.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3399 Add `prepare-release-dev` make command to `release/1.1.x`
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3400 Add `prepare-release-dev` make command to `release/1.2.x`
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3401 Reset 1.3.x for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3405 Reset 1.2.x for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3404 Reset 1.1.x for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3397 [NET-6766] Implement computing of annotations + labels for all created resources
  control-plane/gateways/annotations.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/labels.go
  control-plane/gateways/metadata.go
  control-plane/gateways/metadata_test.go
  control-plane/gateways/role.go
  control-plane/gateways/service.go
  control-plane/gateways/service_test.go
  control-plane/gateways/serviceaccount.go
  control-plane/gateways/serviceaccount_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3403 Release 1.2.x Sync up sameness acceptance tests with main
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, pr/no-backport

#3362 [Net-5510][Net-5455]: CRD controller should only patch the finalizer in the metadata of a CRD, rather than the whole object
  .changelog/3362.txt
  control-plane/config-entries/controllers/configentry_controller.go
  control-plane/config-entries/controllers/controlplanerequestlimit_controller.go
  control-plane/config-entries/controllers/exportedservices_controller.go
  control-plane/config-entries/controllers/finalizer_patch.go
  control-plane/config-entries/controllers/finalizer_patch_test.go
  control-plane/config-entries/controllers/ingressgateway_controller.go
  control-plane/config-entries/controllers/jwtprovider_controller.go
  control-plane/config-entries/controllers/mesh_controller.go
  control-plane/config-entries/controllers/proxydefaults_controller.go
  control-plane/config-entries/controllers/samenessgroups_controller.go
  control-plane/config-entries/controllers/servicedefaults_controller.go
  control-plane/config-entries/controllers/serviceintentions_controller.go
  control-plane/config-entries/controllers/serviceresolver_controller.go
  control-plane/config-entries/controllers/servicerouter_controller.go
  control-plane/config-entries/controllers/servicesplitter_controller.go
  control-plane/config-entries/controllers/terminatinggateway_controller.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3409 Add Changelog entries from patch releases
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#3396 [NET-6809] Add chart related labels for mesh gateway deployments
  control-plane/gateways/deployment_test.go
  control-plane/gateways/service_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3414 Manual Backport of [Net-5510][Net-5455]: CRD controller should only patch the finalizer in the metadata of a CRD, rather than the whole object into release/1.2.x
  .changelog/3362.txt
  control-plane/controllers/configentry_controller.go
  control-plane/controllers/controlplanerequestlimit_controller.go
  control-plane/controllers/exportedservices_controller.go
  control-plane/controllers/finalizer_patch.go
  control-plane/controllers/finalizer_patch_test.go
  control-plane/controllers/ingressgateway_controller.go
  control-plane/controllers/jwtprovider_controller.go
  control-plane/controllers/mesh_controller.go
  control-plane/controllers/proxydefaults_controller.go
  control-plane/controllers/samenessgroups_controller.go
  control-plane/controllers/servicedefaults_controller.go
  control-plane/controllers/serviceintentions_controller.go
  control-plane/controllers/serviceresolver_controller.go
  control-plane/controllers/servicerouter_controller.go
  control-plane/controllers/servicesplitter_controller.go
  control-plane/controllers/terminatinggateway_controller.go
Labels: pr/no-backport

#3415 Manual Backport of [Net-5510][Net-5455]: CRD controller should only patch the finalizer in the metadata of a CRD, rather than the whole object into release/1.1.x
  .changelog/3362.txt
  control-plane/controller/configentry_controller.go
  control-plane/controller/exportedservices_controller.go
  control-plane/controller/finalizer_patch.go
  control-plane/controller/finalizer_patch_test.go
  control-plane/controller/ingressgateway_controller.go
  control-plane/controller/mesh_controller.go
  control-plane/controller/proxydefaults_controller.go
  control-plane/controller/servicedefaults_controller.go
  control-plane/controller/serviceintentions_controller.go
  control-plane/controller/serviceresolver_controller.go
  control-plane/controller/servicerouter_controller.go
  control-plane/controller/servicesplitter_controller.go
  control-plane/controller/terminatinggateway_controller.go
  control-plane/go.mod
Labels: pr/no-backport

#3416 chore: add compatibility note to .0 changelogs
  control-plane/build-support/functions/10-util.sh
Labels: pr/no-changelog, pr/no-backport

#3408 [NET-6744] Fix mesh gw creation for v2
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/connect-inject/constants/constants.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_init_container.go
  control-plane/gateways/deployment_test.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/subcommand/mesh-init/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3419 [NET-6724] Add Affinity for Mesh GW Deployments
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/metadata.go
  control-plane/gateways/metadata_test.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3418 Dockerfile: update to ubi-minimal:9.3
  .changelog/3418.txt
  control-plane/Dockerfile
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3424 Dockerfile: backport #3418 to 1.1.x
  .changelog/3418.txt
  control-plane/Dockerfile
Labels: pr/no-backport
