Repository hashicorp/consul-k8s, pull requests merged in 2023-09, with the labels that each got.

#2869 NET-5389- Remove global.acls.nodeSelector and global.acls.annotations from Gateway Resources Jobs
  .changelog/2869.txt
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-cleanup-job.bats
  charts/consul/test/unit/gateway-resources-job.bats
Labels: backport/1.2.x

#2880 Filter api-gateway cache logging to reduce log output on server disconnect
  .changelog/2880.txt
  control-plane/api-gateway/cache/consul.go
Labels: theme/api-gateway, backport/1.2.x

#2894 removed deprecated `patchesStrategicMerge`
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-ns2-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc2-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/service-resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/static-client/kustomization.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2890 NET-5186 Add NET_BIND_SERVICE to built-in PSPs for consul-dataplane deployments
  charts/consul/templates/ingress-gateways-podsecuritypolicy.yaml
  charts/consul/templates/mesh-gateway-podsecuritypolicy.yaml
  charts/consul/templates/telemetry-collector-podsecuritypolicy.yaml
  charts/consul/templates/terminating-gateways-podsecuritypolicy.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2868 feat: add v2 pod controller w/ workload lifecycle
  control-plane/api-gateway/cache/consul_test.go
  control-plane/catalog/to-consul/syncer_test.go
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/consul_client_health_checks.go
  control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/consul/resource_client.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/test/test_util.go
  control-plane/subcommand/inject-connect/v2controllers.go
  control-plane/subcommand/server-acl-init/command_test.go
Labels: pr/no-changelog, pr/no-backport

#2844 Add RateLimit config to serviceDefaults
  .changelog/2844.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2907 1.1.5 Pre-release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2908 Prepare 1.1.x for next release cycle
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2903 Address issue #1285 via docs
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2905 Fix audit log parse error
  .changelog/2905.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2836 Translate HTTPAuthFilter onto HTTPRoute
  charts/consul/templates/crd-routeauthfilters.yaml
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api/v1alpha1/routeauthfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_routeauthfilters.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2902 Force a check on controller-gen version
  Makefile
Labels: pr/no-changelog, pr/no-backport

#2922 Backport of Configure Gateway Deployment Resources
  .changelog/2723.txt
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-gatewayclasses.yaml
  charts/consul/templates/crd-gateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  charts/consul/templates/crd-tlsroutes.yaml
  charts/consul/templates/crd-udproutes.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
  charts/consul/values.yaml
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api/v1alpha1/api_gateway_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/subcommand/gateway-resources/command.go
Labels: pr/no-changelog, pr/no-backport

#2835 Gateway policy translation NET 4980
  charts/consul/templates/crd-routeauthfilters.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api/v1alpha1/routeauthfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_routeauthfilters.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/api-gateway

#2912 Added validating webhook for gateway policy
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/connect-inject-validatingwebhookconfiguration.yaml
  charts/consul/templates/webhook-cert-manager-clusterrole.yaml
  control-plane/api/v1alpha1/gatewaypolicy_webhook.go
  control-plane/api/v1alpha1/gatewaypolicy_webhook_test.go
  control-plane/config/webhook/manifests.yaml
  control-plane/helper/mutating-webhook-configuration/mutating_webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration_test.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/webhook-cert-manager/command.go
Labels: pr/no-changelog, pr/no-backport

#2891 Backport net-5839 to 1.2.x
  .changelog/2869.txt
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-cleanup-job.bats
  charts/consul/test/unit/gateway-resources-job.bats
Labels: pr/no-backport

#2916 Backport of Fix audit log parse error into release/1.0.x
  .changelog/2905.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
Labels: pr/no-backport

#2841 NET-581 - Added vault namespace in helm
  .changelog/2841.txt
  acceptance/tests/vault/vault_namespaces_test.go
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, consul-india

#2924 Manual backport of #2905 into release/1.1.x
  .changelog/2905.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
Labels: pr/no-backport

#2928 Backport 1.1.x NET-581 - Added vault namespace in helm (#2841)
  .changelog/2841.txt
  acceptance/tests/vault/vault_namespaces_test.go
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2929 Backport NET-581 - Added vault namespace in helm (#2841)
  .changelog/2841.txt
  acceptance/tests/vault/vault_namespaces_test.go
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2910 [NET-5399] Improve token fetching performance for endpoints controller.
  .changelog/2910.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/connect/connect_inject_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2931 Update README.md - include Consul API Gateway as a use case
  README.md
Labels: pr/no-changelog, pr/no-backport

#2923 Manual backport of #2905 into release/1.2.x
  .changelog/2905.txt
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/test/unit/server-config-configmap.bats
Labels: pr/no-backport

#2883 feat: add v2 endpoints controller
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2780 Tests: Fix/improve tests with Restricted PSA enforcement
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/flags/flags.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2911 feat: add v2 pod controller healthstatus and proxyconfiguration
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/consul/resource_client_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2933 [NET-5399] Improve token fetching performance for endpoints controller.
  .changelog/2910.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/connect/connect_inject_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2937 Fix for acceptance tests
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2945 Backport 1.2.x Fix for acceptance tests (#2937)
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
Labels: pr/no-changelog, pr/no-backport

#2932 Add local rate limiting acceptance test
  acceptance/tests/connect/local_rate_limit_test.go
  acceptance/tests/fixtures/cases/local-rate-limiting/service-defaults-static-server.yaml
Labels: pr/no-changelog, pr/no-backport

#2940 [NET-5399] Improve token fetching performance for endpoints controller.
  .changelog/2910.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/connect/connect_inject_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2936 [NET-5574] Update Go version to 1.20.8
  .changelog/2936.txt
  .go-version
Labels: backport/1.1.x, backport/1.2.x

#2938 [NET-5574] Update Go version to 1.19.13 (1.0.x)
  .changelog/2938.txt
  .go-version
Labels: pr/no-backport

#2939 [APIGW] Add comparison of gateway policies to diffing logic
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/diff_test.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2904 NET-5531 Translate response header modifier(s) from HTTPRoute onto Consul config entry
  .changelog/2904.txt
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/api-gateway, backport/1.2.x

#2953 feat(helm): block v2 installs when admin partitions enabled
  charts/consul/templates/_helpers.tpl
  charts/consul/test/unit/helpers.bats
  charts/consul/test/unit/partition-init-job.bats
Labels: pr/no-changelog, pr/no-backport

#2950 [NET-5017] APIGW Status Conditions for Gateway for JWT/Reconcile on JWTProvider Changes
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/resources_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2881 [NET-5346] Expose JWKCluster fields in jwt-provider config entry
  .changelog/2881.txt
  charts/consul/templates/crd-jwtproviders.yaml
  control-plane/api/v1alpha1/jwtprovider_types.go
  control-plane/api/v1alpha1/jwtprovider_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/controllers/configentry_controller_test.go
Labels: backport/1.2.x

#2957 feat: add mesh-inject annotation to helm chart
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/prometheus.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-cleanup-job.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/gateway-cleanup-job.bats
  charts/consul/test/unit/gateway-resources-job.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/test/unit/tls-init-cleanup-job.bats
  charts/consul/test/unit/tls-init-job.bats
Labels: pr/no-changelog, pr/no-backport

#2956 feat: add namespace controller
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/namespace/namespace_controller.go
  control-plane/connect-inject/namespace/namespace_controller_ent_test.go
  control-plane/connect-inject/webhook_v2/mesh_webhook.go
  control-plane/connect-inject/webhook_v2/mesh_webhook_ent_test.go
  control-plane/namespaces/namespaces.go
  control-plane/namespaces/namespaces_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2961 [NET-5017] APIGW Status Conditions for RouteAuthFilter and Routes wrt JWT
  charts/consul/templates/crd-gatewaypolicies.yaml
  charts/consul/templates/crd-routeauthfilters.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/resources_test.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api/v1alpha1/gatewaypolicy_types.go
  control-plane/api/v1alpha1/routeauthfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routeauthfilters.yaml
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2952 GKE Autopilot support
  .changelog/2952.txt
  acceptance/framework/config/config.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/flags/flags.go
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/test/unit/crd-tcproutes.bats
  charts/consul/values.yaml
Labels: backport/1.2.x

#2964 Manual backport of GKE Autopilot support into release/1.2.x
  .changelog/2952.txt
  acceptance/framework/config/config.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/flags/flags.go
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/test/unit/crd-tcproutes.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2966 test(chart): fix telemetry V2 bats
  charts/consul/test/unit/telemetry-collector-v2-deployment.bats
Labels: pr/no-changelog, pr/no-backport

#2965 [NET-5314] Limit v2 Service port registration to L4 TCP ports
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2962 APIGW NS JWT Auth
  .changelog/2962.txt
  CONTRIBUTING.md
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/connect-inject-validatingwebhookconfiguration.yaml
  charts/consul/templates/crd-gatewaypolicies.yaml
  charts/consul/templates/crd-routeauthfilters.yaml
  charts/consul/templates/webhook-cert-manager-clusterrole.yaml
  charts/consul/test/unit/crd-gatewaypolicies.bats
  charts/consul/test/unit/crd-routeauthfilters.bats
  charts/consul/test/unit/telemetry-collector-v2-deployment.bats
  control-plane/PROJECT
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/diff_test.go
  control-plane/api-gateway/common/helpers.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/resources_test.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api/common/common.go
  control-plane/api/v1alpha1/gatewaypolicy_types.go
  control-plane/api/v1alpha1/gatewaypolicy_webhook.go
  control-plane/api/v1alpha1/gatewaypolicy_webhook_test.go
  control-plane/api/v1alpha1/routeauthfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routeauthfilters.yaml
  control-plane/config/webhook/manifests.yaml
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/mutating-webhook-configuration/mutating_webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration_test.go
  control-plane/subcommand/inject-connect/v1controllers.go
  control-plane/subcommand/webhook-cert-manager/command.go
  control-plane/subcommand/webhook-cert-manager/command_test.go
Labels: theme/api-gateway, pr/no-backport

#2947 [NET-5318] feat: add v2 service account controller
  control-plane/connect-inject/common/config.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_ent_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/test/test_util.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2968 Fix endpoints controller v2 tests
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2960 feat(control-plane): v2 backoff on missing namespace
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
Labels: pr/no-changelog, pr/no-backport

#2971 Revert temporary fixes to endpoints v2 tests
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2958 feat: Add HCP Observability ClientID and ClientSecret
  .changelog/2958.txt
  cli/go.mod
  cli/go.sum
  cli/preset/cloud_preset.go
  cli/preset/cloud_preset_test.go
Labels: backport/1.2.x

#2973 Backport/clly/observability credentials/manual
  .changelog/2958.txt
  cli/go.mod
  cli/go.sum
  cli/preset/cloud_preset.go
  cli/preset/cloud_preset_test.go
Labels: pr/no-backport

#2970 v2: multiport acceptance test in tproxy mode
  acceptance/tests-v2/mesh/main_test.go
  acceptance/tests-v2/mesh/mesh_inject_test.go
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/privileged-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/psp-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/secret.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/service.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/serviceaccount.yaml
  acceptance/tests/fixtures/cases/v2-static-client-inject-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/v2-static-client-inject-tproxy/patch.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/webhook_v2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook_v2/mesh_webhook_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2976 Prepare release v1.0.10
  .changelog/2796.txt
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/api/v1alpha1/ingressgateway_types.go
  control-plane/api/v1alpha1/ingressgateway_types_test.go
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2979 Prepare release v1.1.6
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2980 Prepare release v1.2.2
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2977 Mw/net 5340 add support for explicit upstreams
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2981 Bump default consul collector image
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2974 test(control-plane): add ENT tests for pod controller
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2978 [NET-5674] v2: Conditional target port when numeric in k8s
  acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/service.yaml
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2990 Update changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2987 [1.0.x] Post-release steps
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2994 add health status syncing check in acceptance test
  acceptance/tests-v2/mesh/mesh_inject_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
Labels: pr/no-changelog, pr/no-backport

#2988 [1.1.x] Post-release steps
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2989 [1.2.x] Post-release steps
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3004 traffic-permissions: fix unit tests to account for mutation hook
  control-plane/config-entries/controllersv2/meshconfig_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#2986 Add explicit upstreams to multiport acceptance test
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  acceptance/tests/fixtures/cases/v2-static-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/v2-static-client-inject/patch.yaml
  acceptance/tests/mesh_v2/main_test.go
  acceptance/tests/mesh_v2/mesh_inject_test.go
Labels: pr/no-changelog, pr/no-backport

#2996 refactored annotation processing
  control-plane/connect-inject/common/annotation_processor.go
  control-plane/connect-inject/common/annotation_processor_test.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/constants/constants_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2998 Add acceptance test for traffic permissions
  acceptance/tests/fixtures/bases/trafficpermissions/kustomization.yaml
  acceptance/tests/fixtures/bases/trafficpermissions/trafficpermissions.yaml
  acceptance/tests/fixtures/cases/trafficpermissions-deny/kustomization.yaml
  acceptance/tests/fixtures/cases/trafficpermissions-deny/patch.yaml
  acceptance/tests/mesh_v2/mesh_inject_test.go
Labels: pr/no-changelog, pr/no-backport

#2995 Mw/net 5679 explicit upstreams mesh webhook injects upstream env variable
  control-plane/connect-inject/common/annotation_processor.go
  control-plane/connect-inject/common/annotation_processor_test.go
  control-plane/connect-inject/webhookv2/container_env.go
  control-plane/connect-inject/webhookv2/container_env_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
Labels: pr/no-changelog, pr/no-backport

#3003 Use branch where acceptance tests run in parallel
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#3005 Rename pbmesh.Upstreams to pbmesh.Destinations
  acceptance/tests/fixtures/bases/trafficpermissions/trafficpermissions.yaml
  acceptance/tests/mesh_v2/mesh_inject_test.go
  control-plane/connect-inject/common/annotation_processor.go
  control-plane/connect-inject/common/annotation_processor_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/webhookv2/container_env.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2999 docs: add V2 RC changelog
  .changelog/2941.txt
Labels: pr/no-changelog, pr/no-backport

#3006 Disable Flaky Acceptance Tests
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/connect/local_rate_limit_test.go
Labels: pr/no-changelog, pr/no-backport

#3009 fix test
  control-plane/config-entries/controllersv2/meshconfig_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3014 Revert "update go mods"
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3013 activate rc nightly
  .github/workflows/nightly-acceptance-1-3-0-rc1.yml
Labels: pr/no-changelog, pr/no-backport

#3008 Load test for CTGW
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/cloud/load/main_test.go
  acceptance/tests/cloud/load/remote.go
  acceptance/tests/cloud/load/remote_load_test.go
  acceptance/tests/fixtures/bases/pingpong/template.tmpl
Labels: pr/no-changelog, pr/no-backport

#3023 support mesh v2 annotations in cni
  control-plane/cni/main.go
  control-plane/cni/main_test.go
Labels: pr/no-changelog, pr/no-backport

#3022 make enterprise version script more flexible
  control-plane/build-support/scripts/consul-enterprise-version.sh
Labels: pr/no-changelog, pr/no-backport

#3020 use custom images
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  control-plane/build-support/scripts/consul-enterprise-version.sh
Labels: pr/no-changelog, pr/no-backport

#3024 Mw/cherry pick cni annotation
  control-plane/cni/main.go
  control-plane/cni/main_test.go
Labels: pr/no-changelog, pr/no-backport
