Repository hashicorp/consul-k8s, pull requests merged in 2023-10, with the labels that each got.

#3010 [NET-5559] Clean up TODOs in Endpoints Controller V2
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3025 Point RC to RC Images
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  control-plane/build-support/functions/10-util.sh
  control-plane/build-support/scripts/consul-enterprise-version.sh
Labels: pr/no-changelog, pr/no-backport

#3029 [NET-5718] feat(control-plane): ServiceAccount v2 backoff on missing Consul NS
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_ent_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3032 Fix Flaky Wan Federation Failover Test
  acceptance/tests/wan-federation/wan_federation_test.go
Labels: pr/no-changelog, pr/no-backport

#3035 Fix Flaky Wan Federation Failover Test (#3032)
  acceptance/tests/wan-federation/wan_federation_test.go
Labels: pr/no-changelog, pr/no-backport

#3031 fix deprecated kustomize strategic merge
  acceptance/tests/fixtures/cases/crd-partitions/default-partition-default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/default-partition-ns1/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-ns1/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/non-default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-inject-multiport/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-multi-dc/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-namespaces/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/default-ns-default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/default-ns-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/ns-default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/ns-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/default/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/non-default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/static-server-inject/kustomization.yaml
Labels: pr/no-changelog, pr/no-backport

#3033 [NET-5805] Fixing validating cert webhooks, fixing replace statements for go mod
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/webhook-configuration/webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration_test.go
Labels: pr/no-changelog, pr/no-backport

#3034 Fixing validating cert webhooks, fixing replace statements for go mod
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/webhook-configuration/webhook_configuration.go
  control-plane/helper/webhook-configuration/webhook_configuration_test.go
Labels: pr/no-changelog, pr/no-backport

#3036 Update ci.hcl
  .release/ci.hcl
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#3039 [NET-5704] feat(control-plane): v2 only register services for injected pods
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3044 fix(v2): ca cert mounting path in mesh-init and dataplane
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/subcommand/connect-init/command.go
Labels: pr/no-changelog, pr/no-backport

#3047 fix(v2): ca cert mounting path in mesh-init and dataplane (#3044)
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/subcommand/connect-init/command.go
Labels: pr/no-changelog, pr/no-backport

#3048 Change from 'hub' to 'gh' for member checks on JIRA PR syncs
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog, pr/no-backport

#3045 [NET-5818] Fix Status for Gateway Policy
  charts/consul/templates/crd-gatewaypolicies.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api/v1alpha1/gatewaypolicy_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
Labels: pr/no-changelog, pr/no-backport

#3050 Update backport assistant to use merge commits
  .github/workflows/backport.yml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#3055 Manual backport of update backport assistant to use merge commits to 1.1.x
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#3054 Manual backport of update backport assistant to use merge commits to 1.0.x
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#3046 NET-5818 Gateway Policy Status
  charts/consul/templates/crd-gatewaypolicies.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api/v1alpha1/gatewaypolicy_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
Labels: pr/no-changelog, pr/no-backport

#3058 revert backport assistant changes
  .github/workflows/backport.yml
Labels: pr/no-changelog, pr/no-backport

#3052 Net 5640 route binding unit tests 1 3 branch
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
Labels: pr/no-changelog, pr/no-backport

#3051 [Net-5640] Route Binding Unit Tests
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/result_test.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
Labels: pr/no-changelog, pr/no-backport

#3065 Fix Gateway API CRDs
  .copywrite.hcl
  control-plane/config/crd/external/.yml
  control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml
Labels: pr/no-changelog, pr/no-backport

#3066 Manual backport of Fix Gateway API CRDs
  .copywrite.hcl
  control-plane/config/crd/external/.yml
  control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml
Labels: pr/no-changelog, pr/no-backport

#3059 Mw/prepare release
  .changelog/2941.txt
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3068 [NET-5717] feat(control-plane): v2 add service account name to workload identity meta
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
Labels: pr/no-changelog, pr/no-backport

#3057 Fix local rate limiting acceptance tests
  acceptance/tests/connect/local_rate_limit_test.go
Labels: pr/no-changelog, pr/no-backport

#3069 test: fix tests now that v1 catalog disabled in v2 mode
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/test/test_util.go
  control-plane/namespaces/namespaces_test.go
Labels: pr/no-changelog, pr/no-backport

#3070 NET-5947 Add NET_BIND_SERVICE capability in security context for api-gateway pod on OpenShift
  .changelog/3070.txt
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
Labels: theme/openshift, theme/api-gateway, backport/1.2.x

#3049 [NET-5681] v2: Debounce unnecessary Service writes to Consul
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/endpointsv2/write_cache.go
  control-plane/connect-inject/controllers/endpointsv2/write_cache_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#3077 Fix ENT Tests Now that They Are Running Again 🏃
  control-plane/config-entries/controllers/configentry_controller_ent_test.go
  control-plane/config-entries/controllersv2/meshconfig_controller_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
Labels: pr/no-changelog, pr/no-backport

#3082 Backport of Fix ENT Tests Now that They Are Running Again 🏃 into release/1.2.x
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/controllers/configentry_controller_ent_test.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
Labels: theme/testing, pr/no-changelog, pr/no-backport

#3085 [NET-5944] security: Upgrade Go and x/net
  .changelog/3085.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: area/security, backport/1.0.x, backport/1.1.x, backport/1.2.x

#3081 ACL Updates for v2 ResourceAPI
  acceptance/tests/mesh_v2/mesh_inject_test.go
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  control-plane/config-entries/controllersv2/meshconfig_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/test/test_util.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/mesh-init/command_test.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/create_or_update_test.go
  control-plane/subcommand/server-acl-init/rules.go
  control-plane/subcommand/server-acl-init/rules_test.go
Labels: pr/no-changelog, pr/no-backport

#3084 Backport of Fix ENT Tests Now that They Are Running Again 🏃 into release/1.1.x
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
Labels: pr/no-changelog, pr/no-backport

#3089 Manual backport of [NET-5944] security: Upgrade Go and x/net into release/1.0.x
  .changelog/3085.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#3083 Add New Make Target for prepare release dev
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3093 bump patch version
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3099 [NET-5402] Halting Test with JWT
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
Labels: pr/no-changelog, backport/1.3.x

#3094 remove dev tag
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3104 Mw/port dans changes from prepare 1 4 dev
  .github/workflows/build.yml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.3.x

#3107 Mw/port dans changes from prepare 1 4 dev (#3104)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3078 disable TestPartitions_Connect for CNI due to flake
  acceptance/tests/partitions/partitions_connect_test.go
Labels: pr/no-changelog, backport/1.3.x

#3110 Mw/port dans changes from prepare 1 4 dev (#3104)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3096 add probes now that expose paths are supported
  acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml
  acceptance/tests/mesh_v2/mesh_inject_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
Labels: pr/no-changelog, backport/1.3.x

#3105 disable TestPartitions_Connect for CNI due to flake
  acceptance/tests/partitions/partitions_connect_test.go
Labels: pr/no-changelog, pr/no-backport

#3108 Mw/port dans changes from prepare 1 4 dev (#3104)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3112 add probes now that expose paths are supported (#3096)
  acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml
  acceptance/tests/mesh_v2/mesh_inject_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
Labels: pr/no-changelog, pr/no-backport

#3116 Update Envoy
  .changelog/3116.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3117 release/1.3.0 - Update Envoy
  .changelog/3117.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3118 release/1.3.x - Update Envoy
  .changelog/3118.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3119 release/1.2.x - Update Envoy
  .changelog/3119.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3121 release/1.0.x - Update Envoy
  .changelog/3121.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3120 release/1.1.x - Update Envoy
  .changelog/3120.txt
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-backport

#3124 Remove copyright headers from external crds
  .copywrite.hcl
  control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml
  control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x

#3103 test(v2): check for token deletion in acceptance test
  acceptance/tests/mesh_v2/mesh_inject_test.go
Labels: pr/no-changelog, backport/1.3.x

#3128 NET-6204- Repeating error log in consul-connect-injector
  .changelog/3128.txt
  control-plane/api-gateway/cache/gateway.go
Labels: backport/1.2.x, backport/1.3.x

#2946 [CC 5965] Improve HCP Observability E2E tests and add periodic tests
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  acceptance/tests/cloud/observability_test.go
  acceptance/tests/fixtures/bases/cloud/hcp-mock/deployment.yaml
Labels: pr/no-changelog, pr/no-backport

#3140 Backport of [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487) to release/1.3.x
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-backport

#3148 Backport of [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487) to release/1.3.0
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-backport

#3141 Backport of [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487) to release/1.2.x
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-backport

#3142 Backport of [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487) to release/1.1.x
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-backport

#3143 Backport of [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487) to release/1.0.x
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-backport

#3139 [NET-6138] security: Bump google.golang.org/grpc to 1.56.3 (CVE-2023-44487)
  .changelog/3139.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/copy-crds-to-chart/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: area/security, pr/no-backport

#3149 build(docker): remove extraneous docker build for UBI
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3138 Update kubernetes to 1.28.x
  .changelog/3138.txt
  .github/workflows/pr.yml
  README.md
  acceptance/ci-inputs/kind-inputs.yaml
  charts/consul/test/terraform/gke/main.tf
  charts/consul/test/terraform/gke/outputs.tf
Labels: backport/1.3.x

#3151 Update kubernetes to 1.28.x in release/1.3.0
  .changelog/3138.txt
  .github/workflows/pr.yml
  README.md
  acceptance/ci-inputs/kind-inputs.yaml
  charts/consul/Chart.yaml
  charts/consul/test/terraform/gke/main.tf
  charts/consul/test/terraform/gke/outputs.tf
Labels: pr/no-backport

#3152 Update chart version
  charts/consul/Chart.yaml
Labels: pr/no-changelog, pr/no-backport
