Repository hashicorp/consul-k8s, pull requests merged in 2023-02, with the labels that each got.

#1869 Exclude openebs namespace from injection.
  CHANGELOG.md
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x

#1877 Refine server TLS Vault PKI role config in acceptance tests
  acceptance/framework/vault/helpers.go
Labels: backport/0.49.x, backport/1.0.x

#1882 Dockerfile: Remove gnupg from Consul k8s container
  CHANGELOG.md
  control-plane/Dockerfile
Labels: backport/0.49.x, backport/1.0.x

#1885 Dockerfile: remove `gnupg` from dev image
  CHANGELOG.md
  control-plane/Dockerfile
Labels: backport/0.49.x, backport/1.0.x

#1881 NET-1750 Fixes ACL init command Consul Login Datacenter mixup
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/client-daemonset.bats
  control-plane/subcommand/acl-init/command.go
Labels: backport/1.0.x

#1770 Update server-acl-init to always check for the deployed serviceAccountToken secret
  CHANGELOG.md
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/connect_inject_test.go
Labels: theme/openshift, backport/1.0.x

#1915 GitHub actions now uses branch local reusable tests
  .github/workflows/test.yml
Labels: backport/1.0.x, backport/1.1.x

#1908 Pipeline Updates
  .circleci/config.yml
  .github/workflows/reusable-acceptance.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test.yml
  .go-version
  CHANGELOG.md
  acceptance/go.mod
  charts/go.mod
  cli/go.mod
  control-plane/cni/go.mod
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/common/common_test.go
  hack/aws-acceptance-test-cleanup/go.mod
  hack/copy-crds-to-chart/go.mod
  hack/helm-reference-gen/go.mod
Labels: backport/1.1.x

#1931 Fix a typo in circleci config
  .circleci/config.yml
Labels: backport/1.1.x

#1934 Dockerfile: bump Alpine base image to 3.17
  CHANGELOG.md
  control-plane/Dockerfile
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#1900 Update docs for global.tls.caKey
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#1890 Update links to support DevDot
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#1947 Added support for go-changelog automations
  .changelog/changelog.tmpl
  .changelog/note.tmpl
  .github/workflows/changelog-checker.yml
  CONTRIBUTING.md
  Makefile
  control-plane/build-support/functions/10-util.sh
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#1960 Cherry pick go changelog 1 0
  .changelog/changelog.tmpl
  .changelog/note.tmpl
  .github/workflows/changelog-checker.yml
  CONTRIBUTING.md
  Makefile
  control-plane/build-support/functions/10-util.sh
Labels: pr/no-changelog

#1959 Cherry pick go changelog 0 49
  .changelog/changelog.tmpl
  .changelog/note.tmpl
  .github/workflows/changelog-checker.yml
  CONTRIBUTING.md
  Makefile
  control-plane/build-support/functions/10-util.sh
Labels: pr/no-changelog
