Repository hashicorp/consul-k8s, pull requests merged in 2023-08, with the labels that each got.

#2696 Manual backport of Added logLevel field for components (#2302)
  .changelog/2302.txt
  charts/consul/templates/client-config-configmap.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/test/unit/client-config-configmap.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/create-federation-secret-job.bats
  charts/consul/test/unit/gossip-encryption-autogenerate-job.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/test/unit/tls-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2710 [NET-5146] security: Upgrade Go and `x/net`
  .changelog/2710.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2705 Backport of do not set securityContext on Openshift < 4.11 (#2678)
  .changelog/2678.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#2709 Increase timeout while waiting for vault server to be ready
  acceptance/framework/vault/vault_cluster.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2716 Acceptance tests: increase api-gateway retries
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/partitions/partitions_gateway_test.go
Labels: pr/no-changelog, backport/1.2.x

#2695 Manual backport of added logLevel field for components
  .changelog/2302.txt
  charts/consul/templates/client-config-configmap.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/test/unit/client-config-configmap.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/create-federation-secret-job.bats
  charts/consul/test/unit/gossip-encryption-autogenerate-job.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/test/unit/tls-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2697 Manual backport of Added logLevel field for components (#2302)
  .changelog/2302.txt
  charts/consul/templates/client-config-configmap.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/test/unit/client-config-configmap.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/create-federation-secret-job.bats
  charts/consul/test/unit/gossip-encryption-autogenerate-job.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/server-acl-init-cleanup-job.bats
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
  charts/consul/test/unit/tls-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2733 Acceptance tests: increase api-gateway retries (#2716)
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/partitions/partitions_gateway_test.go
Labels: pr/no-changelog, pr/no-backport

#2184 NET-3908: allow configuration of SecurityContextConstraints when running on OpenShift
  .changelog/2184.txt
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/connect-inject-clusterrole.bats
  charts/consul/test/unit/gateway-resources-job.bats
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/api-gateway/gatekeeper/role.go
  control-plane/api-gateway/gatekeeper/rolebinding.go
  control-plane/api-gateway/gatekeeper/serviceaccount.go
  control-plane/api/v1alpha1/api_gateway_types.go
  control-plane/api/v1alpha1/api_gateway_types_test.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/api-gateway, pr/no-backport

#2707 NET-5104 envoy port mapping
  .changelog/2707.txt
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/service.go
  control-plane/api/v1alpha1/api_gateway_types.go
  control-plane/subcommand/gateway-resources/command.go
Labels: theme/api-gateway, backport/1.2.x

#2702 Support restricted PSA enforcement part 2
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/k8s/helpers.go
  acceptance/tests/wan-federation/wan_federation_test.go
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2741 Backport of Support restricted PSA enforcement part 2 into release/1.1.x
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/k8s/helpers.go
  acceptance/tests/wan-federation/wan_federation_test.go
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
Labels: pr/no-changelog, pr/no-backport

#2742 Backport of Support restricted PSA enforcement part 2 into release/1.2.x
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/k8s/helpers.go
  acceptance/tests/wan-federation/wan_federation_test.go
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
Labels: pr/no-changelog, pr/no-backport

#2711 NET-4413 Implement translation + validation of TLS options
  .changelog/2711.txt
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
  control-plane/api-gateway/common/constants.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
Labels: theme/api-gateway, backport/1.2.x

#2706 NET-4993 JWT auth basic acceptance test
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/api-gateway.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/gateway-policy.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/httproute-auth.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/httproute.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-provider.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-route-filter.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/kustomization.yaml
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#2750 Prerelease work for 1.1.4
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2754 Adds changelog for release of 1.1.4
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2753 Reset to dev after release of 1.1.4
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2708 docs: Update outdated `consul.io` links
  .release/release-metadata.hcl
  CONTRIBUTING.md
  README.md
  acceptance/framework/vault/helpers.go
  charts/consul/Chart.yaml
  charts/consul/README.md
  charts/consul/templates/NOTES.txt
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/test/unit/mesh-gateway-deployment.bats
  cli/cmd/install/install.go
  control-plane/api/v1alpha1/proxydefaults_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/subcommand/common/common.go
  hack/helm-reference-gen/fixtures/full-values.golden
  hack/helm-reference-gen/fixtures/full-values.yaml
Labels: pr/no-changelog, pr/no-backport

#2755 Set privileged to false unless on OpenShift without CNI
  .changelog/2755.txt
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2765 Backport of Set privileged to false unless on OpenShift without CNI into release/1.1.x
  .changelog/2755.txt
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-backport

#2757 Updates branch for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2766 Updates branch for dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/scripts/consul-enterprise-version.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2768 Adds changelog for 1.2.1, reorders 1.1.4 and 1.0.9
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2775 Update helm values based on review from docs team
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2774 updates helm values based on review from docs team
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2778 Updates helm values based on review from docs team
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2776 Mw/net 4260 add tproxy coverage
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/patch.yaml
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, backport/1.2.x

#2784 [NET-2880] Add `PrioritizeByLocality` to `ProxyDefaults` CRD
  .changelog/2357.txt
  .changelog/2784.txt
  charts/consul/templates/crd-proxydefaults.yaml
  control-plane/api/v1alpha1/proxydefaults_types.go
  control-plane/api/v1alpha1/proxydefaults_types_test.go
  control-plane/api/v1alpha1/serviceresolver_types.go
  control-plane/api/v1alpha1/serviceresolver_types_test.go
  control-plane/api/v1alpha1/shared_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
Labels: pr/no-backport

#2771 Add readOnlyRootFilesystem to security context
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-changelog, backport/1.2.x

#2792 AKS 1.24 is deprecated, update to latest 1.25 patch
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/variables.tf
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2794 Automate the k8s sameness tests add peering (#2725)
  acceptance/tests/fixtures/bases/sameness/cluster-03-a-default-ns/sameness.yaml
  acceptance/tests/fixtures/bases/sameness/override-ns/intentions.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/patch.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/patch.yaml
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, pr/no-backport

#2735 Net 4889 implement retry feature on the api gateway
  .changelog/2735.txt
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/crd-routeretryfilters.yaml
  charts/consul/templates/crd-routetimeoutfilters.yaml
  control-plane/PROJECT
  control-plane/api-gateway/binding/result.go
  control-plane/api-gateway/binding/route_binding.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/helpers.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/index.go
  control-plane/api/v1alpha1/routeretryfilter_types.go
  control-plane/api/v1alpha1/routetimeoutfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_routeretryfilters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routetimeoutfilters.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#2786 Update Kustomize to use `patches` instead of `patchesStrategicMerge`
  CONTRIBUTING.md
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/default-partition-default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/default-partition-ns1/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-ns1/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/default/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/non-default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/crds-ent/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/cluster-01-a-acceptor/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/cluster-01-b-acceptor/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/cluster-02-a-acceptor/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/cluster-03-a-acceptor/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/ap1-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/exported-services/default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-client/default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/dc1-default/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/dc1-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/dc2/kustomization.yaml
  acceptance/tests/fixtures/cases/sameness/static-server/dc3/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-inject-multiport/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-multi-dc/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-namespaces/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-openshift-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/default-ns-default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/default-ns-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/ns-default-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-partitions/ns-partition/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/default/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-peers/non-default-namespace/kustomization.yaml
  acceptance/tests/fixtures/cases/static-client-tproxy/kustomization.yaml
  acceptance/tests/fixtures/cases/static-server-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/static-server-openshift/kustomization.yaml
  control-plane/config/crd/kustomization.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2791 [NET-4498] Test locality propagation to services from k8s
  acceptance/framework/k8s/kubectl.go
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, pr/no-backport

#2801 Use Kubernetes 1.25 on AKS
  charts/consul/test/terraform/aks/variables.tf
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2805 Point mod to main to fix build errors
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2811 manual backport of AKS 1.25 into 1.2.x
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/variables.tf
Labels: pr/no-changelog, pr/no-backport

#2809 manual backport of AKS 1.25 into 1.0.x
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/variables.tf
Labels: pr/no-changelog, pr/no-backport

#2810 manual backport of AKS 1.25 into 1.1.x
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/variables.tf
Labels: pr/no-changelog, pr/no-backport

#2812 Fix peer test flakes.
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2669 net-1776, add job lifecycle test and changes to connhelper
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/k8s/deploy.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/fixtures/bases/job-client/job.yaml
  acceptance/tests/fixtures/bases/job-client/kustomization.yaml
  acceptance/tests/fixtures/bases/job-client/service.yaml
  acceptance/tests/fixtures/bases/job-client/serviceaccount.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/patch.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2743 Net 1784 inject sidecar first
  .changelog/2743.txt
  acceptance/framework/connhelper/connect_helper.go
  acceptance/tests/connect/connect_external_servers_test.go
  acceptance/tests/connect/connect_inject_namespaces_test.go
  acceptance/tests/connect/connect_inject_test.go
  acceptance/tests/metrics/metrics_test.go
  acceptance/tests/partitions/partitions_connect_test.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
Labels: backport/1.2.x

#2789 Add readOnlyRootFilesystem to security context (#2771)
  .changelog/2789.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.2.x

#2831 Add readOnlyRootFilesystem to security context (#2771) backport to 1.2.x
  .changelog/2789.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#2823 feat: func to create V2 resource client
  control-plane/consul/consul.go
  control-plane/consul/resource_client.go
  control-plane/consul/resource_client_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2800 feat: add helm value for consul resource-apis experiment
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/test/unit/helpers.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/partition-init/command.go
Labels: pr/no-changelog, pr/no-backport

#2829 Manual Backport of #2669 into 1.2.x
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/k8s/deploy.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/fixtures/bases/job-client/job.yaml
  acceptance/tests/fixtures/bases/job-client/kustomization.yaml
  acceptance/tests/fixtures/bases/job-client/service.yaml
  acceptance/tests/fixtures/bases/job-client/serviceaccount.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/patch.yaml
Labels: pr/no-changelog, pr/no-backport

#2822 add sameness testing performance enhancement
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, pr/no-backport

#2787 NET-5186 Add NET_BIND_SERVICE capability to Consul's restricted securityContext
  .changelog/2787.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2816 Added tests for partition dns/pq
  acceptance/tests/sameness/sameness_test.go
Labels: pr/no-changelog, pr/no-backport

#2797 Mw/net 4888 add namespace tests failover wan fed
  acceptance/framework/connhelper/connect_helper.go
  acceptance/tests/cli/cli_install_test.go
  acceptance/tests/connect/connect_inject_test.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/fixtures/bases/service-resolver/kustomization.yaml
  acceptance/tests/fixtures/bases/service-resolver/service-resolver.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-ns2-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-ns2-static-server/patch.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc1-static-server/patch.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc2-static-server/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/dc2-static-server/patch.yaml
  acceptance/tests/fixtures/cases/wan-federation/service-resolver/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/service-resolver/patch.yaml
  acceptance/tests/fixtures/cases/wan-federation/static-client/kustomization.yaml
  acceptance/tests/fixtures/cases/wan-federation/static-client/patch.yaml
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  acceptance/tests/wan-federation/wan_federation_test.go
Labels: pr/no-changelog, pr/no-backport

#2734 NET-4978: New CRDs for GW JWT Auth
  .changelog/2734.txt
  CONTRIBUTING.md
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/gateway-policy.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-provider.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-route-filter.yaml
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/crd-gatewaypolicies.yaml
  charts/consul/templates/crd-routeauthfilters.yaml
  charts/consul/test/unit/crd-gatewaypolicies.bats
  charts/consul/test/unit/crd-routeauthfilters.bats
  control-plane/PROJECT
  control-plane/api/common/common.go
  control-plane/api/v1alpha1/gatewaypolicy_types.go
  control-plane/api/v1alpha1/routeauthfilter_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routeauthfilters.yaml
Labels: theme/api-gateway, pr/no-backport

#2842 fix: lifecycle enabled iptables mismatch
  acceptance/framework/connhelper/connect_helper.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
Labels: pr/no-changelog, backport/1.2.x

#2832 refactor: make space for v2 controllers
  control-plane/consul/resource_client.go
  control-plane/consul/resource_client_test.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/inject-connect/v1controllers.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport

#2846 build: update SDK version to use commit from
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2847 Revert "Add readOnlyRootFilesystem to security context (#2771)"
  .changelog/2789.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-changelog, backport/1.2.x

#2843 Fix issue where CLI install test was running Tproxy manually
  acceptance/tests/cli/cli_install_test.go
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x

#2723 Configure Gateway Deployment Resources
  .changelog/2723.txt
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/gateway-policy.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-provider.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/jwt-route-filter.yaml
  charts/consul/templates/crd-controlplanerequestlimits.yaml
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  charts/consul/templates/crd-gatewayclasses.yaml
  charts/consul/templates/crd-gateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-jwtproviders.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-meshservices.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-samenessgroups.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-tcproutes.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  charts/consul/templates/crd-tlsroutes.yaml
  charts/consul/templates/crd-udproutes.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
  charts/consul/values.yaml
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api/v1alpha1/api_gateway_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/subcommand/gateway-resources/command.go
Labels: backport/1.2.x

#2782 correct prometheus port and scheme annotations if tls is enabled
  .changelog/2782.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2796 Adds fields for PassiveHealthCheck on IngressGateway
  .changelog/2796.txt
  acceptance/tests/fixtures/bases/job-client/job.yaml
  acceptance/tests/fixtures/bases/job-client/service.yaml
  acceptance/tests/fixtures/bases/job-client/serviceaccount.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/patch.yaml
  acceptance/tests/fixtures/cases/jobs/job-client-inject/patch.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-routeretryfilters.yaml
  charts/consul/templates/crd-routetimeoutfilters.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  control-plane/api/v1alpha1/ingressgateway_types.go
  control-plane/api/v1alpha1/ingressgateway_types_test.go
  control-plane/api/v1alpha1/servicedefaults_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routeretryfilters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_routetimeoutfilters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/consul/resource_client.go
  control-plane/consul/resource_client_test.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#2790 added check if anonymous token policy exists
  .changelog/2790.txt
  control-plane/subcommand/server-acl-init/anonymous_token.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, consul-india

#2865 Backport/net 5174/anonymous token policy/manual
  .changelog/2790.txt
  control-plane/subcommand/server-acl-init/anonymous_token.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
Labels: backport/1.0.x

#2785 Net 5229 create dedicated argocd stanza
  .changelog/2785.txt
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, consul-india

#2872 Backport of Net 5229 create dedicated argocd stanza (#2785) in release 1.2.x
  .changelog/2785.txt
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2873 Backport - Net 5229 create dedicated argocd stanza (#2785) in release 1.1.x
  .changelog/2785.txt
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2874 Backport - Net 5229 create dedicated argocd stanza (#2785) in release 1.0.x
  .changelog/2785.txt
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#2877 Manual backport of correct prometheus port and scheme annotations if tls is enabled (#2782)
  .changelog/2782.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#2876 Manual backport of correct prometheus port and scheme annotations if tls is enabled (#2782)
  .changelog/2782.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#2878 Manual backport of correct prometheus port and scheme annotations if tls is enabled (#2782)
  .changelog/2782.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#2871 docs - Update connectInject.logLevel docs
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x
