Repository hashicorp/consul-k8s, pull requests merged in 2023-11, with the labels that each got.

#3147 Update ci.hcl (#3036)
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-backport

#3146 Update ci.hcl (#3036)
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-backport

#3144 Update ci.hcl (#3036)
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-backport

#3153 main: revert k8s version to 1.22.x
  charts/consul/Chart.yaml
Labels: pr/no-changelog, pr/no-backport

#3155 1.3.x: revert k8s version to 1.22.x
  charts/consul/Chart.yaml
Labels: pr/no-changelog, pr/no-backport

#3156 1.3.0: revert k8s version to 1.22.x
  charts/consul/Chart.yaml
Labels: pr/no-changelog, pr/no-backport

#3114 Add Acceptance Test for Cluster Peered Terminating Gateway
  acceptance/framework/helpers/helpers.go
  acceptance/tests/fixtures/cases/crd-peers/external/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/external/patch.yaml
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/terminating-gateway/common.go
  acceptance/tests/terminating-gateway/terminating_gateway_destinations_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3164 Prepare release v1.2.3
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3165 Prepare release v1.1.7
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3162 fix(controller): v2 pod controller error log for missing ip
  .changelog/3162.txt
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
Labels: backport/1.3.x

#3168 Post release 1.2.3
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3170 Post release for 1.0.11
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3169 post release for 1.1.7
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3172 fix(controller): v2 pod controller errors for acl deletion
  .changelog/3172.txt
  control-plane/config-entries/controllersv2/meshconfig_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
Labels: backport/1.3.x

#3167 Release 1.2.3, 1.1.7 and 1.0.11 changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#3182 NET-6303 Prepare for release of 1.3.0
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#3178 NET-5392 Replace dev dependencies w/ latest release tags
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api/mesh/v2beta1/proxy_configuration_types_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3181 NET-5392 Replace dev dependencies w/ latest release tags
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api/mesh/v2beta1/proxy_configuration_types_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, backport/1.3.x

#3158 NET 6409
  .changelog/3158.txt
  cli/cmd/proxy/stats/command.go
  cli/cmd/proxy/stats/command_test.go
  cli/commands.go
  cli/common/envoy/http_test.go
  cli/common/portforward.go
Labels: backport/1.1.x, backport/1.2.x, consul-india, backport/1.3.x

#3180 [NET-5025] Helm Chart: Support StatefulSet PVC retention
  .changelog/3180.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3193 NET-6303 Add 1.3.0 notes to changelog
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.3.x

#3194 Add replace directive in Go mod for Control Plane so that we pull in the latest Consul submodules
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3195 NET-6331 Create MeshGateway CRD
  charts/consul/templates/crd-meshgateways.yaml
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
Labels: pr/no-changelog, pr/no-backport

#3202 Add validation to account for type change
  control-plane/api/v1alpha1/routetimeoutfilter_types.go
  control-plane/config/crd/bases/consul.hashicorp.com_routetimeoutfilters.yaml
Labels: pr/no-changelog, backport/1.3.x

#3196 NET-4992- Kitchen sink gateway test
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/api-gateway.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/external-ref.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/filters.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/gateway-policy.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/gatewayclassconfig.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/httproute.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/jwt-provider.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/jwt-route-filter.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink-ent/kustomization.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/api-gateway.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/external-ref.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/filters.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/gateway-policy.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/gatewayclassconfig.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/httproute.yaml
  acceptance/tests/fixtures/cases/api-gateways/kitchen-sink/kustomization.yaml
Labels: pr/no-changelog, backport/1.3.x

#3200 NET-6406 Adds GatewayClassConfig and MeshGateway resources to the gateway-reso…
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
Labels: pr/no-changelog, pr/no-backport

#3179 chore: skaffold build experiment
  Makefile
  control-plane/Dockerfile.dev
Labels: pr/no-changelog, pr/no-backport

#3209 fix(control-plane): sidecar CPU limit incorrectly validated against CPU request
  .changelog/3209.txt
  control-plane/subcommand/inject-connect/command.go
Labels: backport/1.3.x

#3175 Update rate limiting acceptance test to burst requests in one exec
  acceptance/tests/connect/local_rate_limit_test.go
Labels: pr/no-changelog, backport/1.3.x

#3221 Add -output-format json to consul-k8s proxy list command
  .changelog/3221.txt
  cli/cmd/proxy/list/command.go
  cli/cmd/proxy/list/command_test.go
  cli/common/terminal/table.go
Labels: backport/1.1.x, backport/1.2.x, consul-india, backport/1.3.x

#3231 Remove nightly and weekly jobs
  .github/workflows/nightly-acceptance-1-3-0.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
Labels: pr/no-changelog, pr/no-backport

#3213 NET-6563 Stub CRUD hooks for MeshGatewayController
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3224 Add Mesh GatewayClass CRD
  charts/consul/templates/crd-gatewayclasses.yaml
  control-plane/api/mesh/v2beta1/gateway_class_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclasses.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3222 feat: add named prom port to dataplane sidecar
  .changelog/3222.txt
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
Labels: backport/1.3.x

#3234 backport of 3222: feat: add named prom port to dataplane sidecar
  .changelog/3222.txt
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
Labels: pr/no-backport

#3216 Add CRD for MeshConfiguration
  charts/consul/templates/crd-meshconfigurations.yaml
  control-plane/api/mesh/v2beta1/mesh_configuration_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshconfigurations.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3225 Net 6529 Gatewayclassconfig CRD
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
Labels: pr/no-changelog, pr/no-backport

#3219 Add `telemetryCollector.cloud.resourceId` field that works even when `global.cloud.enabled` is false
  .changelog/3219.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/telemetry-collector-v2-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/telemetry-collector-v2-deployment.bats
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3236 NET-6664 Specify cluster scope for MeshGateway CRD
  charts/consul/templates/crd-meshgateways.yaml
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3137 Add refreshes and retries to server-acl-init job
  .changelog/3137.txt
  control-plane/consul/dynamic.go
  control-plane/consul/dynamic_test.go
  control-plane/subcommand/server-acl-init/anonymous_token.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/create_or_update.go
  control-plane/subcommand/server-acl-init/create_or_update_test.go
  control-plane/subcommand/server-acl-init/servers.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3198 uniform make file experience
  Makefile
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3257 Backport of uniform make file experience into release/1.1.x
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3258 Backport of uniform make file experience into release/1.2.x
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3259 Backport of uniform make file experience into release/1.3.x
  Makefile
Labels: pr/no-changelog, pr/no-backport

#3237 [NET-6617] security: Bump github.com/golang-jwt/jwt/v4 to 4.5.0
  .changelog/3237.txt
  cli/go.mod
  cli/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3241 Backport of Add telemetryCollector.cloud.resourceId field that works even when global.cloud.enabled is false into release/1.1.x
  .changelog/3219.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#3242 Backport of Add telemetryCollector.cloud.resourceId field that works even when global.cloud.enabled is false into release/1.2.x
  .changelog/3219.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#3245 NET-6536 Adds stub of GatewayClass controller into v2 controllers
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api/common/common.go
  control-plane/api/mesh/v2beta1/gateway_class_types.go
  control-plane/config-entries/controllersv2/gateway_class_controller.go
  control-plane/config/rbac/role.yaml
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3210 fixed acl deletetion in endpoints controller
  .changelog/3210.txt
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/subcommand/flags/consul.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x

#3278 fixed acl deletetion in endpoints controller (#3210)
  .changelog/3210.txt
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
Labels: pr/no-backport

#3279 fixed acl deletetion in endpoints controller (#3210)
  .changelog/3210.txt
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
Labels: pr/no-backport

#3276 fixed acl deletetion in endpoints controller (#3210)
  .changelog/3210.txt
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/subcommand/flags/consul.go
Labels: pr/no-backport

#3265 Remove Duplicate UBI Tags
  .github/workflows/build.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3270 Backport of Fix consul-telemetry-collector deployments to non-default namespaces into release/1.1.x
  .changelog/3215.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  acceptance/tests/cloud/observability_test.go
  acceptance/tests/cloud/remote_dev_test.go
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
Labels: pr/no-backport

#3271 Backport of Fix consul-telemetry-collector deployments to non-default namespaces into release/1.2.x
  .changelog/3215.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  acceptance/tests/cloud/observability_test.go
  acceptance/tests/cloud/remote_dev_test.go
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
Labels: pr/no-backport

#3244 NET-6394 Create/update/delete ServiceAccount on MeshGateway reconcile
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/gateways/builder.go
  control-plane/gateways/labels.go
  control-plane/gateways/serviceaccount.go
  control-plane/gateways/serviceaccount_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3272 Backport of Fix consul-telemetry-collector deployments to non-default namespaces into release/1.3.x
  .changelog/3215.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/cloud/basic_test.go
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  acceptance/tests/cloud/observability_test.go
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/telemetry-collector-v2-deployment.yaml
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/test/unit/telemetry-collector-v2-deployment.bats
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
Labels: pr/no-backport

#3253 Net 6535- GatewayClassConfig controller stubs
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/crd-gatewayclassconfigs-v1.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  control-plane/api/common/common.go
  control-plane/config-entries/controllersv2/gateway_class_config_controller.go
  control-plane/config/rbac/role.yaml
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3251 Backport of Add refreshes and retries to server-acl-init job (#3137) to release/1.2.x
  .changelog/3137.txt
  control-plane/consul/dynamic.go
  control-plane/consul/dynamic_test.go
  control-plane/subcommand/server-acl-init/anonymous_token.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/create_or_update.go
  control-plane/subcommand/server-acl-init/create_or_update_test.go
  control-plane/subcommand/server-acl-init/servers.go
Labels: pr/no-backport

#3252 Backport of Add refreshes and retries to server-acl-init job (#3137) to release/1.1.x
  .changelog/3137.txt
  control-plane/consul/dynamic.go
  control-plane/consul/dynamic_test.go
  control-plane/subcommand/server-acl-init/anonymous_token.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/connect_inject.go
  control-plane/subcommand/server-acl-init/create_or_update.go
  control-plane/subcommand/server-acl-init/create_or_update_test.go
  control-plane/subcommand/server-acl-init/servers.go
Labels: pr/no-backport

#3282 Set cron jobs for release branches back to weekly
  .github/workflows/weekly-acceptance-1-1-x.yml
  .github/workflows/weekly-acceptance-1-2-x.yml
  .github/workflows/weekly-acceptance-1-3-x.yml
Labels: pr/no-changelog, pr/no-backport

#3281 Net 6555 Adds field to MeshGW Crd based on new Consul Proto
  Makefile
  charts/consul/templates/crd-meshgateways.yaml
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3283 NET-6722 Rename MeshConfigController to ConsulResourceController
  control-plane/api/auth/v2beta1/trafficpermissions_webhook.go
  control-plane/api/common/consul_resource.go
  control-plane/api/common/consul_resource_webhook.go
  control-plane/api/common/consul_resource_webhook_test.go
  control-plane/api/mesh/v2beta1/grpc_route_webhook.go
  control-plane/api/mesh/v2beta1/http_route_webhook.go
  control-plane/api/mesh/v2beta1/proxy_configuration_route_webhook.go
  control-plane/api/mesh/v2beta1/tcp_route_webhook.go
  control-plane/config-entries/controllersv2/consul_resource_controller.go
  control-plane/config-entries/controllersv2/consul_resource_controller_test.go
  control-plane/config-entries/controllersv2/gateway_class_config_controller.go
  control-plane/config-entries/controllersv2/gateway_class_controller.go
  control-plane/config-entries/controllersv2/grpc_route_controller.go
  control-plane/config-entries/controllersv2/http_route_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller.go
  control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
  control-plane/config-entries/controllersv2/proxy_configuration_controller.go
  control-plane/config-entries/controllersv2/tcp_route_controller.go
  control-plane/config-entries/controllersv2/traffic_permissions_controller.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: pr/no-changelog, pr/no-backport
