Repository hashicorp/consul-k8s, pull requests merged in 2023-03, with the labels that each got.

#1965 updated security scan to have parity with consul-dataplane
  .release/security-scan.hcl
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#1969 add 365 days instead of 1 year to account for leap years
  control-plane/subcommand/tls-init/command_test.go
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#1974 disable go mod scanning
  .release/security-scan.hcl
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#1981 added changelog files
  .changelog/1770.txt
  .changelog/1914.txt
  .changelog/1934.txt
  CHANGELOG.md
Labels: pr/no-changelog

#1980 added changelog files
  .changelog/1770.txt
  .changelog/1934.txt
  .changelog/1953.txt
  CHANGELOG.md
Labels: pr/no-changelog

#1982 Mw/add backport checker
  .github/workflows/backport-checker.yml
  .github/workflows/changelog-checker.yml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#1920 NET-1721: Automatic ACL bootstrap with Vault secrets backend
  .changelog/1920.txt
  acceptance/framework/vault/helpers.go
  acceptance/tests/vault/vault_test.go
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/values.yaml
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/k8s_secrets_backend.go
  control-plane/subcommand/server-acl-init/secrets_backend.go
  control-plane/subcommand/server-acl-init/servers.go
  control-plane/subcommand/server-acl-init/test_fake_secrets_backend.go
  control-plane/subcommand/server-acl-init/vault_secrets_backend.go
Labels: backport/1.1.x

#1990 Mw/update to 1.15.1
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, pr/no-changelog

#1993 update to consul 1.13.7
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#1992 update to consul 1.14.5
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#1999 Prepare 1.0.5 Release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2000 Prepare for 0.49.5 Release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#1998 Mw/update to 1.15.1 (#1990)
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#2002 prepare for 1.1.1 release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2001 Fix changelog for 1.0.5
  .changelog/1953.txt
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#2003 ready for 1.0.6 dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2004 ready for 0.49.6 dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2005 Mw/reset 1 1 x dev mode
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2006 added more retries for tests
  acceptance/framework/consul/cli_cluster.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/helpers/helpers.go
  acceptance/framework/portforward/port_forward.go
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x, pr/no-changelog

#2013 Add SNI skip for client node configuration
  .changelog/2013.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: backport/1.0.x, backport/1.1.x

#2018 Backport of Add SNI skip for client node configuration into release/1.1.x
  .changelog/2013.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
Labels: pr/no-changelog, pr/no-backport

#2008 values.yaml - set default connect inject init cpu resource limits to `null` to increase service registration times
  .changelog/2008.txt
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: backport/0.49.x, backport/1.0.x, backport/1.1.x

#2023 values.yaml - set default connect inject init cpu resource limits to null, backport to 1.0.x
  .changelog/2008.txt
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2024 values.yaml - set default connect inject init cpu resource limits to null, backport to 1.1.x
  .changelog/2008.txt
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2027 Remove client.enabled requirement in docs
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#2028 Remove website prefix from generated docs
  hack/helm-reference-gen/main.go
Labels: pr/no-changelog, pr/no-backport

#2029 Update ACLs, add namespace.write permission
  .changelog/2029.txt
  control-plane/subcommand/server-acl-init/rules.go
  control-plane/subcommand/server-acl-init/rules_test.go
Labels: backport/1.1.x

#2034 Prepare Release 1.1.1
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#2035 Prepares release branch for 1.1.2
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport
