Repository hashicorp/consul-k8s, pull requests merged in 2024-03, with the labels that each got.

#3714 docs: update 1.4.0 Helm docs per Docs team feedback
  charts/consul/values.yaml
Labels: pr/no-changelog, backport/1.4.x

#3719 [NET-8367] security: upgrade google.golang.org/protobuf to 1.33.0
  .changelog/3719.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3725 NET-8391: fix cleanup script
  hack/aws-acceptance-test-cleanup/main.go
Labels: pr/no-changelog, pr/no-backport

#3730 NET-8391: fix cleanup script - remove network interface(s)
  hack/aws-acceptance-test-cleanup/main.go
Labels: pr/no-changelog, pr/no-backport

#3731 updates k8s version
  charts/consul/test/terraform/aks/variables.tf
Labels: pr/no-changelog, pr/no-backport

#3736 fix(control-plane): acl tokens deleted while pods in graceful shutdown
  .changelog/3736.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/consul/helm_cluster_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3739 NET-6878: Remove finalizers from CRDs during test resource cleanup
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/deploy.go
  acceptance/tests/peering/peering_gateway_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3741 Upgrade to go 1.21.8
  .changelog/3741.txt
  .go-version
  control-plane/Dockerfile
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3760 Fix typo in values file for sync catalog test
  acceptance/tests/sync/sync_catalog_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3768 upgraded helm v3 to address GHSA-jw44-4f3j-q396
  .release/security-scan.hcl
  scan.hcl
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3737 Net 6821 - Regenerate Terminating Gateway CRD with new field
  charts/consul/templates/crd-terminatinggateways.yaml
  control-plane/api/v1alpha1/terminatinggateway_types.go
  control-plane/api/v1alpha1/terminatinggateway_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, backport/1.4.x

#3764 Add fixes for flaky-cni and failing cloud-nightly tests
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/deploy.go
  acceptance/framework/k8s/kubectl.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3693 Catalog: Use EndpointSlice and propagate Kubernetes Topology information to synced consul service
  .changelog/3693.txt
  charts/consul/templates/sync-catalog-clusterrole.yaml
  charts/consul/test/unit/sync-catalog-clusterrole.bats
  control-plane/catalog/to-consul/resource.go
  control-plane/catalog/to-consul/resource_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3784 Increase timeout for running commands in acceptance test
  acceptance/framework/helpers/helpers.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3785 Bugfix: Don't recreate servicemap for catalog sync
  control-plane/catalog/to-consul/resource.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3774 test: fix TestConnectInject_ProxyLifecycleShutdown
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
Labels: pr/no-changelog, backport/1.3.x, backport/1.4.x

#3718 Removes Legacy API Gateway Stanza that was deprecated in Consul 1.16
  .changelog/3718.txt
  CONTRIBUTING.md
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/api-gateway-controller-clusterrole.yaml
  charts/consul/templates/api-gateway-controller-clusterrolebinding.yaml
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/api-gateway-controller-podsecuritypolicy.yaml
  charts/consul/templates/api-gateway-controller-service.yaml
  charts/consul/templates/api-gateway-controller-serviceaccount.yaml
  charts/consul/templates/api-gateway-gatewayclass.yaml
  charts/consul/templates/api-gateway-gatewayclassconfig.yaml
  charts/consul/templates/api-gateway-podsecuritypolicy.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/api-gateway-controller-clusterrole.bats
  charts/consul/test/unit/api-gateway-controller-clusterrolebinding.bats
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/api-gateway-controller-podsecuritypolicy.bats
  charts/consul/test/unit/api-gateway-controller-service.bats
  charts/consul/test/unit/api-gateway-controller-serviceaccount.bats
  charts/consul/test/unit/api-gateway-gatewayclass.bats
  charts/consul/test/unit/api-gateway-gatewayclassconfig.bats
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/gateway-resources-job.bats
  charts/consul/test/unit/helpers.bats
  charts/consul/values.yaml
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/rules.go
  control-plane/subcommand/server-acl-init/rules_test.go
Labels: theme/api-gateway, pr/no-backport

#3794 remove unit test for previously removed `consul-cni` validation
  control-plane/cni/main_test.go
Labels: theme/testing, pr/no-changelog, backport/1.4.x

#3779 [NET-8412] Fix order of APIGW ACL policy/role creation
  .changelog/3779.txt
  control-plane/api-gateway/cache/consul.go
Labels: theme/api-gateway, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3758 [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors
  .changelog/3758.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#3759 backport 1.4.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors
  .changelog/3758.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#3769 backport 1.3.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors
  .changelog/3758.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#3808 backport 1.2.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors
  .changelog/3758.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#3809 backport 1.1.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors
  .changelog/3758.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: pr/no-backport

#3811 API gateway metrics
  .changelog/3811.txt
  charts/consul/templates/crd-gatewayclassconfigs-v1.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/values.yaml
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/registration.go
  control-plane/api-gateway/binding/registration_test.go
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/common/metrics.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api/v1alpha1/api_gateway_types.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: backport/1.4.x

#3810 Backport release/1.1.x
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/kubectl.go
  acceptance/framework/logger/logger.go
  acceptance/go.mod
  acceptance/go.sum
Labels: pr/no-changelog, pr/no-backport

#3814 Fix release test
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/consul/helm_cluster_test.go
  acceptance/framework/environment/environment.go
  acceptance/framework/k8s/helpers.go
  acceptance/framework/k8s/kubectl.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/connect/permissive_mtls_test.go
  acceptance/tests/peering/peering_connect_namespaces_test.go
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/peering/peering_gateway_test.go
Labels: pr/no-changelog, pr/no-backport

#3829 fix version output for `consul-cni`
  .changelog/3829.txt
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/cni/main.go
Labels: type/bug, theme/tproxy, backport/1.4.x, backport/1.5.x

#3828 [prerelease-1.4.1] Add option to disable CE test
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#3826 [prerelease-1.2.7] Disable CE test
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#3827 [prerelease-1.3.4] Disable CE test
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#3825 [prerelease-1.1.11] Disable CE test
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#3834 [1.2.7] Disable all CE tests
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#3835 [1.3.4] Disable all CE tests
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/weekly-acceptance-0-49-x.yml
  .github/workflows/weekly-acceptance-1-0-x.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#3836 [1.4.1] Add flag to disable CE tests
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
Labels: pr/no-changelog, pr/no-backport

#3837 [NET-8601] Upgrade `vault/api` and `docker/docker` to resolve open CVEs
  .changelog/3837.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3842 Backport of [NET-8601] Upgrade `vault/api` and `docker/docker` to resolve open CVEs into release/1.4.1
  .changelog/3837.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#3845 Backport of [NET-8601] Upgrade `vault/api` and `docker/docker` to resolve open CVEs into release/1.1.11
  .changelog/3837.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#3844 Backport of [NET-8601] Upgrade `vault/api` and `docker/docker` to resolve open CVEs into release/1.2.7
  .changelog/3837.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#3843 Backport of [NET-8601] Upgrade `vault/api` and `docker/docker` to resolve open CVEs into release/1.3.4
  .changelog/3837.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport
