Repository hashicorp/consul-k8s, pull requests merged in 2024-02, with the labels that each got.

#3532 [NET-6417] Fix meshgw tests
  control-plane/controllers/resources/mesh_gateway_controller_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3533 add nightly for rc branch
  .github/workflows/weekly-acceptance-1-4-0-rc1.yml
  .github/workflows/weekly-acceptance-1-4-x.yml
Labels: pr/no-changelog, pr/no-backport

#3507 [NET-7243] Stub APIGateway Controller for v2
  charts/consul/templates/connect-inject-clusterrole.yaml
  control-plane/api/common/common.go
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/controllers/resources/api-gateway-controller.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3530 Net 7376 Status struct on api gateway with required info from kubesig
  control-plane/api/mesh/v2beta1/api_gateway_types.go
Labels: pr/no-changelog, pr/no-backport

#3536 Fix meshgw tests (#3532)
  control-plane/controllers/resources/mesh_gateway_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3535 Mw/prepare main for 1.5 dev
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/build-support/functions/10-util.sh
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3540 Net 7279 consul k8s write failing acceptance test for tcp route
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway_v2/api_gateway_v2_test.go
  acceptance/tests/api-gateway_v2/helpers.go
  acceptance/tests/api-gateway_v2/main_test.go
  acceptance/tests/fixtures/bases/api-gateway-v2/apigateway.yaml
  acceptance/tests/fixtures/bases/api-gateway-v2/certificate.yaml
  acceptance/tests/fixtures/bases/api-gateway-v2/gatewayclass.yaml
  acceptance/tests/fixtures/bases/api-gateway-v2/gatewayclassconfig.yaml
  acceptance/tests/fixtures/bases/api-gateway-v2/kustomization.yaml
  acceptance/tests/fixtures/bases/api-gateway-v2/tcproute.yaml
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3550 Add json tags to api-gateway types
  charts/consul/templates/crd-apigateways.yaml
  charts/consul/templates/crd-trafficpermissions.yaml
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/config/crd/bases/auth.consul.hashicorp.com_trafficpermissions.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml
Labels: pr/no-changelog, pr/no-backport

#3543 reconcile consul-k8s with changes made in Consul
  charts/consul/templates/crd-apigateways.yaml
  charts/consul/templates/crd-grpcroutes.yaml
  charts/consul/templates/crd-httproutes.yaml
  charts/consul/templates/crd-tcproutes.yaml
  control-plane/api/auth/v2beta1/traffic_permissions_types.go
  control-plane/api/auth/v2beta1/traffic_permissions_types_test.go
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/api/mesh/v2beta1/gateway_class_types.go
  control-plane/api/mesh/v2beta1/grpc_route_types.go
  control-plane/api/mesh/v2beta1/grpc_route_types_test.go
  control-plane/api/mesh/v2beta1/http_route_types.go
  control-plane/api/mesh/v2beta1/http_route_types_test.go
  control-plane/api/mesh/v2beta1/mesh_configuration_types.go
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/api/mesh/v2beta1/proxy_configuration_types.go
  control-plane/api/mesh/v2beta1/proxy_configuration_types_test.go
  control-plane/api/mesh/v2beta1/tcp_route_types.go
  control-plane/api/mesh/v2beta1/tcp_route_types_test.go
  control-plane/api/multicluster/v2beta1/exported_services_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_grpcroutes.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_httproutes.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_tcproutes.yaml
  control-plane/connect-inject/common/annotation_processor.go
  control-plane/connect-inject/common/annotation_processor_test.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
  control-plane/consul/dataplane_client_test.go
  control-plane/consul/resource_client_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/mesh-init/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3537 [NET-7656] Add GatewayClassConfig watch for MeshGateway controller
  control-plane/controllers/resources/mesh_gateway_controller.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/service.go
  control-plane/gateways/service_test.go
Labels: theme/mesh-gw, pr/no-changelog, backport/1.4.x

#3548 Ensure signals are passed to commands
  .changelog/3548.txt
  charts/consul/templates/api-gateway-controller-deployment.yaml
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/telemetry-collector-v2-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/test/unit/api-gateway-controller-deployment.bats
  charts/consul/test/unit/client-daemonset.bats
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3519 [NET-7158] CRUD hooks for api gateway v2
  control-plane/controllers/resources/api-gateway-controller.go
  control-plane/controllers/resources/api-gateway-controller_test.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3549 Add NET_BIND_SERVICE to the security context in the deployment of Mesh Gateway (NET-6463)
  .changelog/3549.txt
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/test/unit/mesh-gateway-deployment.bats
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3559 [NET-7657,NET-6934] Define v2 GatewayClass + GatewayClassConfig locally
  charts/consul/templates/crd-gatewayclasses.yaml
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/gateway_class_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclasses.yaml
  control-plane/controllers/resources/gateway_class_config_controller.go
  control-plane/controllers/resources/gateway_class_controller.go
  control-plane/controllers/resources/mesh_gateway_controller.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/gateway-resources/command_test.go
Labels: pr/no-changelog, backport/1.4.x

#3574 [NET-7156] Gateways Controllers Reusability
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/controllers/resources/api-gateway-controller.go
  control-plane/controllers/resources/gateway_controller_setup.go
  control-plane/controllers/resources/gateway_indices.go
  control-plane/controllers/resources/mesh_gateway_controller.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/mesh-gw, theme/api-gateway, pr/no-changelog, pr/no-backport

#3575 [NET-6465] Consider init container resources when determining if existing + desired deployments are equal
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/deployment_test.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3581 [NET-7657] Consume version of proto-public with GatewayClass[Config] removed
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, backport/1.4.x

#3586 prepare for 1.4.0 RC release
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3560 Update multicluster v2beta1 to v2
  acceptance/tests/vault/vault_wan_fed_test.go
  charts/consul/templates/crd-exportedservices.yaml
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/api/mesh/v2beta1/gateway_class_config_types.go
  control-plane/api/mesh/v2beta1/gateway_class_types.go
  control-plane/api/mesh/v2beta1/grpc_route_types.go
  control-plane/api/mesh/v2beta1/http_route_types.go
  control-plane/api/mesh/v2beta1/mesh_configuration_types.go
  control-plane/api/mesh/v2beta1/mesh_gateway_types.go
  control-plane/api/mesh/v2beta1/proxy_configuration_types.go
  control-plane/api/mesh/v2beta1/tcp_route_types.go
  control-plane/api/multicluster/v2/exported_services_types.go
  control-plane/api/multicluster/v2/multicluster_groupversion_info.go
  control-plane/api/multicluster/v2/shared_types.go
  control-plane/api/multicluster/v2/status.go
  control-plane/api/multicluster/v2/zz_generated.deepcopy.go
  control-plane/config/crd/bases/multicluster.consul.hashicorp.com_exportedservices.yaml
  control-plane/controllers/resources/exported_services_controller.go
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-changelog, backport/1.4.x

#3588 release: Update 10-util.sh to adjust formatting
  control-plane/build-support/functions/10-util.sh
Labels: pr/no-changelog, backport/1.4.x

#3591 use go 1.21.7
  .changelog/3591.txt
  .go-version
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3596 add make target script
  Makefile
  control-plane/build-support/scripts/mod_tidy.sh
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3590 v2tenancy: namespace mirroring acceptance tests
  acceptance/framework/connhelper/connect_helper.go
  acceptance/framework/resource/helpers.go
  acceptance/tests/mesh_v2/mesh_inject_test.go
  acceptance/tests/tenancy_v2/namespace_test.go
Labels: pr/no-changelog, pr/no-backport

#3603 add linting back
  .github/workflows/lint.yaml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3604 added comment about cloud test package (#3471)
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: pr/no-changelog, pr/no-backport

#3611 fixed copyright headers
  control-plane/api-gateway/gatekeeper/deployment_test.go
  control-plane/build-support/scripts/mod_tidy.sh
Labels: pr/no-changelog, pr/no-backport

#3613 fixed copyright headers
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  acceptance/tests/fixtures/bases/sameness/override-ns/service-defaults.yaml
  acceptance/tests/fixtures/bases/sameness/peering/mesh/mesh.yaml
  cli/cmd/proxy/stats/command.go
  cli/cmd/proxy/stats/command_test.go
  control-plane/api-gateway/gatekeeper/deployment_test.go
  control-plane/build-support/scripts/mod_tidy.sh
  control-plane/consul/dynamic.go
  control-plane/consul/dynamic_test.go
  control-plane/controllers/finalizer_patch.go
  control-plane/controllers/finalizer_patch_test.go
  control-plane/subcommand/server-acl-init/anonymous_token_test.go
Labels: pr/no-changelog, pr/no-backport

#3612 Mw/1 3 x add copyright headers
  acceptance/tests/cloud/fakeserver_client.go
  acceptance/tests/cloud/metrics_validation.go
  cli/cmd/proxy/stats/command.go
  cli/cmd/proxy/stats/command_test.go
  control-plane/api-gateway/gatekeeper/deployment_test.go
  control-plane/build-support/scripts/mod_tidy.sh
  control-plane/config-entries/controllers/finalizer_patch.go
  control-plane/config-entries/controllers/finalizer_patch_test.go
  control-plane/consul/dynamic.go
  control-plane/consul/dynamic_test.go
Labels: pr/no-changelog, pr/no-backport

#3407 Datadog Integration
  .changelog/3407.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/datadog-agent-role.yaml
  charts/consul/templates/datadog-agent-rolebinding.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
  control-plane/subcommand/common/common.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/rules.go
Labels: type/enhancement, theme/telemetry, type/docs, backport/1.1.x, backport/1.2.x, backport/1.3.x

#3564 Net 7238 - consul k8s modify gateway resources job to create apigw gatewayclass and gatewayclassconfig
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3620 Datadog Integration (#3407)
  .changelog/3407.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/datadog-agent-role.yaml
  charts/consul/templates/datadog-agent-rolebinding.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
  control-plane/subcommand/common/common.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/rules.go
Labels: pr/no-backport

#3619 Datadog Integration (#3407)
  .changelog/3407.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/datadog-agent-role.yaml
  charts/consul/templates/datadog-agent-rolebinding.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
  control-plane/subcommand/common/common.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/rules.go
Labels: pr/no-backport

#3626 Backport of Datadog Integration into release/1.2.x (cherry-pick)
  .changelog/3407.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/datadog-agent-role.yaml
  charts/consul/templates/datadog-agent-rolebinding.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/server-acl-init-job.bats
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  charts/consul/values.yaml
  control-plane/subcommand/common/common.go
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/command_test.go
  control-plane/subcommand/server-acl-init/rules.go
Labels: pr/no-backport

#3633 Prerelease 1.3.3
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3634 Prepare release 1.2.6
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3632 Prepare release 1.1.10
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3636 [NET-5932] chore: remove comment from closed ticket
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
Labels: pr/no-changelog, backport/1.4.x

#3625 [NET-2420] security: Upgrade helm containerd and several other dependencies
  .changelog/3625.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3642 Set release/1.1.x to 1.1.11 dev mode
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3643 Set release/1.2.x to 1.2.7 dev mode
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3428 build: Create arm64 packages as well
  .changelog/3428.txt
  .github/workflows/build.yml
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3657 [NET-8174] security: add scan triage for CVE-2024-25620 (helm/v3)
  .release/security-scan.hcl
  scan.hcl
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3662 Update main changelog for 1.1.10, 1.2.6 and 1.3.3
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#3580 [NET-7450] setup crud hooks for APIGateway v2
  charts/consul/templates/crd-apigateways.yaml
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml
  control-plane/controllers/resources/api-gateway-controller.go
  control-plane/controllers/resources/api-gateway-controller_test.go
  control-plane/controllers/resources/gateway_controller_crud.go
  control-plane/controllers/resources/mesh_gateway_controller.go
  control-plane/gateways/builder.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/metadata_test.go
  control-plane/gateways/serviceaccount_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3656 values.yaml - tlsServerName docs
  charts/consul/values.yaml
Labels: backport/1.0.x, backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3669 [NET-6741] make: Add target for updating dependencies across all modules
  Makefile
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3668 build.yml: Add ECR images back
  .changelog/3668.txt
  .github/workflows/build.yml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3682 1.2.x: Publish ECR images
  .changelog/3668.txt
  .github/workflows/build.yml
Labels: pr/no-backport

#3681 build.yml: typo on tags
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.4.x

#3683 1.1.x: Publish ECR images
  .changelog/3668.txt
  .github/workflows/build.yml
Labels: pr/no-backport

#3680 1.3.x: publish ECR images
  .changelog/3668.txt
  .github/workflows/build.yml
Labels: pr/no-backport

#3688 [NET-8174] security: add scan triage for CVE-2024-26147 (helm/v3)
  .release/security-scan.hcl
  scan.hcl
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3694 Sync `release/1.4.x` and `release/1.4.0` for 1.4.0 GA release
  .changelog/3428.txt
  .changelog/3625.txt
  .changelog/3668.txt
  .changelog/3675.txt
  .github/workflows/build.yml
  .github/workflows/lint.yaml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/security-scan.yml
  .release/security-scan.hcl
  Makefile
  README.md
  acceptance/ci-inputs/kind-inputs.yaml
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/README.md
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
  scan.hcl
Labels: pr/no-changelog, pr/no-backport

#3697 Prepare 1.4.0 release
  .changelog/3625.txt
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#3695 chore: upgrade Consul dependencies to latest
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway_v2/api_gateway_v2_test.go
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  hack/aws-acceptance-test-cleanup/go.mod
  hack/aws-acceptance-test-cleanup/go.sum
  hack/camel-crds/go.mod
  hack/camel-crds/go.sum
  hack/helm-reference-gen/go.mod
  hack/helm-reference-gen/go.sum
Labels: pr/no-changelog, backport/1.4.x

#3699 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#3700 release: add \n to end of NOTE for releases
  control-plane/build-support/functions/10-util.sh
Labels: pr/no-changelog, pr/no-backport

#3701 chore: upgrade `consul/api` to latest (1.4.0)
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3702 chore: upgrade `consul/api` to latest
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3704 [NET-8174] security: add triage alias for GO-2024-2554 (1.4.0)
  .release/security-scan.hcl
  scan.hcl
Labels: pr/no-changelog, pr/no-backport

#3705 [NET-8174] security: add triage alias for GO-2024-2554
  .release/security-scan.hcl
  scan.hcl
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3710 docs: update `CHANGELOG` for K8s 1.4.0 release
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.4.x
