Repository hashicorp/consul-k8s, pull requests merged in 2024-01, with the labels that each got.

#3369 v2tenancy: support partition creation when adminPartitions enabled
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  acceptance/framework/config/config.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/k8s/helpers.go
  acceptance/framework/portforward/port_forward.go
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/partitions/main_test.go
  acceptance/tests/tenancy_v2/main_test.go
  acceptance/tests/tenancy_v2/partition_test.go
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/helpers.bats
  charts/consul/test/unit/partition-init-job.bats
  charts/consul/values.yaml
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/partition-init/command.go
  control-plane/subcommand/partition-init/command_ent_test.go
Labels: pr/no-changelog, pr/no-backport

#3427 delete gateway in cleanup-gateway-resouces
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/gateways/config.go
  control-plane/subcommand/gateway-cleanup/command.go
  control-plane/subcommand/gateway-resources/command.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3420 Support WAN Address Annotations
  charts/consul/templates/gateway-resources-configmap.yaml
  charts/consul/test/unit/gateway-resources-configmap.bats
  charts/consul/values.yaml
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_test.go
Labels: pr/no-changelog, pr/no-backport

#3429 [NET-6829] Add tls support for mesh gateways
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhookv2/container_init.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_init_container.go
  control-plane/gateways/deployment_test.go
  control-plane/subcommand/flags/consul.go
  control-plane/subcommand/flags/consul_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3439 disable TestConnectInject_LocalRateLimiting for cloud provider tests
  acceptance/tests/connect/local_rate_limit_test.go
Labels: pr/no-changelog, backport/1.3.x

#3440 [NET-6702] HTTPRoute not being deleted from consul bug
  .changelog/3440.txt
  control-plane/api-gateway/cache/consul.go
Labels: type/bug, backport/1.2.x, backport/1.3.x

#3442 [NET-7009] security: update x/crypto to 0.17.0
  .changelog/3442.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3430 Pass gateway init resources from config to the container
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_init_container.go
  control-plane/gateways/deployment_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3375 Add acceptance test cleanup
  acceptance/framework/consul/helm_cluster.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3322 [NET-6581] perf: Fetch services once rather than per-node on deregister
  .changelog/3322.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
  control-plane/namespaces/namespaces.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#3434 Net 6822 - consul consul k8s add listeners to mesh gateway consume for service
  charts/consul/templates/crd-meshgateways.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
  control-plane/gateways/service.go
  control-plane/gateways/service_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3438 Fix to support non-enterprise HCP observability testing
  acceptance/tests/cloud/observability_test.go
Labels: pr/no-changelog, pr/no-backport

#3471 added comment about cloud test package
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3470 Net 7189 Consul k8s add protocol to listeners on the mesh gateway
  charts/consul/templates/crd-meshgateways.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
  control-plane/gateways/service.go
  control-plane/gateways/service_test.go
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3475 Manual backport of cleanup acceptance tests
  acceptance/framework/consul/helm_cluster.go
Labels: pr/no-changelog, pr/no-backport

#3000 Set leave_on_terminate=true for servers and hardcode maxUnavailable=1
  .changelog/2962.txt
  .changelog/3000.txt
  acceptance/ci-inputs/aks_acceptance_test_packages.yaml
  acceptance/ci-inputs/eks_acceptance_test_packages.yaml
  acceptance/ci-inputs/gke_acceptance_test_packages.yaml
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
  acceptance/tests/example/main_test.go
  acceptance/tests/server/main_test.go
  acceptance/tests/server/server_test.go
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/server-config-configmap.yaml
  charts/consul/templates/server-disruptionbudget.yaml
  charts/consul/test/unit/server-config-configmap.bats
  charts/consul/test/unit/server-disruptionbudget.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#3435 v2tenancy: v2 namespace controller + tests
  Makefile
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  control-plane/config-entries/controllersv2/consul_resource_controller_test.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
  control-plane/helper/test/test_util.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/inject-connect/command_test.go
  control-plane/subcommand/inject-connect/v2controllers.go
  control-plane/subcommand/mesh-init/command_ent_test.go
  control-plane/subcommand/mesh-init/command_test.go
  control-plane/subcommand/partition-init/command_ent_test.go
  control-plane/subcommand/server-acl-init/command_ent_test.go
  control-plane/tenancy/namespace/namespace.go
  control-plane/tenancy/namespace/namespace_controller.go
  control-plane/tenancy/namespace/namespace_controller_ent_test.go
  control-plane/tenancy/namespace/namespace_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3437 Net 6289 improve consul api gateway annotations
  .changelog/3437.txt
  cli/cmd/proxy/list/command.go
  cli/cmd/proxy/list/command_test.go
  control-plane/api-gateway/common/labels.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
Labels: backport/1.3.x

#3480 Update the version of client-go to v0.26.12
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3482 Update client-go to v0.26.12
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#3477 Mesh Gateway Deployment Configuration
  charts/consul/test/unit/gateway-resources-configmap.bats
  control-plane/gateways/builder.go
  control-plane/gateways/constants.go
  control-plane/gateways/deployment.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_init_container.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/gateway_config.go
  control-plane/gateways/metadata.go
  control-plane/gateways/metadata_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3489 Backport - Upgrade go to 1.21.6 and use single source of .go-version to release/1.2.x
  .changelog/3478.txt
  .go-version
  Makefile
  control-plane/Dockerfile
Labels: pr/no-backport

#3488 Backport - Upgrade go to 1.21.6 and use single source of .go-version to release/1.1.x
  .changelog/3478.txt
  .go-version
  Makefile
  control-plane/Dockerfile
Labels: pr/no-backport

#3465 NET-7179: Update MeshGateway to use new proto with workload selector
  charts/consul/templates/crd-meshgateways.yaml
  charts/consul/templates/gateway-resources-configmap.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
  control-plane/gateways/deployment_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/gateway-resources/command_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3501 Use golang -alpine image when building go-discover
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3500 Backport of CRT build failing for Go into release/1.3.x
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3497 Backport of CRT build failing for Go into release/1.2.x
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3496 Backport of CRT build failing for Go into release/1.1.x
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3502 Add CaseInsenstive field to ServiceRouter.
  .changelog/3502.txt
  charts/consul/templates/crd-servicerouters.yaml
  control-plane/api/v1alpha1/servicerouter_types.go
  control-plane/api/v1alpha1/servicerouter_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.3.x

#3498 Set ReadOnlyRootFilesystem and AllowPrivilegeEscalation to false
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhookv2/container_init.go
  control-plane/connect-inject/webhookv2/container_init_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3511 Set ReadOnlyRootFilesystem and AllowPrivilegeEscalation to false (#3498)
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, pr/no-backport

#3512 Set ReadOnlyRootFilesystem and AllowPrivilegeEscalation to false (#3498)
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, pr/no-backport

#3513 Set ReadOnlyRootFilesystem and AllowPrivilegeEscalation to false (#3498)
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, pr/no-backport

#3514 Set ReadOnlyRootFilesystem and AllowPrivilegeEscalation to false (#3498)
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, pr/no-backport

#3516 Prerelease 1.3.2
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhookv2/container_init.go
  control-plane/connect-inject/webhookv2/container_init_test.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3517 Prerelease 1.2.5
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3518 Prerelease 1.1.9
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3521 Update tests of traffic permission deny action to enterprise only
  control-plane/controllers/resources/consul_resource_controller_ent_test.go
  control-plane/controllers/resources/consul_resource_controller_test.go
Labels: pr/no-changelog, pr/no-backport

#3515 Changelog for #3498
  .changelog/3498.txt
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x

#3526 [NET-7492, NET-7495] Support -server-watch-disabled, use -proxy-* args instead of -service-*
  control-plane/gateways/constants.go
  control-plane/gateways/deployment_dataplane_container.go
  control-plane/gateways/deployment_test.go
  control-plane/gateways/gateway_config.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#3506 NET-7153 Generate API Gateway CRDs
  charts/consul/templates/crd-apigateways.yaml
  control-plane/api/auth/v2beta1/traffic_permissions_types_test.go
  control-plane/api/mesh/v2beta1/api_gateway_types.go
  control-plane/api/mesh/v2beta1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/api-gateway, pr/no-changelog, pr/no-backport

#3528 [NET-7534] v2: Make port names in consul-k8s compatible with NET-5586
  control-plane/connect-inject/common/common.go
  control-plane/connect-inject/common/common_test.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
  control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
  control-plane/connect-inject/controllers/pod/pod_controller.go
  control-plane/connect-inject/controllers/pod/pod_controller_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
Labels: pr/no-changelog, pr/no-backport
