Repository hashicorp/consul-k8s, pull requests merged in 2024-10, with the labels that each got.

#4377 [NET-11222] rollback command
  .changelog/4255.txt
  control-plane/subcommand/sync-catalog/command.go
  control-plane/subcommand/sync-catalog/command_test.go
Labels: pr/no-changelog, pr/no-backport

#4383 bump kubernetes version for AKS
  charts/consul/test/terraform/aks/variables.tf
Labels: pr/no-changelog, pr/no-backport

#4382 NO-JIRA: cleanup iamRoles as part of nightly test cleanup
  hack/aws-acceptance-test-cleanup/main.go
Labels: pr/no-changelog, pr/no-backport

#3874 Sync Catalog: Add k8s endpoint health state to consul health check
  .changelog/3874.txt
  control-plane/catalog/to-consul/resource.go
  control-plane/catalog/to-consul/resource_test.go
Labels: pr/no-backport

#4389 Prepare branch for future patch release
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4390 Prepare 1.6.0 release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4392 Update changelog to include 1.6.0
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.6.x

#4391 Prepare branch for future minor release
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4385 [NET-11043] crd: support request normalization and header match options to prevent L7 intentions bypass
  .changelog/4385.txt
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  cli/go.mod
  cli/go.sum
  control-plane/api/v1alpha1/mesh_types.go
  control-plane/api/v1alpha1/mesh_types_test.go
  control-plane/api/v1alpha1/serviceintentions_types.go
  control-plane/api/v1alpha1/serviceintentions_types_test.go
  control-plane/catalog/metrics/metrics.go
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/go.mod
  control-plane/go.sum
  control-plane/helper/test/test_util.go
  control-plane/subcommand/common/metrics_util.go
Labels: backport/1.1.x, backport/1.4.x, backport/1.5.x, backport/1.6.x

#4406 [NET-11297] added bats testing
  charts/consul/test/unit/sync-catalog-cleanup-on-uninstall-job.bats
  charts/consul/test/unit/sync-catalog-cleanup-on-upgrade-job.bats
  charts/consul/test/unit/sync-catalog-cleanup-serviceaccount.bats
Labels: pr/no-changelog, pr/no-backport
