Repository hashicorp/consul-k8s, pull requests merged in 2024-09, with the labels that each got.

#4300 NET-10763 - Allow DNS Proxy to configured with an ACL token when manageSystemACLs is false
  .changelog/4300.txt
  .gitignore
  acceptance/tests/consul-dns/consul_dns_test.go
  charts/consul/templates/dns-proxy-deployment.yaml
  charts/consul/test/unit/dns-proxy-deployment.bats
  charts/consul/values.yaml
Labels: pr/no-backport

#4307 NET-10871 Remove unnecessary resource permissions in connect-inject ClusterRole
  .changelog/4307.txt
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/test/unit/connect-inject-clusterrole.bats
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#4306 changelog 1.5.x
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4302 changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4303 changelog 1.3.x
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4304 changelog 1.1.x
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4305 changelog 1.4.x
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4313 security: Upgrade Go to 1.22.7
  .changelog/4313.txt
  .go-version
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4324 ci: update the security-scanner gha token
  .github/workflows/security-scan.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4335 Init 1.6 weekly tests
  .github/workflows/weekly-acceptance-1-6-x.yml
Labels: pr/no-changelog, backport/1.6

#4333 [NET-10961] Ignore gke managed namespaces by default
  .changelog/4333.txt
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4346 add exception to pr.yaml
  .github/workflows/pr.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.3.x, backport/1.4.x, backport/1.5.x, backport/1.6.x

#4345 [NET-11106] Make bats testing more reproducible
  Makefile
  charts/consul/test/docker/Test.dockerfile
Labels: pr/no-changelog, pr/no-backport

#4357 Backport prepare release rc1
  .changelog/4333.txt
  .github/scripts/check_skip_ci.sh
  .github/workflows/pr.yml
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  charts/consul/test/docker/Test.dockerfile
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4315 Fixes tolerations not working
  .changelog/4315.txt
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/test/unit/gateway-resources-job.bats
  control-plane/subcommand/gateway-resources/command_test.go
Labels: backport/1.1.x, backport/1.4.x, backport/1.5.x, backport/1.6.x

#4356 Prepare release 1.6.0 rc1
  .changelog/4333.txt
  .github/scripts/check_skip_ci.sh
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  charts/consul/test/docker/Test.dockerfile
  charts/consul/values.yaml
Labels: pr/no-changelog, backport/1.6.x

#4363 [NET-11150] ci: fix conditional skip and add safeguard
  .github/scripts/check_skip_ci.sh
  .github/workflows/reusable-conditional-skip.yml
  .github/workflows/security-scan.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.3.x, backport/1.4.x, backport/1.5.x, backport/1.6.x

#4370 Init 1.6.0 release branch
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4316 [NET-10985] Fix bug where imagePullSecrets were not set up for Gateways
  .changelog/4316.txt
  charts/consul/templates/connect-inject-configmap.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/api-gateway/gatekeeper/rolebinding.go
  control-plane/api-gateway/gatekeeper/serviceaccount.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x, backport/1.6.x
