Repository hashicorp/consul-k8s, pull requests merged in 2024-06, with the labels that each got.

#3959 [NET-6464] lock down init container
  .changelog/3959.txt
  control-plane/api-gateway/gatekeeper/init.go
Labels: backport/1.4.x, backport/1.5.x

#4060 [NET-9420] clean up acl role policy for apigw
  .changelog/4060.txt
  acceptance/framework/environment/environment.go
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4063 [NET-8091] Replace InlineCertificate kind in test w/ FileSystemCertificate kind
  control-plane/api-gateway/common/diff_test.go
Labels: pr/no-changelog, backport/1.5.x

#4053 [NET-6705] Remove Secrets resource from partition-init Role
  .changelog/4053.txt
  charts/consul/templates/partition-init-role.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4081 ci: update security-scanner token
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-backport

#4059 fix: deregistration should not do graceful shutdown if there is a new pod
  .changelog/4059.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#4085 update go version to 1.22.4
  .changelog/4085.txt
  .go-version
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4091 [NET-9839] fix: add shared version submodule
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  acceptance/go.mod
  acceptance/go.sum
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
  version/fips_build.go
  version/go.mod
  version/non_fips_build.go
  version/version.go
Labels: pr/no-backport

#4094 Backport of [NET-9839] fix: add shared version submodule (#4091) into release/1.5.x
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
  version/fips_build.go
  version/go.mod
  version/non_fips_build.go
  version/version.go
Labels: pr/no-backport

#4095 Backport of [NET-9839] fix: add shared version submodule (#4091) into release/1.5.0
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
  version/fips_build.go
  version/go.mod
  version/non_fips_build.go
  version/version.go
Labels: pr/no-backport

#4096 Backport of [NET-9839] fix: add shared version submodule (#4091) into release/1.4.x
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
  version/fips_build.go
  version/go.mod
  version/non_fips_build.go
  version/version.go
Labels: pr/no-backport

#4097 Backport of [NET-9839] fix: add shared version submodule (#4091) into release/1.3.x
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/common/secrets.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/connect-inject/webhookv2/mesh_webhook.go
  control-plane/connect-inject/webhookv2/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/subcommand/connect-init/command.go
  control-plane/subcommand/mesh-init/command.go
  control-plane/version/fips_build.go
  control-plane/version/non_fips_build.go
  control-plane/version/version.go
  version/fips_build.go
  version/go.mod
  version/non_fips_build.go
  version/version.go
Labels: pr/no-backport

#4098 Backport of [NET-9839] fix: add shared version submodule (#4091) into release/1.1.x
  .changelog/4091.txt
  .github/workflows/build.yml
  Makefile
  cli/commands.go
  cli/go.mod
  cli/main.go
  control-plane/build-support/functions/10-util.sh
  control-plane/cni/go.mod
  control-plane/cni/main.go
  control-plane/commands.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/connect-inject/webhook/mesh_webhook_test.go
  control-plane/consul/consul.go
  control-plane/consul/consul_test.go
  control-plane/go.mod
  control-plane/helper/go-discover/discover.go
  control-plane/main.go
  control-plane/version/version.go
  version/go.mod
  version/version.go
Labels: pr/no-backport

#4092 docs: remove mulitport docs, add v1dns flag
  charts/consul/values.yaml
Labels: pr/no-changelog, backport/1.5.x

#4102 Backport of update go version to 1.22.4 into release/1.5.0
  .changelog/4085.txt
  .go-version
Labels: pr/no-backport

#4100 [NET-9606] Use namespace-local Secret for mounting TLS certificates into api-gateway Pod
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/ownership.go
  control-plane/api-gateway/gatekeeper/secret.go
  control-plane/api-gateway/gatekeeper/volumes.go
Labels: pr/no-changelog, backport/1.5.x

#4104 Backport: [NET-9606] Use namespace-local Secret for mounting TLS certificates into api-gateway Pod
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/ownership.go
  control-plane/api-gateway/gatekeeper/secret.go
  control-plane/api-gateway/gatekeeper/volumes.go
Labels: pr/no-changelog, pr/no-backport

#4103 Backport of [NET-9606] Use namespace-local Secret for mounting TLS certificates into api-gateway Pod into release/1.5.x
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/gatekeeper.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/ownership.go
  control-plane/api-gateway/gatekeeper/secret.go
  control-plane/api-gateway/gatekeeper/volumes.go
Labels: pr/no-changelog, pr/no-backport

#4112 build: stage 1.5.0 release
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4105 NET-9994: Cleanup volumes created as part of acceptance tests
  hack/aws-acceptance-test-cleanup/main.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4107 [NET-9606] Add test case covering cross-namespace TLS certificate Secret ref
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
Labels: pr/no-changelog, backport/1.5.x

#4067 [NET-9500] Cleanup orphaned inline-certs and acl role/policy
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4125 [NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#4124 [NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#4128 [NET-9446] chore: update CHANGELOG and tests for 1.5.0
  .github/workflows/weekly-acceptance-1-2-x.yml
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.5.x

#4129 [NET-9446] chore: disable CE tests for Consul 1.18
  .github/workflows/merge.yml
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#4127 ci: add conditional skip for docs changes
  .github/scripts/check_skip_ci.sh
  .github/workflows/build.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-conditional-skip.yml
  .github/workflows/security-scan.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.4.x, backport/1.5.x

#4131 [NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)
  acceptance/go.mod
  acceptance/go.sum
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#4132 [NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)
  acceptance/go.mod
  acceptance/go.sum
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#4133 [NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)
  acceptance/go.mod
  acceptance/go.sum
  control-plane/api-gateway/binding/cleanup.go
  control-plane/api-gateway/binding/cleanup_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-changelog, pr/no-backport

#4144 ci: pass required consul-k8s-workflows checks on CI skip
  .github/workflows/pr.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.3.x, backport/1.4.x, backport/1.5.x

#3989 Fix ArgoCD hooks annotation location
  .changelog/3989.txt
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/test/unit/server-acl-init-job.bats
Labels: pr/no-backport
