Repository hashicorp/consul-k8s, pull requests merged in 2024-05, with the labels that each got.

#3960 chore: remove workstream from JIRA sync
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog, pr/no-backport

#3958 NET-9154: Update Kubernetes version
  charts/consul/test/terraform/aks/variables.tf
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3965 chore: fix JIRA workflow
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
Labels: pr/no-changelog, pr/no-backport

#3956 Fix a panic in connect-inject when the provided upstreams list is malformed
  .changelog/3956.txt
  control-plane/connect-inject/webhook/container_env.go
  control-plane/connect-inject/webhook/container_env_test.go
Labels: backport/1.3.x, backport/1.4.x

#3943 [NET-9152] CRD for service registeration
  .changelog/3943.txt
  charts/consul/templates/connect-inject-clusterrole.yaml
  charts/consul/templates/crd-registrations.yaml
  control-plane/api/common/common.go
  control-plane/api/v1alpha1/registration_types.go
  control-plane/api/v1alpha1/registration_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/config/crd/bases/consul.hashicorp.com_registrations.yaml
  control-plane/controllers/configentries/registrations_controller.go
  control-plane/controllers/configentries/registrations_controller_test.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-backport

#2909 Add ReadOnlyRootFilesystem to Security Context
  .changelog/2909.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: pr/no-backport

#3974 activate tproxy mode even when a cluster IP is not assigned to pod
  .changelog/3974.txt
  control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
  control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Labels: backport/1.3.x, backport/1.4.x

#3980 security: Upgrade Go to 1.21.10
  .changelog/3980.txt
  .go-version
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3978 NET-9178-Consul-api-gateway-not-starting-after-restart
  .changelog/3978.txt
  control-plane/api-gateway/cache/consul.go
Labels: backport/1.4.x

#3990 [NET-9201] Validating webhook for registrations
  CONTRIBUTING.md
  charts/consul/templates/connect-inject-validatingwebhookconfiguration.yaml
  charts/consul/templates/crd-registrations.yaml
  control-plane/api/v1alpha1/registration_types.go
  control-plane/api/v1alpha1/registration_webhook.go
  control-plane/api/v1alpha1/registration_webhook_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_registrations.yaml
  control-plane/config/webhook/manifests.yaml
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#3979 Updating GitHub action versions to the latest TSCCR approved version
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
  .github/workflows/lint.yaml
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-api-gateway-conformance.yml
  .github/workflows/nightly-cleanup.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/security-scan.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
  .github/workflows/weekly-acceptance-1-2-x.yml
  .github/workflows/weekly-acceptance-1-3-x.yml
  .github/workflows/weekly-acceptance-1-4-0-rc1.yml
  .github/workflows/weekly-acceptance-1-4-x.yml
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3992 test: fix PeeringGateway acceptance
  acceptance/tests/peering/peering_gateway_test.go
Labels: pr/no-changelog, pr/no-backport

#3998 Backport of Updating GitHub action versions to the latest TSCCR approved version into release/1.4.x
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/jira-issues.yaml
  .github/workflows/jira-pr.yaml
  .github/workflows/lint.yaml
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/nightly-api-gateway-conformance.yml
  .github/workflows/nightly-cleanup.yml
  .github/workflows/pr.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/security-scan.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
  .github/workflows/weekly-acceptance-1-2-x.yml
  .github/workflows/weekly-acceptance-1-3-x.yml
Labels: pr/no-changelog, pr/no-backport

#3991 Adds ability to set the imagePullPolicy for all Consul images (consul…
  .changelog/3991.txt
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/cni-daemonset.yaml
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/templates/create-federation-secret-job.yaml
  charts/consul/templates/enterprise-license-job.yaml
  charts/consul/templates/gateway-cleanup-job.yaml
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/gossip-encryption-autogenerate-job.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/partition-init-job.yaml
  charts/consul/templates/server-acl-init-cleanup-job.yaml
  charts/consul/templates/server-acl-init-job.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/templates/tests/test-runner.yaml
  charts/consul/templates/tls-init-cleanup-job.yaml
  charts/consul/templates/tls-init-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/test/unit/helpers.bats
  charts/consul/values.yaml
  control-plane/api-gateway/common/helm_config.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/mesh_webhook.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/inject-connect/command_test.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: theme/api-gateway, pr/no-backport

#3993 [NET-9155] Cache resources for Registrations
  control-plane/api/v1alpha1/registration_types.go
  control-plane/catalog/registration/cache.go
  control-plane/catalog/registration/registrations_controller.go
  control-plane/catalog/registration/registrations_controller_test.go
  control-plane/catalog/registration/result.go
  control-plane/controllers/configentries/registrations_controller.go
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: pr/no-changelog, pr/no-backport

#4000 [NET-9376] Fix issue with multiple APIGW
  .changelog/4000.txt
  control-plane/api-gateway/cache/consul.go
Labels: pr/no-backport

#4001 [NET-9376] Fix Issue with multiple APIGW's roles/policy
  .changelog/4001.txt
  control-plane/api-gateway/cache/consul.go
Labels: pr/no-backport

#4002 [NET-9376] Fix Issue with multiple APIGW's roles/policy
  .changelog/4002.txt
  control-plane/api-gateway/cache/consul.go
Labels: pr/no-backport

#4003 update role policy for api-gateway when creating new gateway
  .changelog/4003.txt
  control-plane/api-gateway/cache/consul.go
Labels: pr/no-backport

#3999 FLAKEY_TEST: Add retry to outbound request for ProxyLifecycleShutdown…
  acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#4008 [NET-9097] Update service resolver webhook registration missed in previous backport
  control-plane/subcommand/inject-connect/command.go
Labels: pr/no-changelog, pr/no-backport

#4010 Prepare release for 1.4.2
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4011 Prepare release for 1.3.5
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4013 Prepare 1.1.12
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4015 Prepare 1.3.5
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4014 Prepare release for 1.2.8
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4016 security: update alpine base image to 3.19
  .changelog/4016.txt
  control-plane/Dockerfile
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3994 upgrade go to 1.22.3
  .changelog/3994.txt
  .go-version
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#4021 security: temporary triage for alpine base image
  .release/security-scan.hcl
Labels: pr/no-changelog, pr/no-backport

#4027 Post release 1.4.2
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4028 Post release 1.3.5
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4029 Post release 1.2.8
  CHANGELOG.md
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4033 Adds post release changelog for 1.4.2, 1.3.5, 1.2.8, and 1.1.12
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4009 run generators ctrl-manifests and ctrl-generate
  charts/consul/templates/crd-gatewayclassconfigs-v1.yaml
  charts/consul/templates/crd-gatewayclassconfigs.yaml
  control-plane/api-gateway/gatekeeper/volumes.go
  control-plane/catalog/registration/cache.go
  control-plane/catalog/registration/result.go
  control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
  control-plane/config/webhook/manifests.yaml
Labels: pr/no-changelog, pr/no-backport

#4035 Updates Helm chart comments with Consul Dedicated Rebrand changes
  charts/consul/values.yaml
Labels: pr/no-changelog, backport/1.4.x

#4022 chore: fix previous changelog for alpine upgrade
  .changelog/4016.txt
Labels: pr/no-changelog, pr/no-backport

#4034 [NET-4414] Revert: Remove anyuid SCC requirement for OpenShift
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#4037 [NET-4414] Revert: Remove anyuid SCC requirement for OpenShift
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4038 [NET-4414] Revert: Remove anyuid SCC requirement for OpenShift
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4039 [NET-4414] Revert: Remove anyuid SCC requirement for OpenShift
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4041 prepare release 1.4.3
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4043 prepare release 1.2.9
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4040 build.yml: package consul-cni
  .changelog/4040.txt
  .github/workflows/build.yml
  .release/linux/postinst
  .release/linux/postrm
Labels: backport/1.4.x

#4047 Update Changelog in main
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4054 build: prepare for 1.6.0 dev
  .github/workflows/weekly-acceptance-1-5-x.yml
  Makefile
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4056 [NET-9445] build: prepare for 1.5.1 dev
  charts/consul/Chart.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#4055 [NET-9445] chore: update consul dependencies
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, backport/1.5.x

#4058 Backport of [NET-9445] chore: update consul dependencies into release/1.5.0
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4064 [NET-9605] fix issue where gateway pods with TLS block thrash
  control-plane/api-gateway/gatekeeper/volumes.go
Labels: pr/no-changelog, backport/1.5.x
