Repository hashicorp/consul-k8s, pull requests merged in 2024-04, with the labels that each got.

#3813 Remove anyuid SCC requirement for OpenShift
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3851 Backport: Remove anyuid SCC requirement for OpenShift (#3813)
  .changelog/3813.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#3852 Cleanup formatting to follow consul-k8s standard
  acceptance/framework/consul/helm_cluster.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/container_init.go
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3859 [1.2.7] Remove Duplicate UBI Tags (#3265)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3863 Re-add get-go-version
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3861 Backport: Cleanup formatting to follow consul-k8s standard (#3852)
  acceptance/framework/consul/helm_cluster.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/container_init.go
Labels: pr/no-changelog, pr/no-backport

#3635 Datadog Unix Socket Path Custom Path fix
  .changelog/3635.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/test/unit/server-statefulset.bats
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3860 [1.3.4] Remove Duplicate UBI Tags (#3265)
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3871 [1.2.x] Post-release steps
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3870 [1.1.x] Post-release steps
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3880 [1.4.x] Post-release steps
  .github/workflows/merge.yml
  .github/workflows/nightly-acceptance.yml
  .github/workflows/pr.yml
  .github/workflows/weekly-acceptance-1-1-x.yml
  CHANGELOG.md
  charts/consul/Chart.yaml
  cli/go.mod
  cli/go.sum
  cli/version/version.go
  control-plane/version/version.go
Labels: pr/no-changelog, pr/no-backport

#3881 readd dev image tags for fips ubi
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3882 Manual backport of Remove Duplicate UBI Tags to release/1.1.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-backport

#3846 [net-7710] don't overwrite prometheus path annotation if it's already been specified
  .changelog/3846.txt
  charts/consul/templates/client-daemonset.yaml
  charts/consul/templates/ingress-gateways-deployment.yaml
  charts/consul/templates/mesh-gateway-deployment.yaml
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/terminating-gateways-deployment.yaml
  charts/consul/test/unit/client-daemonset.bats
  charts/consul/test/unit/ingress-gateways-deployment.bats
  charts/consul/test/unit/mesh-gateway-deployment.bats
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/terminating-gateways-deployment.bats
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3878 feat: Add startup-grace-period-seconds and graceful-startup-path
  .changelog/3878.txt
  charts/consul/templates/connect-inject-deployment.yaml
  charts/consul/test/unit/connect-inject-deployment.bats
  charts/consul/values.yaml
  cli/helm/values.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/constants/constants.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration.go
  control-plane/connect-inject/lifecycle/lifecycle_configuration_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go
  control-plane/subcommand/inject-connect/command.go
  control-plane/subcommand/inject-connect/v1controllers.go
  control-plane/subcommand/inject-connect/v2controllers.go
Labels: backport/1.3.x, backport/1.4.x

#3815 NET-8594: Disable TestSyncCatalog
  acceptance/tests/sync/sync_catalog_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3893 [NET-8946 NET-8947 NET-8948] security: bump go, x/net and envoy versions
  .changelog/3893.txt
  .go-version
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3904 NET-8594: Disable TestSyncCatalogIngress
  acceptance/tests/sync/sync_catalog_test.go
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3905 Helm: support sync-lb-services-endpoints for sync catalog
  .changelog/3905.txt
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3685 Datadog Integration Acceptance Tests / Bug fixes
  .changelog/3685.txt
  acceptance/framework/config/config.go
  acceptance/framework/consul/helm_cluster.go
  acceptance/framework/datadog/datadog.go
  acceptance/framework/flags/flags.go
  acceptance/tests/datadog/datadog_test.go
  acceptance/tests/datadog/main_test.go
  acceptance/tests/fixtures/bases/datadog/datadog.yaml
  acceptance/tests/fixtures/bases/datadog/fake-intake.yaml
  acceptance/tests/fixtures/bases/datadog/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-dogstatsd-udp/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-dogstatsd-udp/patch.yaml
  acceptance/tests/fixtures/cases/datadog-dogstatsd-uds/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-dogstatsd-uds/patch.yaml
  acceptance/tests/fixtures/cases/datadog-openmetrics/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-openmetrics/patch.yaml
  acceptance/tests/fixtures/cases/datadog-otlp-grpc/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-otlp-grpc/patch.yaml
  acceptance/tests/fixtures/cases/datadog-otlp/kustomization.yaml
  acceptance/tests/fixtures/cases/datadog-otlp/patch.yaml
  charts/consul/templates/_helpers.tpl
  charts/consul/templates/server-statefulset.yaml
  charts/consul/templates/telemetry-collector-deployment.yaml
  charts/consul/test/unit/server-statefulset.bats
  charts/consul/test/unit/telemetry-collector-deployment.bats
  control-plane/cni/main.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#3918 [NET-8412] Fix APIGW policy creation ordering for upgrade path
  .changelog/3918.txt
  control-plane/api-gateway/cache/consul.go
Labels: theme/api-gateway, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3867 Add post-release changelogs
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#3873 GH-3406 - Only error for config entries from different datacenters when the config entries are different
  .changelog/3873.txt
  control-plane/controllers/configentries/configentry_controller.go
  control-plane/controllers/configentries/configentry_controller_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3921 add missing license file
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3942 Net 9069/xw add license file to all bin
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.3.x, backport/1.4.x

#3928 [NET-6466] Remove secrets from termgw role
  .changelog/3928.txt
  charts/consul/templates/terminating-gateways-role.yaml
  charts/consul/test/unit/terminating-gateways-role.bats
Labels: backport/1.3.x, backport/1.4.x, theme/terminating-gateway

#3941 NO_JIRA: Update deprecated terraform config in release branch
  charts/consul/test/terraform/eks/main.tf
  charts/consul/test/terraform/gke/main.tf
Labels: pr/no-changelog, pr/no-backport

#3949 Net 9069/add license backport 1.1.x
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3950 Net 9069/add license backport 1.2.x
  .github/workflows/build.yml
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#3948 Net 9069/fix local brokerage
  .github/workflows/build.yml
  control-plane/Dockerfile
  control-plane/LICENSE
Labels: backport/1.1.x, pr/no-changelog, backport/1.2.x, backport/1.3.x, backport/1.4.x

#3767 [NET-8091] Use file-system-certificate in Consul instead of inline-certificate
  .changelog/3767.txt
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/partitions/partitions_gateway_test.go
  control-plane/api-gateway/binding/binder.go
  control-plane/api-gateway/binding/binder_test.go
  control-plane/api-gateway/cache/consul.go
  control-plane/api-gateway/cache/consul_test.go
  control-plane/api-gateway/common/diff.go
  control-plane/api-gateway/common/resources.go
  control-plane/api-gateway/common/translation.go
  control-plane/api-gateway/common/translation_test.go
  control-plane/api-gateway/controllers/gateway_controller.go
  control-plane/api-gateway/controllers/gateway_controller_integration_test.go
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/api-gateway/gatekeeper/volumes.go
  control-plane/go.mod
  control-plane/go.sum
Labels: theme/api-gateway, pr/no-backport
