Repository hashicorp/consul-k8s, pull requests merged in 2024-07, with the labels that each got.

#4154 Update go version
  .changelog/4154.txt
  .go-version
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4152 Net 4414 remove anyuid openshift requirement
  .changelog/4152.txt
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/fixtures/bases/multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/multiport-app/kustomization.yaml
  acceptance/tests/fixtures/bases/static-client/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-client/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/kustomization.yaml
  acceptance/tests/fixtures/bases/static-server/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/static-server/kustomization.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/anyuid-scc-rolebinding.yaml
  acceptance/tests/fixtures/bases/v2-multiport-app/kustomization.yaml
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/gatekeeper_test.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/connect-inject/common/openshift.go
  control-plane/connect-inject/common/openshift_test.go
  control-plane/connect-inject/constants/annotations_and_labels.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/redirect_traffic.go
  control-plane/connect-inject/webhook/redirect_traffic_test.go
Labels: backport/1.4.x, backport/1.5.x

#4169 [NET-10454] Update go-retryablehttp
  .changelog/4169.txt
  acceptance/go.mod
  acceptance/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4175 Stage release of 1.4.4
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4177 Stage release of 1.5.1
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4178 Stage release of 1.3.7
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4167 NET-10249 - add server acl init option to create ACL role for dns-proxy
  acceptance/tests/consul-dns/consul_dns_test.go
  charts/consul/templates/server-acl-init-job.yaml
  control-plane/subcommand/server-acl-init/command.go
  control-plane/subcommand/server-acl-init/rules.go
  control-plane/subcommand/server-acl-init/rules_test.go
Labels: pr/no-changelog, pr/no-backport

#4168 Fix and re-enable catalog sync ingress acceptance test
  acceptance/tests/sync/sync_catalog_test.go
Labels: pr/no-changelog, pr/no-backport

#4190 release/1.3.x: remove v2 tests
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: pr/no-changelog, pr/no-backport

#4189 release/1.4.x: remove v2 tests 1.4
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: pr/no-changelog, pr/no-backport

#4188 release/1.5.x remove v2 tests
  acceptance/ci-inputs/kind_acceptance_test_packages.yaml
Labels: pr/no-changelog, pr/no-backport

#4176 Prep branch for future release
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4182 Prep branch for future release
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4181 Prep branch for future release
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4180 Update termgw acceptance tests
  acceptance/framework/helpers/helpers.go
  acceptance/tests/fixtures/cases/terminating-gateway-destinations/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/external-service.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/terminating-gateway/external-service.yaml
  acceptance/tests/fixtures/cases/terminating-gateway/terminating-gateway.yaml
  acceptance/tests/terminating-gateway/common.go
  acceptance/tests/terminating-gateway/terminating_gateway_destinations_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_test.go
Labels: pr/no-changelog, backport/1.5.x

#4183 Prep branch for future release
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4191 Update changelog to reflect latest patch releases
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4113 Update Error Message when Secret Reference is invalid
  control-plane/api-gateway/binding/validation.go
  control-plane/api-gateway/binding/validation_test.go
Labels: pr/no-changelog, pr/no-backport

#4184 Net 10114 consul is under resourced when deploying to crc local version of open shift
  .changelog/4184.txt
  charts/consul/templates/gateway-resources-job.yaml
  charts/consul/templates/webhook-cert-manager-deployment.yaml
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4194 Add non-code files/directories to skip for acceptance tests
  .github/scripts/check_skip_ci.sh
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#4195 update check skip ci to only run acceptance tests for code changes
  .github/scripts/check_skip_ci.sh
  .github/workflows/pr.yml
Labels: pr/no-changelog, pr/no-backport

#4204 add conditional skip and skip running tests and build if only non-cod…
  .github/scripts/check_skip_ci.sh
  .github/scripts/skip_check_ci.sh
  .github/workflows/pr.yml
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, pr/no-backport

#4205 skip ci when only non-code files are changed
  .github/scripts/check_skip_ci.sh
  .github/workflows/pr.yml
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, pr/no-backport

#4202 NET-10526 - consul-k8s - add test to ensure that the regular dns service is not deployed when dns proxy is enabled
  charts/consul/test/unit/dns-service.bats
Labels: pr/no-changelog, pr/no-backport

#4201 NET-10522 - consul-k8s - update test that makes it seem like global.enabled=false and client.enabled=true is required to enable dns proxy
  charts/consul/test/unit/dns-proxy-deployment.bats
Labels: pr/no-changelog, pr/no-backport

#4210 NET-10548 Adds image pull secrets to the gateway cleanup and gateway resources job service account
  .changelog/4210.txt
  charts/consul/templates/gateway-cleanup-serviceaccount.yaml
  charts/consul/templates/gateway-resources-serviceaccount.yaml
  charts/consul/test/unit/gateway-cleanup-serviceaccount.bats
  charts/consul/test/unit/gateway-resources-serviceaccount.bats
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#4213 Adds back manageNonStandardCRDs option to the helm chart
  .changelog/4213.txt
  charts/consul/templates/crd-tcproutes-external.yaml
  charts/consul/test/unit/crd-tcproutes-external.bats
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#4174 NET-10194 - dns proxy acceptance test for partitions
  acceptance/tests/consul-dns/consul_dns_partitions_test.go
  acceptance/tests/consul-dns/consul_dns_test.go
  acceptance/tests/consul-dns/coredns-original.yaml
  acceptance/tests/consul-dns/coredns-template.yaml
  charts/consul/templates/dns-proxy-deployment.yaml
Labels: pr/no-changelog, pr/no-backport
