Repository hashicorp/consul-k8s, pull requests merged in 2024-08, with the labels that each got.

#4223 NET-10601 - add test cases to ensure DNS proxy continues to work after pods roll
  acceptance/tests/consul-dns/consul_dns_partitions_test.go
Labels: pr/no-changelog, pr/no-backport

#4228 Update docker packages to resolve resolve-CVE-2024-41110
  .changelog/4228.txt
  cli/go.mod
  cli/go.sum
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4227 [NET-10547] openshift: re-order SCC volume list for Argo sync
  .changelog/4227.txt
  charts/consul/templates/client-securitycontextconstraints.yaml
  charts/consul/templates/cni-securitycontextconstraints.yaml
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4243 Run generators
  acceptance/tests/consul-dns/coredns-original.yaml
  acceptance/tests/consul-dns/coredns-template.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-destinations/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/external-service.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/terminating-gateway/external-service.yaml
  acceptance/tests/fixtures/cases/terminating-gateway/terminating-gateway.yaml
  hack/copy-crds-to-chart/main.go
Labels: pr/no-changelog, pr/no-backport

#4247 [NET-10731] Fix issue with nil pointer derefs when section name is not specified for GatewayPolicy
  .changelog/4247.txt
  control-plane/api-gateway/binding/validation.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#4237 NET-5272/add docs team code owners to review helm values description
  .github/CODEOWNERS
Labels: backport/1.1.x, pr/no-changelog, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4224 [NET-10567] Fix namespace normalization on external registration/ACL Setup for Terminating Gateways
  .changelog/4224.txt
  acceptance/framework/helpers/helpers.go
  acceptance/framework/k8s/deploy.go
  acceptance/go.mod
  acceptance/go.sum
  acceptance/tests/config-entries/config_entries_namespaces_test.go
  acceptance/tests/config-entries/config_entries_test.go
  acceptance/tests/fixtures/bases/external-service-registration/external-service.yaml
  acceptance/tests/fixtures/bases/external-service-registration/kustomization.yaml
  acceptance/tests/fixtures/bases/terminating-gateway/kustomization.yaml
  acceptance/tests/fixtures/bases/terminating-gateway/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/crd-peers/default-terminating-gateway/kustomization.yaml
  acceptance/tests/fixtures/cases/crd-peers/default-terminating-gateway/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/crd-peers/external-service-registration/external-service.yaml
  acceptance/tests/fixtures/cases/crd-peers/external-service-registration/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-destinations/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/all-non-default/external-service-registration/external-service.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/all-non-default/external-service-registration/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/all-non-default/terminating-gateway/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/all-non-default/terminating-gateway/terminating-gateway.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/client-non-default/static-client-inject/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/client-non-default/static-client-inject/patch.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/client-non-default/terminating-gateway/kustomization.yaml
  acceptance/tests/fixtures/cases/terminating-gateway-namespaces/client-non-default/terminating-gateway/terminating-gateway.yaml
  acceptance/tests/peering/peering_connect_test.go
  acceptance/tests/terminating-gateway/common.go
  acceptance/tests/terminating-gateway/terminating_gateway_destinations_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  acceptance/tests/terminating-gateway/terminating_gateway_test.go
  control-plane/api/v1alpha1/terminatinggateway_types.go
  control-plane/catalog/registration/cache.go
  control-plane/catalog/registration/registrations_controller.go
  control-plane/catalog/registration/registrations_controller_test.go
  control-plane/catalog/registration/result.go
  control-plane/config/rbac/role.yaml
  control-plane/controllers/configentries/configentry_controller_test.go
  control-plane/controllers/configentries/terminatinggateway_controller.go
  control-plane/subcommand/inject-connect/v1controllers.go
Labels: backport/1.5.x

#4261 make missing changes in the backport
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#4260 make missing changes in the backport
  control-plane/Dockerfile
Labels: pr/no-changelog, pr/no-backport

#4262 [release/1.1.x] config entry: add validate_clusters to mesh config entry
  .changelog/4256.txt
  Makefile
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/templates/crd-exportedservices.yaml
  charts/consul/templates/crd-ingressgateways.yaml
  charts/consul/templates/crd-meshes.yaml
  charts/consul/templates/crd-peeringacceptors.yaml
  charts/consul/templates/crd-peeringdialers.yaml
  charts/consul/templates/crd-proxydefaults.yaml
  charts/consul/templates/crd-servicedefaults.yaml
  charts/consul/templates/crd-serviceintentions.yaml
  charts/consul/templates/crd-serviceresolvers.yaml
  charts/consul/templates/crd-servicerouters.yaml
  charts/consul/templates/crd-servicesplitters.yaml
  charts/consul/templates/crd-terminatinggateways.yaml
  cli/go.mod
  cli/go.sum
  control-plane/api/v1alpha1/ingressgateway_types_test.go
  control-plane/api/v1alpha1/mesh_types.go
  control-plane/api/v1alpha1/mesh_types_test.go
  control-plane/api/v1alpha1/servicedefaults_types_test.go
  control-plane/api/v1alpha1/zz_generated.deepcopy.go
  control-plane/build-support/controller/README.md
  control-plane/build-support/controller/boilerplate.go.txt
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
  control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
  control-plane/config/rbac/role.yaml
  control-plane/config/webhook/manifests.yaml
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller.go
  control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller.go
  control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
  control-plane/connect-inject/webhook/dns.go
  control-plane/connect-inject/webhook/dns_test.go
  control-plane/go.mod
  control-plane/go.sum
  hack/copy-crds-to-chart/main.go
Labels: pr/no-backport

#4270 prepare release 1.1.15
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4272 fix consul version
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4271 prepare release 1.3.8
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4273 prepare release 1.4.5
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4212 NET-10124: Add metrics endpoint and labels to sync catalog deployment
  .changelog/4212.txt
  charts/consul/templates/sync-catalog-deployment.yaml
  charts/consul/test/unit/sync-catalog-deployment.bats
  charts/consul/values.yaml
  control-plane/catalog/metrics/metrics.go
  control-plane/catalog/to-consul/resource.go
  control-plane/catalog/to-consul/syncer.go
  control-plane/catalog/to-consul/syncer_test.go
  control-plane/catalog/to-k8s/sink.go
  control-plane/catalog/to-k8s/sink_test.go
  control-plane/controllers/configentries/configentry_controller_test.go
  control-plane/go.mod
  control-plane/subcommand/common/metrics_util.go
  control-plane/subcommand/gateway-resources/command.go
  control-plane/subcommand/sync-catalog/command.go
  control-plane/subcommand/sync-catalog/command_ent_test.go
  control-plane/subcommand/sync-catalog/command_test.go
Labels: pr/no-backport

#4266 [NET-10544] bugfix: catalog sync fails repeatedly to deregister a service in some scenarios
  .changelog/4266.txt
  control-plane/catalog/to-consul/syncer.go
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4277 Add HOST_IP environment variable to consul_dataplane_sidecar.go
  .changelog/4277.txt
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4286 [release/1.1.x] update ubi image and go-discover
  .changelog/4287.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#4290 [release/1.3.x] update ubi image and go-discover
  .changelog/4287.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#4289 [release/1.4.x] update ubi image and go-discover
  .changelog/4287.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#4288 [release/1.5.x] update ubi image and go-discover
  .changelog/4287.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#4255 remove all k8s services from consul
  .changelog/4255.txt
  control-plane/subcommand/sync-catalog/command.go
  control-plane/subcommand/sync-catalog/command_test.go
Labels: backport/1.1.x, backport/1.3.x, backport/1.4.x, backport/1.5.x

#4287 update ubi image and go-discover
  .changelog/4287.txt
  control-plane/Dockerfile
Labels: pr/no-backport

#4294 prepare 1.5.3
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4293 prepare 1.4.6
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4292 prepare 1.3.9
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4291 prepare 1.1.16
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport
