Repository hashicorp/consul-k8s, pull requests merged in 2025-08, with the labels that each got.

#4679 update: go version to 1.24.5
  .changelog/4679.txt
  acceptance/go.mod
  charts/go.mod
  cli/go.mod
  control-plane/cni/go.mod
  control-plane/go.mod
  hack/aws-acceptance-test-cleanup/go.mod
  hack/camel-crds/go.mod
  hack/copy-crds-to-chart/go.mod
  hack/helm-reference-gen/go.mod
  version/go.mod
Labels: backport/1.6.x, backport/1.7.x, backport/1.8.x

#4684 go-discover version upgrade
  .changelog/4684.txt
  control-plane/Dockerfile
Labels: backport/1.6.x, backport/1.7.x, backport/1.8.x

#4704 security: update helm.sh/helm/v3 to v3.18.5 to fix CVE
  .changelog/4696.txt
  cli/go.mod
  cli/go.sum
Labels: pr/no-backport

#4707 Prepare Release 1.6.8
  .release/security-scan.hcl
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4712 Prepare Release 1.8.1
  .release/security-scan.hcl
Labels: pr/no-changelog, pr/no-backport

#4710 update: next version in version.go
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4708 update: next version in version.go
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4706 update: next version in version.go
  charts/consul/Chart.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport
