Repository hashicorp/consul-k8s, pull requests merged in 2025-06, with the labels that each got.

#4602 update: version to next release 1.7.2 in version.go
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4598 Post release/1.7.1
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4581 update changed-files action to version 46.0.1 for CVE fix
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, backport/1.5.x, backport/1.6.x, backport/1.7.x

#4601 update: upgrade alpine version to 3.21 in Dockerfile
  control-plane/Dockerfile
Labels: pr/no-changelog, backport/1.5.x, backport/1.6.x, backport/1.7.x

#4618 Manual Backport of Add: UseSNI in remoteJWKS config in JWTProvider into release/1.7.x
  .changelog/4609.txt
  charts/consul/templates/crd-jwtproviders.yaml
  control-plane/api/v1alpha1/jwtprovider_types.go
  control-plane/api/v1alpha1/jwtprovider_types_test.go
  control-plane/config/crd/bases/consul.hashicorp.com_jwtproviders.yaml
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-backport

#4596 Increasing retry time at multiple places and force delete of consul namespace on cluster
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/openshift/basic_openshift_test.go
  acceptance/tests/openshift/openshift_test_runner.go
Labels: pr/no-changelog, backport/1.7.x

#4629 upgraded go to 1.23.10
  .changelog/4629.txt
  .go-version
  acceptance/go.mod
  charts/go.mod
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/go.mod
  hack/aws-acceptance-test-cleanup/go.mod
  hack/camel-crds/go.mod
  hack/copy-crds-to-chart/go.mod
  hack/helm-reference-gen/go.mod
  version/go.mod
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#4635 upgrade helm3 package in cli to address CVEs
  .changelog/4629.txt
  .changelog/4635.txt
  cli/go.mod
  cli/go.sum
  cli/preset/cloud_preset_test.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#4388 helm: allow configuration of container liveness and readiness probes
  .changelog/4388.txt
  charts/consul/templates/client-daemonset.yaml
  charts/consul/values.yaml
Labels: do-not-merge, backport/1.7.x

#4639 stage v1.5.9
  .release/security-scan.hcl
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport
