Repository hashicorp/consul-k8s, pull requests merged in 2025-02, with the labels that each got.

#4467 Openshift tenancy test
  acceptance/framework/consul/helm_cluster.go
  acceptance/tests/openshift/basic_openshift_test.go
  acceptance/tests/openshift/openshift_test_runner.go
  acceptance/tests/openshift/tenancy_openshift_test.go
Labels: pr/no-changelog, pr/no-backport

#4470 feat: add k8s topology zone info for nodePort service(author @kolorful)
  .changelog/4470.txt
  control-plane/catalog/to-consul/resource.go
  control-plane/catalog/to-consul/resource_test.go
Labels: pr/no-backport

#4471 [NET-11567] Update Helm Chart to allow snapshotagent to support extraVolumes and extraEnvionmentVars
  .changelog/4471.txt
  charts/consul/templates/server-statefulset.yaml
  charts/consul/values.yaml
Labels: backport/1.1.x, backport/1.4.x, backport/1.5.x, backport/1.6.x

#4478 NET-12097 Support PodSecurityAdmission at the restricted level
  .changelog/4478.txt
  acceptance/framework/k8s/deploy.go
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  charts/consul/templates/mesh-gateway-deployment.yaml
  control-plane/api-gateway/gatekeeper/dataplane.go
  control-plane/api-gateway/gatekeeper/deployment.go
  control-plane/api-gateway/gatekeeper/init.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
  control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-backport
