Repository hashicorp/consul-k8s, pull requests merged in 2025-05, with the labels that each got.

#4554 changing CODEOWNERS and skipping CODEOWNERS from PR check
  .github/CODEOWNERS
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, pr/no-backport

#4557 Update file skip logic and simplify CODEOWNERS config
  .github/CODEOWNERS
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, backport/1.4.x, backport/1.5.x, backport/1.6.x, backport/1.7.x

#4556 Post release 1.7.0
  .release/security-scan.hcl
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4562 Update file skip logic and simplify CODEOWNERS config (#4557)
  .github/CODEOWNERS
Labels: pr/no-changelog, pr/no-backport

#4563 Update file skip logic and simplify CODEOWNERS config (#4557)
  .github/CODEOWNERS
Labels: pr/no-changelog, pr/no-backport

#4564 Update file skip logic and simplify CODEOWNERS config (#4557)
  .github/CODEOWNERS
Labels: pr/no-changelog, pr/no-backport

#4565 fixed charts after last release
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4568 fixed charts after last release
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4567 fixed charts after last release
  charts/consul/Chart.yaml
  charts/consul/values.yaml
Labels: pr/no-changelog, pr/no-backport

#4570 update base image for ubi9-minimal for fixing sec vulns
  .changelog/4570.txt
  control-plane/Dockerfile
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#4575 update ubuntu version for build workflow as 20.04 is deprecated in GH
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.6.x

#4578 (fix build action) updating go version to match go toolchain version in mod files
  .go-version
Labels: pr/no-changelog, pr/no-backport

#4584 Preparation for release 1.7.1
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4583 Preparation for release 1.6.5
  CHANGELOG.md
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4585 Preparation for release 1.7.1
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#4576 Fixing multiple flaky test failures due to timeout, version updates, script changes
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
  acceptance/tests/api-gateway/api_gateway_tenancy_test.go
  acceptance/tests/connect/connect_proxy_lifecycle_test.go
  acceptance/tests/consul-dns/consul_dns_test.go
  acceptance/tests/sameness/sameness_test.go
  charts/consul/test/terraform/aks/main.tf
  charts/consul/test/terraform/aks/variables.tf
  charts/consul/test/terraform/eks/main.tf
  charts/consul/test/terraform/eks/variables.tf
  charts/consul/test/terraform/gke/main.tf
  charts/consul/test/terraform/gke/variables.tf
Labels: pr/no-changelog, pr/no-backport

#4586 Preparation for release 1.7.1
  .github/workflows/build.yml
  .github/workflows/reusable-conditional-skip.yml
Labels: pr/no-changelog, pr/no-backport
