Repository hashicorp/consul-k8s, pull requests merged in 2025-03, with the labels that each got.

#4486 upgraded go version to 1.23.6
  .changelog/4486.txt
  .github/workflows/lint.yaml
  .go-version
  .golangci.yml
  acceptance/go.mod
  charts/go.mod
  cli/go.mod
  control-plane/Dockerfile
  control-plane/cni/go.mod
  control-plane/go.mod
  hack/aws-acceptance-test-cleanup/go.mod
  hack/camel-crds/go.mod
  hack/copy-crds-to-chart/go.mod
  hack/helm-reference-gen/go.mod
  version/go.mod
Labels: pr/no-backport

#4489 added workflow file for 1.7.x branch
  .github/workflows/weekly-acceptance-1-7-x.yml
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4488 prepping for 1.7.0-rc release
  .github/workflows/weekly-acceptance-1-7-x.yml
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4490 fixed CVEs
  .release/security-scan.hcl
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4492 fixed CVEs
  .release/security-scan.hcl
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: pr/no-changelog, pr/no-backport

#4493 CVE fix release 1.7.0 rc1
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
Labels: pr/no-changelog, pr/no-backport

#4483 PSA Acceptance Tests
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/api-gateway/gatewayclassconfig.yaml
  acceptance/tests/fixtures/bases/static-client/deployment.yaml
  acceptance/tests/fixtures/bases/static-server-https/deployment.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/deployment.yaml
  acceptance/tests/fixtures/bases/static-server/deployment.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/api-gateway.yaml
  acceptance/tests/fixtures/cases/static-server-inject/patch.yaml
  acceptance/tests/partitions/partitions_gateway_test.go
  acceptance/tests/peering/peering_gateway_test.go
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, backport/1.7.x

#4497 Backport of PSA Acceptance Tests into release/1.7.x
  acceptance/tests/api-gateway/api_gateway_external_servers_test.go
  acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go
  acceptance/tests/api-gateway/api_gateway_test.go
  acceptance/tests/fixtures/bases/api-gateway/gatewayclassconfig.yaml
  acceptance/tests/fixtures/bases/static-client/deployment.yaml
  acceptance/tests/fixtures/bases/static-server-https/deployment.yaml
  acceptance/tests/fixtures/bases/static-server-tcp/deployment.yaml
  acceptance/tests/fixtures/bases/static-server/deployment.yaml
  acceptance/tests/fixtures/cases/api-gateways/jwt-auth/api-gateway.yaml
  acceptance/tests/fixtures/cases/static-server-inject/patch.yaml
  acceptance/tests/partitions/partitions_gateway_test.go
  acceptance/tests/peering/peering_gateway_test.go
  acceptance/tests/wan-federation/wan_federation_gateway_test.go
  control-plane/connect-inject/webhook/container_init.go
  control-plane/connect-inject/webhook/container_init_test.go
Labels: pr/no-changelog, pr/no-backport

#4502 fixed CVEs
  .changelog/4502.txt
  acceptance/go.mod
  acceptance/go.sum
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#4510 prepare release for 1.4.9
  .github/workflows/lint.yaml
  .go-version
  .golangci.yml
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  control-plane/subcommand/sync-catalog/command.go
  control-plane/tenancy/namespace/namespace_controller_test.go
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4500 prepare for release 1.5.6
  .github/workflows/lint.yaml
  .go-version
  .golangci.yml
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  control-plane/tenancy/namespace/namespace_controller_test.go
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4501 Prepare for release 1.6.3
  .github/workflows/lint.yaml
  .golangci.yml
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  charts/consul/values.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  version/version.go
Labels: pr/no-changelog, pr/no-backport

#4512 CVE fixes
  cli/go.mod
  cli/go.sum
Labels: pr/no-changelog, pr/no-backport

#4511 CVE fixes
  cli/go.mod
  cli/go.sum
Labels: pr/no-changelog, pr/no-backport

#4513 update go version
  .go-version
Labels: pr/no-changelog, pr/no-backport

#4515 Post release 1.5.6
  .github/workflows/lint.yaml
  .go-version
  .golangci.yml
  CHANGELOG.md
  acceptance/go.mod
  acceptance/go.sum
  charts/consul/Chart.yaml
  cli/go.mod
  cli/go.sum
  control-plane/cni/go.mod
  control-plane/cni/go.sum
  control-plane/go.mod
  control-plane/go.sum
  control-plane/tenancy/namespace/namespace_controller_test.go
  version/version.go
Labels: pr/no-changelog, pr/no-backport
